### ISSUE TITLE
I want to use .html file in sites folder instead of .md file for changes.

### ISSUE THREAD

**Issue by raman-maker** [tlienart/Franklin.jl#1029]
I have now learn making changes in live server website by doing changes in .html files inside sites folder so i want that website should from .html file and fro .md file on restarting live server.I want to use .html file in sites folder instead of .md file for changes. Now i understand that .html files are better way to make desired changes in website. What should i do to make make .html files as default source for website ? I tried to remove unnecessary reference attachments in h1 and h2 headings but on restarting live server they again come back

**Comment by tlienart** [comment]
Sorry I don't understand your question. 

If you place `.html` files in your root folder, these will be served normally. For instance:

```
yourFolder
├── _assets
├── utils.jl
├── _layout
├── config.md
├── _rss
├── _libs
├── index.md
├── 404.md
├── Project.toml
├── foo.md                     <--- this is a markdown file
├── bar.html                   <--- this is a standard HTML file
└── _css
    ├── franklin.css
    └── basic.css
```

when the output is generated you'll get something at `/foo/` (based on `foo.md`) and at `/bar/` (based on `bar.html`). 

The only difference is that `*.html` files are injected "as they are" without taking the layout into account. If you want to add elements of the layout, you have to explicitly add that in the HTML for instance with `{{insert head.html}}` etc.

Given that this is not an issue with Franklin but more with usage, I'll close this and suggest you use the Julia slack (`#franklin` channel) to get more help if you need it.
