### ISSUE TITLE
"'Closewrite' not defined" Error when using Franklin.serve()

### ISSUE THREAD

**Issue by SSShupe** [tlienart/Franklin.jl#1034]
I am using Franklin with Julia 1.9.2 on Debian. When I follow the instructions on the main Franklin site, the site files are generated, but when I open a browser on localhost:8000, nothing shows, and I get the following error:

```
julia> using Franklin

julia> newsite("SSS"; template="vela")
✓ Website folder generated at "SSS" (now the current directory).
→ Use serve() from Franklin to see the website in your browser.

julia> serve()
  Activating project at `~/Franklin/SSS`
→ Initial full pass...
→ evaluating code [ex3] in (menu1.md)                                                                                                                                                  → Starting the server...
✓ LiveServer listening on http://localhost:8000/ ...
  (use CTRL+C to shut down)
WARNING: both IOExtras and Base export "closewrite"; uses of it in module ConnectionPool must be qualified
WARNING: both IOExtras and Base export "closewrite"; uses of it in module Servers must be qualified
┌ Error: error handling request
│   exception =
│    UndefVarError: `closewrite` not defined
│    Stacktrace:
│     [1] macro expansion
│       @ ~/.julia/packages/HTTP/RwjlP/src/Servers.jl:403 [inlined]
│     [2] (::HTTP.Servers.var"#13#14"{LiveServer.var"#16#21"{HTTP.Handlers.RequestHandlerFunction{LiveServer.var"#14#19"{typeof(identity), Bool, Bool, LiveServer.SimpleWatcher}}}, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})()
│       @ HTTP.Servers ./task.jl:514
└ @ HTTP.Servers ~/.julia/packages/HTTP/RwjlP/src/Servers.jl:405
```
(The error repeats multiple times, but it's always the same.) I've used Franklin before and never seen this error before. I'm not sure if it's a Franklin error or something screwy with the HTTP package.

Any help would be appreciated. Thanks.

**Comment by SSShupe** [comment]
The error does affect the output. When I open localhost:8000 with the browser I get nothing (opening the browser also seems to be what triggers the error). It doesn't seem to actually crash the server, though; I have to use Ctrl-C to terminate it.

I'm going to nose around and see if I can find a workaround.

**Comment by SSShupe** [comment]
Well, I'm not sure why, but everything is working now. One of these mysteries of computing. Perhaps a bad sprite had infested my computer last time. I'll let you know if the problem reappears.

**Comment by tlienart** [comment]
So FYI I'm aware of this kind of problem popping up when eg:

1. Start the server and go to a browser tab
2. Kill it
3. Restart it and refresh a pre-existing browser tab

This will typically show errors probably because the socket was dropped and then reopened (or something magical of the sort)

Same kind of stuff can happen when using several browsers and using different tabs and, again, refreshing stuff around the time a server is restarted.

If you happen to recreate the problem and got to it via another route, let me know, it's always useful!
