### ISSUE TITLE
Draft Mode using a Local Variable

### ISSUE THREAD

**Issue by limarta** [tlienart/Franklin.jl#1044]
Often when writing blog posts, we need a way to store drafts but hide them during deployment. Currently in Franklin.jl, it is possible to add a file to `ignore` in `config.md` to skip the file during the build process. However, this also means `serve()` will also not display the file. It would be helpful to have a "draft" mode that suppresses pages only at deployment time with a `draft=true` local variable set. Now if a user wishes to continue editing the page locally, calling `serve()` locally will still display the page.

Example:
```
+++
draft = true
+++

# This is a post currently being written but not yet for deployment

Partial content...
```

**Comment by tlienart** [comment]
I'm supportive of this, it should be a small addition to be added both here and there: https://github.com/tlienart/Xranklin.jl/issues/254
