### ISSUE TITLE
nested loops

### ISSUE THREAD

**Issue by Krastanov** [tlienart/Franklin.jl#1046]
I have a Jekyll website that heavily uses nested loops over complicated page variables as a way to generate a page. I was surprised to see that does not work in Franklin. What is the idiomatic way to do the following (pseudocode):

```
# file utils.jl

myvariable_d = [Dict("a"=>[1,2]),Dict("a"=>[3,4])]
myvariable_v = [[1,2],[3,4]]
```

```
# file homepage.md

{{for group in myvariable_d}}
{{for i in group["a"]}}
## {{fill i}}
{{end}}
{{end}}

{{for group in myvariable_v}}
{{for i in group}}
## {{fill i}}
{{end}}
{{end}}
```

**Comment by tlienart** [comment]
As soon as you have complexity like this you should move the logic to a hfun and just write Julia code for it.

The next version will allow for a bit more flexibility in these things but the purpose is just to be more consistent, not to allow gradually more complex logic in a kind of specialised DSL like in Hugo.

**Comment by Krastanov** [comment]
Thanks! Closing the issue, but feel free to move it to discussion or QnA if appropriate.
