### ISSUE TITLE
XML prolog lost from RSS template

### ISSUE THREAD

**Issue by McSinyx** [tlienart/Franklin.jl#1057]
I want to make the feed human readable asking the browser to apply some XSLT, e.g. in `_rss/head.xml`

    <?xml-stylesheet type="text/xsl" href="/assets/feed.xslt"?>

However, this line isn't present in the output feed.

**Comment by tlienart** [comment]
this

https://github.com/tlienart/Franklin.jl/blob/fde286de36e4fd1037dbf24e3dfc73c3f52675ad/src/manager/rss_generator.jl#L86-L90

is the likely culprit 

Could you:

1. copy paste the content of your `_rss/head.html` here
2. show the head of the generated rss file that you got?

**Comment by McSinyx** [comment]
I cannot reproduce this, I think I followed the link to the production feed (and not the newly generated one).  Sorry for the noise :sweat_smile:
