### ISSUE TITLE
FR: Button to copy code blocks to clipboard

### ISSUE THREAD

**Issue by IanButterworth** [tlienart/Franklin.jl#1064]
It's quite standard for code blocks to have copy to clipboard buttons, it'd be nice to have it on places like the julialang.org website.

**Comment by tlienart** [comment]
See https://franklinjl.org/demos/#010_clipboard_button_for_code_blocks 

A button to copy code is typically done in javascript and as such is left for the user to handle. The example above shows how to use a common JS package to do that, there are other ways including raw JS: https://www.phind.com/search?cache=iko4c6uizwpacuq7ceix74e7.
