### ISSUE TITLE
May insert variable value into a HTML tag attribute?

### ISSUE THREAD

**Issue by zfengg** [tlienart/Franklin.jl#1065]
For example, may I insert the value of a local variable ``descr = "Homepage of A Group"`` into the HTML meta tag like ``<meta property="og:description" content= $descr >``?

**Comment by tlienart** [comment]
in your case, `descr` seems like a global variable in which case you'd put that in `config.md` and do:

```html
<meta property="og:description" content="{{ descr }}" >
```

which will then show on all pages

if you do want this only on a single page, set the default value in `config.md` to empty `descr = ""` then on any page you want a specific value `descr = "..."` and in layout:

```
{{isnotempty descr}}
  <meta property="og:description" content="{{ descr }}" >
{{end}}
```

**Comment by zfengg** [comment]
Thank you for the clear explanation. It works! Now I see that the underlying pipeline deals with all the 
```
{{ ... }}
```
and there is no difference in their positions in the pre-produced HTML.
