### ISSUE TITLE
Pagevariables not always available?

### ISSUE THREAD

**Issue by kellertuer** [tlienart/Franklin.jl#1081]
I ran into an interesting problem, which I think even started with the last beaking change – but not only did I have to find time to narrow it down, it is also a bit complicated to describe.

## Status
Currently when running Franklin locally (seems fine on CI) on Avery _first_ run I got an error, but when just (in the same environment) running it again, it was fine.
The error message was, that some of my page vars seem to be nothing, but I could not narrow that down. Until today.

In the folder https://github.com/kellertuer/kellertuer.github.io/tree/master/projects I use the page-variables to store metadata about the projects. Now the code loading them is 

https://github.com/kellertuer/kellertuer.github.io/blob/32a223db8fcc907fb6ad67523ef72f77cab318a1/utils.jl#L17-L29

Where I mainly crawl the folder and for every file I read the metadata into a large dict. For two of the projects ( https://github.com/kellertuer/kellertuer.github.io/blob/master/projects/mvirt.md and https://github.com/kellertuer/kellertuer.github.io/blob/master/projects/secondordertv.md ) being `nothing`) besides the title for the first.
This also caused the errors, since I assumed that the `start` is always a proper date. Which then it was not for these two.

So: What might be reasons for these two files to not be able to load the `pagevars`? Is that a bug in Franklin or a problem on my side ;) ?

**Comment by kellertuer** [comment]
Addon: As far as I can see, there seems to be an upper bound of variables being loaded? It always affects the last two files in the folder.

If I rename, e.g. `graph-laplace.md` to `xgraphlaplace.md` it is the one without pagervars. So is there maybe an global user bound how many can be accessed also maybe in the one loop that I do?

**Comment by bhvieira** [comment]
I have been suffering from something similar for a while now. At https://bhvieira.github.io/blog/ in the deployment the pagevars for posts from 2020 are not retrieved correctly (this works flawlessly in local)

**Comment by bhvieira** [comment]
This was corrected with a `@delay` macro

**Comment by kellertuer** [comment]
Can you make that a bit more precise where you put that and how `@delay` works there?

**Comment by bhvieira** [comment]
See https://github.com/bhvieira/bhvieira.github.io/blob/f18577b8cd749ceb6002171edfc7b30ce4af9526/utils.jl#L26

**Comment by kellertuer** [comment]
Thanks, will try that on my function later as well then.

**Comment by kellertuer** [comment]
Ah, works great! Thanks for finding that out.

**Comment by bhvieira** [comment]
Glad to hear!
