### ISSUE TITLE
Optional CSS inlining

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#127]
It may be good to try to inline the CSS in the optimize phase and just put everything in a `<style>..</style>`. Maybe try to do this either before or after the minification and see what works best.

It should be optional bc while for simple CSS this will likely not be a problem, if the CSS is quite heavy (e.g. Tufte + KaTeX + ... ) then in fact it might not help much. Maybe just try and see...

**Comment by zdroid** [comment]
This should definitely not be implemented. Inlining CSS is a practice that's frowned upon, as it is harder to maintain such web pages.

**Comment by tlienart** [comment]
Yeah I agree with this, let's not do it, thanks for chipping in!
