### ISSUE TITLE
Import script with JL functions

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#330]
Using Julia within the markdown is useful for a [number of things](https://tlienart.github.io/JuDocWeb/pub/code/eval-tricks.html), generally it may be useful to have evaluated code blocks that don't appear on the  page but that define functions that are used elsewhere, e.g. in a `@def`. 

One way to do  this is to have  a  command `\import{utils.jl}` which would do just that.

The advantage is that `utils.jl` can then be developped and tested as standard Julia which is  less error-prone; further the function(s) can be re-used easily.

**Edit**: now all pages are modules, so this could be achieved by making config.md be a parent module for all other modules...

**Comment by Wikunia** [comment]
This can be related: Currently it is not possible to use input variables inside `\ouput` or `\textoutput`, right?
Would like to have something like this:
```
``julia:add(d, e)
#hideall
println(d+e)
``
\textouput{add(1,2)}
```

**Comment by tlienart** [comment]
oh wow, no that's not directly possible yet. Would you mind telling me your use case? maybe that could be a nice thing to add.

The syntax would have to be different though, at the moment the `julia:XXXX` gives the name of the  script where the code is written, this allows to not re-run the code every time `serve` is called even across sessions. 

Maybe something that would resemble what you're suggesting is

`````markdown
@def va = 5
@def vb = 7

```julia:ex
#hideall 
println(locvar("va")+locvar("vb"))
```
\output{ex}
`````

I actually have  this working on a local branch, the only change required to make this work is to have `Franklin.locvar` made available to page module which is trivial. 

If you were thinking of something else / this doesn't fit the bill, maybe explain your use case and I'll try to  see how we could tackle it

**Comment by Wikunia** [comment]
In my blog I want to showcase the changes I made to some code and currently (not using Franklin) I link to a GitHub site where the changes are listed and post the current code into the blog. What I would like to do ist to write in my blog:
`\textoutput{showdiff("https://github.com/Wikunia/ConstraintSolver.jl/blob/eef86f17fcb92648c1836fd195e3fbc5c96bc974/src/ConstraintSolver.jl#L58-L65, https://github.com/Wikunia/ConstraintSolver.jl/blob/afb3f66eca883db3770beacd5d09cbb5ba908ba2/src/ConstraintSolver.jl#L57-L65"; diff_type=:line)}` 

Which would then run the `showdiff` function which I maybe define in `config.md` or somewhere else and returns back a nice diff code with the changes or if `diff_type=:side` a side by side table. Just as an example probably it should return both line diff and side diff and show the appropriate one based on mobile or desktop devices but that's far outside this issue :laughing:

**Comment by Wikunia** [comment]
Syntax wise I think it would be even better to call it like I can call the latex commands with
```
\showdiff{before}{now}
```

**Comment by tlienart** [comment]
Ok nice I think that's clear. Actually  that's already  possible as  well, consider the simple example below with an "add" function but your example is just with  a more complicated `my_add` which would be your diff function:

`````markdown
```julia:init
#hideall
myadd(x, y) = x + y
```


\newcommand{\add}[2]{
```julia:ex000
#hideall
myadd(#1,#2)
```
\show{ex000}
}


\add{2}{3}
`````

Note: here I use `\show` which shows STDOUT + displays the result of  the cell (which here is what I want), if you only want STDOUT (e.g. you're using `println` statements) then use `\output` or, indeed, `\textoutput` if you want it to be reprocessed.

Let me know how you get on, that could be a nice example to add to the tricks

**Comment by tlienart** [comment]
**Important note**, the replacement with `#1, #2` is a literal replacement, so  you will need to add `\"` for paths, something like

`````markdown
\newcommand{\showdiff}[2]{
```julia:ex000
#hideall
your_showdiff("!#1","!#2")
```
\show{ex000}
}
`````

note the `!` as well to avoid a  space being placed left of the insertion so that if you use `\showdiff{foo/bar, foo/baz}` it will internally  call `your_showdiff("foo/bar", "foo/baz")`.

**Comment by Wikunia** [comment]
Thanks for the fast reply. I think you have to write `\showdiff{foo/bar}{foo/baz}`, right?
Additionally is there a way to always reload a code block? It's a bit tedious to change a code block and have to restart the server to make it available. Maybe add another `# eval_always` or so to the code block. Otherwise it seems to work fine. Thanks!

**Comment by tlienart** [comment]
> Thanks for the fast reply. I think you have to write `\showdiff{foo/bar}{foo/baz}`, right?

yep  sorry, fixed

> Additionally is there a way to always reload a code block? It's a bit tedious to change a code block and have to restart the server to make it available.

use `@def reeval=true` on the page. All code blocks on that page will be re-evaluated on  every  build.

**Comment by tlienart** [comment]
This is now allowed via `utils.jl` in particular pertaining to @Wikunia's questions:

```julia
function lx_showdiff(com, _)
    # keep this first line
    brace_content = Franklin.content(com.braces[1]) # input string
    # Now do whatever you want with the content:
    before, after = split(brace_content, ',')
    # do stuff with before and after and return whatever you want
    return uppercase(before) * lowercase(after)
end
```

**Comment by Wikunia** [comment]
Thank you :grinning: 
Can you clarify some things?
- They all need the naming convention `lx_NAME_OF_FUNCTION`? 
- Does the `_` has any meaning?
- Is there a `utils.jl` which can be used? I don't find any in my folder.

**Comment by tlienart** [comment]
Hello @Wikunia sorry for being a bit quick here. You can read more in the [NEWS](https://github.com/tlienart/Franklin.jl/blob/master/NEWS.md) it's all very fresh and I'd be happy to have feedback :) 

* just add a `utils.jl` file next to your `config.md` 
* yes if you want to define something that acts like a latex command it needs to be a function called `lx_***` if you don't like that you could call them `fname` and then just have a one liner `lx_fname = fname`.

I'll try to provide a full example in a few mins

**Comment by tlienart** [comment]
Ok so here are steps for a sandbox:

* make sure you've updated franklin
* create somewhere appropriate `newsite(".", template="sandbox")
* add a file `utils.jl` same level as the `config.md` and write

```julia
function lx_showdiff(com, _)
    # keep this first line
    brace_content = Franklin.content(com.braces[1]) # input string
    # Now do whatever you want with the content:
    before, after = strip.(split(brace_content, ','))
    # do stuff with before and after and return whatever you want
    return uppercase(before) * lowercase(after)
end
```

* change the file `index.md` for

```
@def title = "Franklin Sandbox"

Hello

\showdiff{aaaa,bbbb}
```

serve that and you'll see this

---

![Screen Shot 2020-04-13 at 11 01 51](https://user-images.githubusercontent.com/10897531/79108265-41b1b680-7d76-11ea-8e8a-aa234d576e7f.png)

**Comment by Wikunia** [comment]
Ah perfect. I looked at the docs and in the GitHub releases :smile: 
I'll have a look tmr. This looks clear to me. Are you "The Oracle"? :wink:
