### ISSUE TITLE
There was an error running the code [Plotly]

### ISSUE THREAD

**Issue by cserteGT3** [tlienart/Franklin.jl#334]
Here's a weird one from PlotlyJS. Source is the PlotlyJS [example building script](https://github.com/sglyon/PlotlyJS.jl/blob/bc4ffc16d3d03b8644e9a9dd1f2084536a9b0807/docs/build_example_docs.jl#L62)
The following works in the REPL:
```julia
julia> using PlotlyJS

julia> a = attr(t=60, b=60, l=50, r=5)
PlotlyAttribute with fields b, l, r, and t

julia>
```
However, if I want to use this in a JuDoc page like below, I get the following error:
`There was an error running the code: ErrorException("function attr does not accept keyword arguments")`.

~~~
@def title = "Issue334"
@def hasplotly = true

## Issue

This works in the REPL, and even if I copy from `assets/pages/menu9/issue334/t1.jl`.

```julia:./issue334/t1
using PlotlyJS
a = attr(t=60, b=60, l=50, r=5)
```

\textoutput{./issue334/t1}
~~~

See online [here](https://csertegt3.github.io/JuDocPlottest/pub/menu9.html) and source [here](https://github.com/cserteGT3/JuDocPlottest/blob/master/src/pages/menu9.md).

It happens with julia 1.3.1 on windows and latest tagged versions of JuDoc and PlotlyJS:
```
(JuDocPlottest) pkg> st
    Status `C:\Users\cstamas\Documents\GIT\JuDocPlottest\Project.toml`
  [4ca9428c] JuDoc v0.4.2
  [98b081ad] Literate v2.2.1
  [47be7bcc] ORCA v0.3.1
  [f0f68f2c] PlotlyJS v0.13.0
  [d330b81b] PyPlot v2.8.2
  [44d3d7a6] Weave v0.9.1
  [9a3f8284] Random
```

**Comment by tlienart** [comment]
For a reason  I don't yet fully understand, you have to  use Plotly with `import` and not with  `using` (when combined with JuDoc).  

Do 

`````markdown
@def hasplotly = true
@def reeval = true <!-- keep that once  to make sure everything is properly  re-evaluated -->
```julia:./issue334/t1
import PlotlyJS
a = PlotlyJSattr(t=60, b=60, l=50, r=5)
```
\textoutput{./issue334/t1} <!-- this is empty by the way -->
`````

Here are full examples you can imitate:  https://tlienart.github.io/JuDocWeb/pub/extras/plotly.html

(I should add explicitly in the  docs that, for now, people should use import instead of using in the plotly thing).

**Comment by cserteGT3** [comment]
Thank you!
I did miss, that `import` must be used and agree that the docs should state it explicitly.
The whole purpose was to do something like in the docs of PlotlyJS.jl, where they use the `PlotlyJS.html_body(plot)` function to insert the evaluated plots into the page. But I couldn't figure out, how could it work it with JuDoc (the following does not work, because places the plot to the bottom of the page, but I don't see the difference between their and my approach - beyond the software that processes the markdown 😄 )
~~~

## Another try

```julia:ex2
import PlotlyJS

x = y = [-2*pi + 4*pi*i/100 for i in 1:100]
z = [sin(x[i]) * cos(y[j]) * sin(x[i]*x[i]+y[j]*y[j])/log(x[i]*x[i]+y[j]*y[j]+1)
     for i in 1:100 for j in 1:100]
z_ = [z[i:i+99] for i in 1:100:10000]

data = PlotlyJS.contour(;z=z_, x=x, y=y)

plt = PlotlyJS.plot(data)
PlotlyJS.relayout!(plt, margin=PlotlyJS.attr(t=60, b=60, l=50, r=50))
html_block = PlotlyJS.html_body(plt.plot);
println("\n~~~")
#even tried to place a div block manually
println("""<div id="5578125e-fbe3-4b94-8735-4c014bbe94a3" class="plotly-graph-div"></div>""")
println("$html_block")
println("~~~\n\n\n")
```

\textoutput{ex2}
~~~

Anyway I think I'll settle with your solution, which works perfectly 👍
