### ISSUE TITLE
Highlight themes doesn't seem to work

### ISSUE THREAD

**Issue by Wikunia** [tlienart/Franklin.jl#345]
I wanted to use a dark theme for my code but somehow this does not work or I'm doing something wrong:
Changed the content of `libs/highlight/github.min.css` to a dark theme like https://raw.githubusercontent.com/highlightjs/highlight.js/master/src/styles/gruvbox-dark.css
But it looks really weird. 
![DeepinScreenshot_select-area_20200122171914](https://user-images.githubusercontent.com/4931746/72912063-5c5a2d80-3d3b-11ea-9a90-3775f340cf02.png)
Additionally I often have the problem that if I change the theme and have `serve()` running in the background that my browser says `hljs` can't be found. If I run `publish()` it fixes the issue. That's a bit weird. 
Is there something wrong with how I changed the theme?

**Comment by Wikunia** [comment]
BTW `Franklin.JD_CAN_HIGHLIGHT` returns `true`.  But even if I don't change the theme I often get: 
![DeepinScreenshot_select-area_20200122173730](https://user-images.githubusercontent.com/4931746/72913740-e1464680-3d3d-11ea-939a-248e5f3a7da8.png)
Often means: Whenever I change some `.md` file. It goes away when I restart julia and run `serve()` again or if I publish.

**Comment by tlienart** [comment]
Thanks for reporting, I'll try to build a simple example with `gruvbok-dark`, see  if I can  reproduce and let you know either way asap

**Comment by Wikunia** [comment]
Just found that there is an error in `highlight.pack.js`
Saying Unexpected token `:` unfortunately it is minified so it's hard to check. I'll try downloading my own highlight.js and put it into `libs` to see whether that works.

**Comment by tlienart** [comment]
Thanks! so yes there's a single thing I modify in the `highlight.pack` and  it's this: 

```julia
function(e) {
    return {
        c: [{
            cN: "meta",
            b: /^julia>/,
            relevance: 10,
            starts: {
                e: /^(?![ ]{6})/,
                sL: "julia"
            }
        }, {
            cN: "metas",
            b: /^shell>/,
            relevance: 10,
            starts: {
                e: /^(?![ ]{6})/,
                sL: "bash"
            }
        }, {
            cN: "metap",
            b: b: /^\(.*\)\spkg>/,
            relevance: 10,
            starts: {
                e: /^(?![ ]{6})/,
                sL: "julia"
            }
        }]
    }
}
```

this  allows to detect `pkg>` and `shell>` ; note in `"metap"` there's `b: b:`; it should only be  `b:`. I'll fix this in FranklinTemplates. Thanks for reporting!

**Comment by Wikunia** [comment]
Okay I downloaded my own version of higlight.js with support for julia in version 9.18.0 instead of 9.17 and there is no error anymore.
The wrong color comes from `src/_css/judoc.css`

**Comment by tlienart** [comment]
That makes sense, thank you for reporting. 

Some notes for the eventual full transition to Franklin (you're kind of using it at a pretty  rough period, changing name is not trivial). 

* `.jd-content` will be `.franklin-content` 
* `.jd-toc` will be `.franklin-toc`

Also  if you check internal variables like `CAN_MINIFY` they will be prceded by `FD_` instead of `JD_`. 

I'll  close this  now but feel free to reopen; the changes  corresponding to what you found will be merged  in `FranklinTemplates` 0.4.3 in a few minutes.

**Comment by Wikunia** [comment]
Trying stuff out for my blog: opensourc.es The final goal is to move everything to a new design. Currently it is just a bit getting used to it. Do you have a rough estimate when the transition will be done?

**Comment by tlienart** [comment]
Well I'm working on it right now, it's almost complete. Assuming I don't run into snags it should be finished  within the next couple of hours. Maybe follow  #340 which I'll close when I've convinced myself things work. I'll also write a small guide there for what has changed so that people can 'migrate'.

**Comment by Wikunia** [comment]
Wow nice. Maybe you can ping me here once it's done or I subscribe to releases if that helps. I'm happy to test it out then.

**Comment by tlienart** [comment]
sure I'll do that, and yes feedback is always super useful
