### ISSUE TITLE
Live-generated plotly plots don't get all the bells and whistles

### ISSUE THREAD

**Issue by platawiec** [tlienart/Franklin.jl#348]
Currently the issue can be seen on the Franklin page with plotly, where the "Off-line" generated plot can zoom in/out, hover over values, etc., whereas the "On-line" generated example doesn't do anything. One difference I noted is that the "Off-line" example appears in a code block, but this is above my depth to debug in more detail. I was able to reproduce this in my own examples, however. If there is a way to "escape" the auto-generated output code block, then it would be helpful to demonstrate that as well.

https://tlienart.github.io/franklindocs/pub/extras/plotly.html

**Comment by tlienart** [comment]
Hello Pawel,

I'm  sorry I can't reproduce the  problem, on the link you quote and  the  first plot I can  hover  over value, zoom in  and out etc. ? maybe I misunderstood your issue

<img width="860" alt="Screen Shot 2020-01-26 at 10 53 12" src="https://user-images.githubusercontent.com/10897531/73133525-1dbdbf00-402a-11ea-8214-7330f44ec85f.png">
<img width="847" alt="Screen Shot 2020-01-26 at 10 53 47" src="https://user-images.githubusercontent.com/10897531/73133527-2615fa00-402a-11ea-8276-05f9802f04dd.png">

Could you help me with a step-by-step of what you'd like to do in a scenario that works (even outside of Franklin) and one where using Franklin makes it not work?





> If there is a way to "escape" the auto-generated output code block, then it would be helpful to demonstrate that as well.

Sorry I also don't get what you mean here? What would you like to see  as  output? the plotly code?

**Comment by platawiec** [comment]
Sorry for being unclear. I can confirm the first plot of the page works, but the second plot (the "live-generated plot") doesn't work. I can't pan, compare points, or zoom in/out etc. on it. It looks like below for me.

![image](https://user-images.githubusercontent.com/24233125/73135334-d7a73200-400e-11ea-8a1a-9eb2dfd99539.png)

My workflow is:

1. Write Literate script with `fdplotly` function recommended in docs. I make plots via `PlotlyJS` and use `fdplotly` where necessary.
2. Write the markdown page the Literate script is embedded in, with a `\literate{/scripts/script.jl}` line
3. Wait for the code to run and look at the page via `serve()`.

In my own example, I see the exact same issue as the second plot in the docs

**Comment by tlienart** [comment]
Ok yes thanks a lot for the clarifications and apologies for the issue; I'll try to track down what exactly may be causing this, I suspect it's just me who made poor usage of Plotly so it hopefully shouldn't be too hard to fix

**Comment by tlienart** [comment]
Looks like the problem is caused by extra `<pre><code>` and `</code></pre>` being added around the plot:

```
<pre><code>
	<div id="jdpcao" style="width:600px;height:350px;"></div>
	<script>
        var fig = JSON.parse('{"layout":{"margin":{"l":50,"b":50,"r":50,"t":60},"title":"Basic Contour Plot"},"data":[{"type":"contour","z":[[10.0,5.625,2.5,0.625,0.0],[10.625,6.25,3.125,1.25,0.625],[12.5,8.125,5.0,3.125,2.5],[15.625,11.25,8.125,6.25,5.625],[20.0,15.625,12.5,10.625,10.0]]}]}');
        CONTAINER = document.getElementById('jdpcao');
        Plotly.plot(CONTAINER, fig.data, fig.layout);
	</script>
</code></pre>
```

removing those does the job. I need to figure out why they were added in the first  place  but hopefully that shouldn't be too difficult to figure out and fix. 

Thanks  a lot for reporting!

**Comment by tlienart** [comment]
Now  fixed: https://tlienart.github.io/franklindocs/pub/extras/plotly.html#live-generated_plot 

The  helper function `fdplotly` is now part of Franklin as it seemed useful.  Thanks again for reporting!
