### ISSUE TITLE
NEWS.md + slack channel + announcement of  0.6

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#354]
since it seems that there's a few people now using Franklin for their website (🎉 ) maybe it'd be a good idea to

- add a `NEWS.md` keeping track of breaking changes and what to do about them (*)
- open a slack channel

(*) so far there's been few because the exposed part of Franklin is very limited but now with the improvement of the code evaluation & the pending re-structuring of how the site folder is organised, there will be a couple of such changes.

**Comment by cormullion** [comment]
You were also going to re-announce it at some point? - I suppose it doesn’t hurt to keep it in view, there’s always new people joining the Julia community.

**Comment by tlienart** [comment]
Yes, I want to get #335 in first then will announce. Thanks!

**Comment by tlienart** [comment]
OK 0.6 is out, NEWS.md is here, Slack channel  could be created in some near future.

@ usual folks, if you're upgrading to 0.6 and currently have a working website, please add

```markdown
@def folder_structure = v"0.1"
```

to your config.md file so that the  new release doesn't break your stuff. The `NEWS.md` explains how to migrate (unfortunately it requires a bit of work but I think it's for the best).

If your website is currently well ranked or linked by other people, you may want to add redirect pages if you decide to migrate.

**Comment by cormullion** [comment]
Cool stuff! The Slack channel is already a thing... :)

**Comment by tlienart** [comment]
Oh man, thanks! :heart:
