### ISSUE TITLE
\begin{align*} not accepted

### ISSUE THREAD

**Issue by theogf** [tlienart/Franklin.jl#368]
Hey! Just started to use Franklin and so far it looks super easy in the first steps! 
I just noticed that \begin{align*} \end{align*} was not working, it would be nice to be able to not have numbers on every equation :)

**Comment by tlienart** [comment]
Oh, you can specify this in the CSS! 

Just head to `_css/franklin.css` and remove the `katex-display::after`.

You can also build a simple way to disable all numbering in a specified bracket:

```
This is numbered
$$ 1+1 = 2 $$
@@no-number
$$ 2+2 = 4
and
$$ 3+3 = 7-1 $$
@@
Numbered again
$$ 7 + 1 = 8 $$ 
```

in the CSS add: 

```css
.no-number .katex-display::after {
  counter-increment: nothing;
  content: "";
}
```

PS: I know it's tempting to just write LaTeX in there but there's only a basic correspondence, it's not pandoc :) the "LaTeX" commands are more there to help you define and use your own commands.

**Comment by tlienart** [comment]
Ps: it would be easy to basically just define what you're suggesting by mixing what I'm saying above:

In `config.md`
```
\newcommand{\nalign}[1]{@@no-number \begin{align}#1\end{align}@@}
```

and then

```
\nalign{3+3}
```

(of course you could do this differently or name it differently)

**Comment by tlienart** [comment]
I'll  close this now but please re-open if you have suggestions or other questions
