### ISSUE TITLE
Ignoring a folder

### ISSUE THREAD

**Issue by Wikunia** [tlienart/Franklin.jl#376]
Currently I have a folder which holds some information for plugins I wrote. That was no problem before as only the `pages/` folder was used for serving the page but now Franklin checks every folder and tries to serve it. As mentioned in slack I can move the folder to `_assets` but in general it might be a nice idea to ignore certain folders using a `@def ignore_folders` or something like that.

**Comment by Wikunia** [comment]
By ignoring I also mean that it will not copied over to `__site` which is currently the case when having it in `_assets`.

**Comment by MarcMush** [comment]
or maybe a `.fdignore` file, similar to a `.gitignore`

**Comment by Wikunia** [comment]
The `@def ignore` doesn't seem to work anymore.
Have you changed the structure somehow? 
I have `@def ignore = ["git-repos/"]` in my `config.md` but when I run `serve()` I get an error that I have 
```
``@docs 
....
``
``` in one of the files inside that folder.  (`` -> 3 of them but can't show that here I think :smile: )
I can even specify the complete path to the file in `@def ignore` but still get an error.

All I did was:
```
] add Franklin
using Franklin
serve()
```
in the root directory.

Thanks in advance!

**Comment by Wikunia** [comment]
Okay there is more wrong. I think the entire `config.md` is ignored. Everything I defined in there is not useable. For example I have
```
\newcommand{\note}[1]{@@note @@title ⚠ Note@@ @@content #1 @@ @@}
```

and in one of my posts:
```
\note{...}
```

and get the error

```
Franklin.LxComError("Command '\\note' was used before it was defined.")
```

**Comment by tlienart** [comment]
Do you have a repo with the code somewhere? it might be helpful. The `config.md` should definitely not be ignored.

**Comment by Wikunia** [comment]
Not at the moment but I'll create it on GitHub and invite you.

**Comment by Wikunia** [comment]
You should have an invite now. The ignore folder is also in gitignore but you can just create a folder `git-repos` with a `.md` file and some markdown error inside :smile:

**Comment by tlienart** [comment]
Yeah so the issue was with comment lines like `<!---------------------` which are now forbidden, this `<!-- ---------------` (note the whtiespace) is allowed. Closing now (see PR in your repo  @Wikunia ).

**Comment by Wikunia** [comment]
Perfect thanks. Additionally you probably want to add `ignore` to the documentation. Haven't found it there.

**Comment by tlienart** [comment]
yeah it's on the (ever longer) list of things to add to the docs: https://github.com/tlienart/Franklin.jl/issues/323
