### ISSUE TITLE
Relative path for images in subfolders

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#377]
If a user is on page `/blog/kaggle/index.md` and tries to do `\fig{./img.png}` the image will be searched for in `/assets/blog/kaggle/index/` instead of `/assets/blog/kaggle/`

**Comment by Wikunia** [comment]
Would it be possible to also have it work for normal markdown syntax? `![kaggle image](./img.png)` ?
Currently the relative path doesn't seem to work if written like this.

**Comment by tlienart** [comment]
I'm reluctant to do this as it may just cause confusing behaviour for users who would be migrating from the likes of Jekyll, as much as possible I'd like to have the base markdown -> html follow standard-ish conventions and everything else be commands so that it's clear that the behaviour is different.

Btw if you're tired of writing `\figalt` or would like something more convenient to write, you can always define your own for instance `\fa{1}{2}` :)

**Comment by Wikunia** [comment]
I see. Understandable yeah I think moving my blog over to Franklin needs me to do some changes to every post anyway so this shouldn't be a big deal. Thanks and keep up your awesome work!

**Comment by tlienart** [comment]
Thanks for the feedback!
