### ISSUE TITLE
Improve GitHub deployment

### ISSUE THREAD

**Issue by Keno** [tlienart/Franklin.jl#379]
I tried out Franklin today (https://github.com/JuliaPackaging/binarybuilder.org). I didn't end up using much of Franklin's feature set, but what I did use worked flawlessly, which is no small thing for a new package, so congratulations :).

I do have some thoughts on improving the deployment workflow (I've tested this out on the above repo and it seems to work well):

1. Use a deploy key rather than a personal access token

Personal access tokens are account scoped rather than repository scoped. This may not be a problem for personal sites, but for organizations I can't put my personal access tokens in the secrets since it would give everybody in the org access to all my repos. Luckily the github action used for deployment already supports deploy keys, so it's just a matter of updating the docs.

2. Generate the __site as part of the deploy

It looks like at the moment Franklin expects the user to generate the __site locally. This is not a great workflow, since it'll prevent merged pull requests from being automatically deployed unless the PR includes the regeneration. I see there's #362 for this already, but everything I'm doing in https://github.com/JuliaPackaging/binarybuilder.org could probably be bundled into a standalone action provided by this repo that can then just be installed. I'm sure our resident github actions expert @DilumAluthge would be happy to help out.

**Comment by tlienart** [comment]
Ok this was super helpful, thanks so much, I was wondering about external dependencies for the pre-rendering but GitHub actions makes that super easy to manage. 

I'll do a bit more testing with the DEPLOY_KEY thing and assuming everything works seamlessly will add that soon.

**Comment by tlienart** [comment]
Now done in #390 which will be rolled out in the docs soon
