### ISSUE TITLE
Loop template inside a condition template cause error

### ISSUE THREAD

**Issue by ndgnuh** [tlienart/Franklin.jl#380]
## Issue 
Some of the pages won't have tags (search or home page...), so tags won't be defined. This code will cause `Franklin.HTMLBlockError("I found a lonely {{end}}.")`. 
```
{{ isdef tags }}
    {{for tag in tags}}{{fill tag}}{{end}}
{{end}}
```

## Current workaround
Use another file `taghead.html`
```
{{ isdef tags }}
    {{ insert taghead.html}}
{{ end }}
```

Insde taghead.html 
```
{{ for tag in tags }}{{fill tag}}{{ end }}
```

**Comment by tlienart** [comment]
I think this is fixed because `{{fill xxx}}` if `xxx` is not recognised will just return `nothing`.
