### ISSUE TITLE
href of header links to page/index.html

### ISSUE THREAD

**Issue by MarcMush** [tlienart/Franklin.jl#382]
when clicking on a header, the link is `/path/to/page/index.html#title` instead of `/path/to/page/#title` which causes the page to reload
IMO, the best would be simply `href="#title"`

**Comment by MarcMush** [comment]
https://github.com/tlienart/Franklin.jl/blob/dcbdd3f318b4cdeb6711df4f166c521d144115b2/src/converter/markdown/blocks.jl#L131

https://github.com/tlienart/Franklin.jl/blob/dcbdd3f318b4cdeb6711df4f166c521d144115b2/src/utils/html.jl#L20-L21

**Comment by tlienart** [comment]
Ah yes, that makes sense, thanks!
