### ISSUE TITLE
Controlling the site layout

### ISSUE THREAD

**Issue by snirgaz** [tlienart/Franklin.jl#398]
I might have missed that part in the documentation but It is unclear to me how should I control the site layout. 
More specifically, adding aditional ".md" files does not automatically add menu items, making these pages inaccessible. 
Do I have to manually edit "_layout/head.html"?

**Comment by tlienart** [comment]
Yes that's right! basically franklin generates pages by doing `head * page * foot` where `page` is the result of the markdown conversion and is wrapped in a big div called `franklin-content` (you can change that name if you want). 

So then you can adjust `head` and `foot` at will and _all_ pages will have them. Of course you may not want this so the next step is to use `{{ispage ...}}...{{end}}` blocks in the `head` and possibly `foot` and insert subblocks accordingly (either by writing html directly or by `{{insert ...}}`. 

Then pages are still generated with the same process but the `head` and/or `foot` will be different depending on the page and the conditional blocks. 

As an example if you check in the template "jemdoc" which is quite simple, you'll  see that in the `head.html` there are conditional blocks which add a `active` class to  menu items depending on the page you're on, the result is for instance https://tlienart.github.io/FranklinTemplates.jl/templates/jemdoc/menu2/ where if you look at the left menu "More goodies" is underlined.

I know I have to do a pass on the docs to add more info on how to do this, help  is welcome  by making suggestions of what's not immediately obvious on the https://github.com/tlienart/franklindocs repo :) thanks and I hope this helps

**Comment by snirgaz** [comment]
Thanks! Works great.
