### ISSUE TITLE
Exporting to pandoc/latex

### ISSUE THREAD

**Issue by snirgaz** [tlienart/Franklin.jl#399]
I am using the package to compile a set of lecture notes for a computational physics course.
It would nice to be able to generate a single file containing all classes (now separate pages) in a single file.
Is it possible to export the generated pages into pandoc/latex format?

**Comment by tlienart** [comment]
So you would like to get one big PDF file with all the pages? 

Basically it shouldn't be too hard to generate one big HTML page with a lot of content on it (you can use Franklin's `fd2html` to help generate the content of that insider class that I mentioned  in #398), basically the raw HTML corresponding just to the content, and you can add your own stuff before and after it. 
To then go from that generated HTML to PDF is more unchartered territory. Pandoc is a great tool but I don't  know whether it handles KaTeX well. And it may be more pain than it's worth. What I would suggest is to just use a bruteforce html to pdf command line interface which just "prints" your document:  [wkhtmltopdf](https://wkhtmltopdf.org/) does that very well and the CLI is dead simple. For instance I just tried

```
wkhtmltopdf https://tlienart.github.io/pub/csml/glr/ridgecv.html ~/Desktop/test2.pdf
```

and it gave:

[test2.pdf](https://github.com/tlienart/Franklin.jl/files/4328674/test2.pdf)

which I thought looks  great.

The disadvantage is that you wouldn't get access to  the intermediary LaTeX but, as I said, this may be more painful than is worth it, Pandoc is super powerful but also not always the easiest tool to  just get stuff to  work well and fast 😄 

What do you think?

**Comment by snirgaz** [comment]
That is a nice workaround!
Though it seems like some of the math got distorted in the PDF file, e.g Eq. 10 and transpose symbols.
But I guess this is related to the wkhtmltopdf tool since the html files looks fine.

**Comment by tlienart** [comment]
I'll close this now but feel free to re-open if you'd like other things. 

Note: you may be interested  in the #403 conversation, mathjax can pre-render to SVG so *potentially* the printing process would *not* distort anything, but all of this is speculative, I haven't tried 😄
