### ISSUE TITLE
Missing highlight.js

### ISSUE THREAD

**Issue by ViralBShah** [tlienart/Franklin.jl#402]
What do I need to do to get this?
```
[ Info: Precompiling Franklin [713c75ef-9fc9-4b05-94a9-213340da978e]
✘ Couldn't find highlight.js (``/Users/viral/.julia/artifacts/1f34757b37b4d557365669ed69ebb5253d959e20/bin/node` -e "require('highlight.js')"` failed).
```

**Comment by tlienart** [comment]
Please try following  https://franklinjl.org/index.html#installing_optional_extras and let me know if it doensn't work.

PS: note that this installation is not essential especially if you're using GitHub actions as the library itself is needed only in the (optional) pre-rendering step. If you don't have it, Franklin will plug in the javascript from `_libs/` and, assuming you're using it for standard languages like Julia (😉) highlighting should work just fine.

**Comment by tlienart** [comment]
closing in favour  of https://github.com/tlienart/franklindocs/issues/14
