### ISSUE TITLE
Insert and process MD from HTML

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#407]
In the HTML page do  something like

```
HTML here
{{insert somefile.md}}
```

with the expected result being that it would process `somefile.md` with `fd2html` and paste the resulting HTML there.

A key thing will be to ignore `somefile.md` in the general run so that we don't  end up with a  spurious URL `root/somefile/`; possibly these could be written *inside* of `_layout` and everything markdown file inside `_layout` be ignored.

**Comment by tlienart** [comment]
This would also potentially be useful for a single page layout where  user would  include subblocks written in MD.

**Comment by tbeason** [comment]
Just seeing this issue. This is exactly what I need! I want to redesign my personal page to basically have a two-column piece up top ("About me") and then will just be single column for the remainder. I had planned on the sections just being `.md` files. I have the layout mostly done in bootstrap, but need to add in the content.

A two piece example:
```html
<div class="container" style="margin-top:30px">
{{insert section1.md}}
<br>
{{insert section2.md}}
</div>
```
Perhaps this could also be done with a loop (which I think is also something you want to work on). So maybe this could go along nicely with #409 and/or #391 ?

**Comment by tlienart** [comment]
did you put this on a repo somewhere? would be good to see how you're trying to do this and whether there may be a simpler way (or not in which case it'll help me see how to best go about this issue)

**Comment by tbeason** [comment]
No I did not yet. Like I said, only have (most of) the bootstrap stuff in place, hadn't really gotten to the Franklin stuff yet. I will create a dummy repo with the code in the next few days and report back.

**Comment by tlienart** [comment]
This is now doable in `v0.7` basically plop something like this in `utils.jl`:

```julia
function hfun_insertmd(args)
    path = args[1]
    return Franklin.fd2html(read(path, String))
end
```

Which you can call in your HTML with `{{insertmd path}}`. 

**Note**: I'm not convinced this is the best way to go in your particular case, it would help to see your draft site but the above should work.
