### ISSUE TITLE
Static content

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/Franklin.jl#410]
Would be very useful with a `_static` folder similar to what exists in Hugo (https://gohugo.io/content-management/static-files).

**Comment by tlienart** [comment]
I may misunderstand your suggestion but doesn't `_assets` do what you want? 

> Files that get served statically (as-is, no modification) on the site root.
By default, the static/ directory in the site project is used for all static files (e.g. stylesheets, JavaScript, images). The static files are served on the site root path (eg. if you have the file static/image.png you can access it using ....

Seems to be a description for `_assets`?

**Comment by fredrikekre** [comment]
Kinda, the difference beeing `The static files are served on the site root path`. For example, for custom domain names with github pages you need a file `CNAME` file in the root.

**Comment by tlienart** [comment]
So the aim is to  you want to be able to do 

* `yoursite.org/myasset.png` instead of 
* `your site.org/assets/myasset.org` 

?

**Comment by fredrikekre** [comment]
Yes.

**Comment by tlienart** [comment]
Sorry to ask again, what's the use case more precisely? is it essentially that it's annoying to write `[my image](/assets/img.png)` instead of `[my image](/img.png)` in markdown or is it a broader issue where you don't want the URL to show a `/assets/`? 

I'm a bit attached to the idea that the generated folder structure maps 1-1 with the way the URLs work but this may be because I don't yet really see how useful this could be.

Thanks!

**Comment by fredrikekre** [comment]
For a custom domain name on gh-pages I need a file `CNAME` including the domain name, I believe this has to be at the root, cf. https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain.

**Comment by fredrikekre** [comment]
I believe the reason www.julialang.org` works is that this file https://github.com/JuliaLang/www.julialang.org/blob/gh-pages/CNAME is there from before switching to Franklin.

**Comment by tlienart** [comment]
oh! so you mostly want the CNAME to be left alone and copied properly to __site ?

**Comment by tlienart** [comment]
ok this I'll fix immediately

**Comment by fredrikekre** [comment]
Yea, I misunderstood. I didn't think any extra files were copied over to `__site`. Just for completeness before closing: My idea would then be something like. I think my idea would then have to be something like
```
static/
content/
```
where `content` would be process by Franklin and put in `__site` and then `static` would just overlay that. This gives some more control to the user about what ends up in `__site`.
