### ISSUE TITLE
Possible LaTex parsing error?

### ISSUE THREAD

**Issue by snirgaz** [tlienart/Franklin.jl#424]
The following issue happens only after updating to the latest Franklin.jl version.

I am trying to parse the markdown text:
`       Now we will show that taking $\rho=\frac{e^{-\beta \mathcal{E}_{s}}} {\mathcal{Z}} $, namely the Boltzmann distribution, minimizes the variational free energy.
`

The resulting HTML contains both the correct rendered LaTeX equation followed by a spurious (?)  "text" version of the same equation.

<img width="752" alt="Screen Shot 2020-03-23 at 10 39 29" src="https://user-images.githubusercontent.com/6839009/77297904-a8e9c700-6cf2-11ea-90c6-2bd119e9d30e.png">

**Comment by tlienart** [comment]
Thanks for that, I can reproduce, it should be an easy fix, sorry  about that!

**Comment by tlienart** [comment]
0.6.12 will be released shortly and fixes this

<img width="151" alt="Screen Shot 2020-03-23 at 10 12 22" src="https://user-images.githubusercontent.com/10897531/77300829-01b76080-6cef-11ea-9948-1d6b1c23e8af.png">
