### ISSUE TITLE
Using Interact with Franklin?

### ISSUE THREAD

**Issue by xukai92** [tlienart/Franklin.jl#426]
I wonder if it is possible to use [Interact.jl](https://github.com/JuliaGizmos/Interact.jl) to include some interactive componenet with Franklin?

**Comment by tlienart** [comment]
I don't  know much about Interact but unless I'm mistaken it requires you to run a server with Julia running right? if that's correct then the answer is *no*; if it generates javascript that can be served statically then yes, no problem. 

Now note that there is *another* way to do interactive stuff with  Franklin: see [here](https://tlienart.github.io/FranklinTemplates.jl/templates/sandbox-extended/mdpad/), I've not played a lot with it but in theory you can do a fair bit; it uses @tshort's [mdpad](https://github.com/tshort/mdpad-js) based on [mithril](https://mithril.js.org/). 

This should provide similar functionality to the recently released [Matte.jl](https://github.com/angusmoore/Matte.jl) (I think).

**Comment by xukai92** [comment]
Yeah I'm not an expert of Interact either but it does seem to require some kind of servers running in Julia. 

Thanks for the example using mdpad! The source code you showed looks more like manipulate the HTML file directly using Julia. Seems like it requires more knowledge of web dev than Interact.jl. I wonder if it's possible to achieve things like https://github.com/JuliaGizmos/Interact.jl#manipulate?

**Comment by tlienart** [comment]
so the answer is definitely yes, the key question is "how much Javascript"? at the moment if I wanted to do this immediately, I'd pretty much just code in Javascript. If there is a way to extract logic from Julia and get Javascript out of it, then maybe this could be used; I think https://github.com/JuliaGizmos/JSExpr.jl is interesting but I've not tried playing with it. 

I'm interested in charting and it seems interactive stuff would be of interest to people who are considering using Franklin so I'll investigate this a bit more and report; in the mean time if you get something to work to let me know 😄

**Comment by tlienart** [comment]
Searching the web a bit it seems that a rather nice candidate for interactive plots that would be similar to Interact.jl is JSXGraph; see for instance: http://jsxgraph.uni-bayreuth.de/wiki/index.php/Multiple_logarithmic_spirals 

I might try to see if it can play well with JSExpr.jl, could be a nice combination. 

Other possible nice JS libs are Chart.js, Chartism.js, ApexCharts.js, mpld3, ... it's a bit crazy how many there are though many seem to have a rather narrow scope. JSXGraph seems closest to what Interact offers as far as I could tell.

I'll close this as this is not really a Franklin issue, you could load any one of these libs without trouble but would end up writing the meat of the code in Javascript; there may be a possibility to do JSX+JSExpr.jl but that's another project entirely 😄

**Comment by tlienart** [comment]
Hello  @xukai92 I thought I'd let you  know that [JSXGraph.jl](https://github.com/tlienart/JSXGraph.jl) is now a thing and works well with  Franklin as you can see in [this page of examples](https://tlienart.github.io/JSXGraphWeb/)

It's  still  barebones but might be  of interest!

**Comment by xukai92** [comment]
Great - thanks for updating me @tlienart :D The page of examples look great. I will try it next time I write my blog!
