### ISSUE TITLE
"type Nothing has no field args" if last line of code block is a comment

### ISSUE THREAD

**Issue by lucasvreis** [tlienart/Franklin.jl#427]
Steps to reproduce:

- Create a _named_ Julia code environment
- Start the server
- Write a Julia comment in the last nonempty line of code before closing the environment
- Franklin throws `type Nothing has no field args`

Also, if the comment is _already there_ before starting the server, I do not run into problems. Just when it is already running and updates the page.

**Comment by tlienart** [comment]
Oh 🤔 thanks for reporting this! ok I think I know what it is, there’s some logic to look at the last line of a code block to check what output should be shown (or not shown) and I didn’t think that the last line could be a comment... 

I’ll fix that asap, probably tomorrow; thanks for the report!
