### ISSUE TITLE
Special character in footnote tags

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/Franklin.jl#430]
Compare:
```
julia> Franklin.fd2html("""
       Hello[^ö]

       [^ö]: world
       """)
"<p>Hello<a href=\"#footnote-ö\" class=\"footnote\">[ö]</a></p>\n<div class=\"footnote\" id=\"footnote-ö\"><p class=\"footnote-title\">ö</p><p>world</p>\n</div>\n"

julia> Franklin.fd2html("""
       Hello[^a]

       [^a]: world
       """)
"<p>Hello<sup id=\"fnref:a\"><a href=\"#fndef:a\" class=\"fnref\">[1]</a></sup>\n<table class=\"fndef\" id=\"fndef:a\">\n    <tr>\n        <td class=\"fndef-backref\"><a href=\"#fnref:a\">[1]</a></td>\n        <td class=\"fndef-content\">world</td>\n    </tr>\n</table>\n</p>\n"
```
rendered as:
![Screenshot from 2020-03-25 12-11-54](https://user-images.githubusercontent.com/11698744/77530583-e042aa00-6e91-11ea-8ce1-2ce9505958c0.png)

**Comment by tlienart** [comment]
Hmm yeah the regex is `match(r"^\[\^[a-zA-Z0-9]+\](:)?$", τ.ss)` (https://github.com/tlienart/Franklin.jl/blob/a0e2032f7b55e008d4bb512e875333800fd80f88/src/parser/markdown/validate.jl#L14) I'd have to dig a bit to remember how to  also allow unicode chars in that regex

**Comment by tlienart** [comment]
Yeah looks like `[\p{L}0-9]` would  do the job
