### ISSUE TITLE
Deployment error: process '/usr/bin/rsync' failed with exit code 23

### ISSUE THREAD

**Issue by kescobo** [tlienart/Franklin.jl#438]
I made a brand new repository with `newsite("LabDocs", template="minimal-mistakes")`, and the site builds / updates locally with `serve()`. 

I followed the instructions [here](https://franklinjl.org/workflow/deploy/) to deploy on a project site: 

1. created and added personal access token with name `FRANKLIN`
2. created a [new repository](https://github.com/Klepac-Ceraj-Lab/LabDocs)
3. did `git init` in local repo, added everything and pushed to `master` branch. 

[The build](https://github.com/Klepac-Ceraj-Lab/LabDocs/runs/556065335) starts, but after the `gh-pages` branch is made, it fails with:

```
##[error]The deploy step encountered an error: The process '/usr/bin/rsync' failed with exit code 23 ❌
Deployment Failed ❌
```

The only other thing I did that's not in the docs is I edited `config.md` to change the website and author to 

```
@def website_url   = "https://klepac-ceraj-lab.github.io/LabDocs/"
@def author = "VKC Lab Staff"
```

Project environment:

```
(@v1.4) pkg> st
Status `~/.julia/environments/v1.4/Project.toml`
  [c52e3926] Atom v0.12.10
  [6e4b80f9] BenchmarkTools v0.5.0
  [35a29f4d] DocumenterTools v0.1.5
  [713c75ef] Franklin v0.6.16
  [7073ff75] IJulia v1.21.1
  [e5e0dc1b] Juno v0.8.1
  [5fb14364] OhMyREPL v0.5.5
  [14b8a8f1] PkgTemplates v0.7.0-DEV #master (https://github.com/invenia/PkgTemplates.jl.git)
  [08abe8d2] PrettyTables v0.8.4
  [ce6b1742] RDatasets v0.6.7
  [295af30f] Revise v2.6.0
```

**Comment by tlienart** [comment]
Hello @kescobo the "proper" way to deploying things is detailed in #390 (with apologies, it should be part of the docs, haven't found the time to put it there yet). In very short:

* use this [`.github/workflows/deploy.yml`](https://github.com/tlienart/LabDocs/blob/master/.github/workflows/deploy.yml) which is a bit more complete
* do `ssh-keygen -N "" -f franklin` and copy
  * the content of `franklin.pub` in a new key called FRANKLIN with rw access
  * the content of `franklin` in a new secret called DEPLOY_KEY
* push

That being said what you did seems like the right thing, I've not seen this `rsync` issue before. But would you mind trying the above and reporting if it worked for you? thanks!

**Comment by kescobo** [comment]
Awesome, thanks for the help! I'll try to give this a shot later today (or possibly tomorrow, depending on baby naps), and make a PR to to the docs if that would be helpful.

**Comment by tlienart** [comment]
PR would be awesome, it will force me to look into it and have it done :D thanks!

**Comment by kescobo** [comment]
I'm a bit confused what you mean by "in a new key called FRANKLIN."

So the deploy key should be called `FRANKLIN` and be the public rsa key, but the secret should be called `DEPLOY_KEY` and be the private rsa key?

**Comment by tlienart** [comment]
Yeah that makes sense thanks! and glad it works :)
