### ISSUE TITLE
Issue with Katex + Unicode + \newcommand

### ISSUE THREAD

**Issue by lucasvreis** [tlienart/Franklin.jl#439]
If one uses unicode symbols in Katex, and later in the math employs a macro defined in Franklin with `\newcommand`, a fixed number of characters will be rendered omitted after the macro (depending on the number of symbols before the macro):
```
\newcommand{\u}{1}

$$ φφφ\u abcdef $$
```
Page shows (but in Katex beauty):
`φφφ1cdef` :thinking: 

There is no issue if the unicode is inside the macro definition, like:
```
\newcommand{\u}{1}
\newcommand{\v}{φφφ}
$$ \v\u abcdef $$
```
Outputs `φφφ1abcdef` as expected.

Also, this is specific to the math environment, I found no issues when things are outside it.

**Comment by tlienart** [comment]
Thanks a lot for the reproducing example; I suspect this is some issue with `convert_md_math`; I'll try to fix it soon.
