### ISSUE TITLE
Interact in Franklin

### ISSUE THREAD

**Issue by shashi** [tlienart/Franklin.jl#440]
Hi @tlienart!

I am one of the authors of Interact.jl. I have always wanted a site generator like Franklin.jl in Julia. It's pretty amazing! But I also want to support interactive widgets and plots (where the interaction needs to execute some Julia code). I have been building a server for a bunch of files that contain interactive UIs (with syntax inspired by LaTeX) but it looks to me like Franklin has much the same and more features and already has a really solid implementation. Also there are many templates and themes and most importantly users :)

So I was poking around the code and docs to look at how I could make Franklin have interact widgets in it. For example I would like to be able to write
```julia
using Interact
```julia-live
@manipulate for n=10:10:100
   plot(rand(n))
end
\```
```
or something like that, and have a slider appear on the generated web page that one can mess with to change the plotting parameter. Here are some of my observations:

1. Serving webio js (the underlying infrastructure of Interact) and including it in pages seems easy enough.
2. The tricky part is, serve  can't just write out the output to a `output/..` file since the result of a code cell that has something interactive is more than something static -- in general it must create communicating Julia tasks when a user visits the page.
3. In principle all this is possible as long as we're working within the confines of Franklin.serve

Would you say this is a reasonable goal to hack at, or would you say interactive concerns are better left for another package which will unfortunately have to reproduce the same hyperlinked website type of features? What would your first impulse be if you needed an interactive widget be in your Franklin website?

Thanks!

**Comment by tlienart** [comment]
It's kind of funny to read your message when a few days ago I had a private exchange precisely about this with one of the folks from JuliaGizmos and he ended up convincing me that this would not be possible bc you'd basically need Julia running in the browser. So much so that I ended up starting to code my own thing on top of [JSXGraph](https://jsxgraph.uni-bayreuth.de/wp/index.html) using [JSExpr.jl](https://github.com/JuliaGizmos/JSExpr.jl). 
Anyway I think it's great to brainstorm what would be possible (also linking #426 since it was a related question).

My current perspective in short:

- using Interact for a **locally served website** using Franklin would be doable I think and I don't see major roadblocks; we might want to think a bit about when things are evaluated, possibly use a background thread or something like this, but it could be really cool.
- using Interact for a **statically served website** would not be directly doable as far as I understand because you would need to have Julia running in the browser in some form. 

I have not investigated the first option which may be what you're suggesting. The second option seemed too hard to do at the moment which is why I started hacking away at building a kind of bridge to JSXGraph where the process basically is a bit like PlotlyJS:

- write some Julia code
- it effectively generates specific Javascript
- serve that Javascript statically

Example of the kind of stuff you could do: https://jsxgraph.uni-bayreuth.de/wiki/index.php/Lissajous_curves

One last possibility would have to make it possible to generate Javascript from WebIO/Interact...

**Comment by shashi** [comment]
Oh hahaha that _is_ funny! Was this on Slack?

Yeah I did mean **locally served website**.

> One last possibility would have to make it possible to generate Javascript from WebIO/Interact that > could be directly plugged in but my understanding was that this is not possible at the moment and > would probably never be

It's actually possible to write completely client sided interaction right now with WebIO, (we don't try to communicate with Julia if there's no event handler for an observable value.) For example you essentially use the same API (e.g. Interact widgets) and then write handlers in JavaScript rather than Julia (maybe one day we can compile to WASM). So we can definitely make that possible, and allow use of Julia if one wants to.

> Example of the kind of  stuff you could do: https://jsxgraph.uni-bayreuth.de/wiki/index.php/Lissajous_curves

That's really cool! I think these tools are great.

I think what I'm going to do is, get something working and ask you how to make it right. It will allow us to talk in more detail about the littler problems.

**Comment by tlienart** [comment]
Awesome, looking forward to it

**Comment by ericphanson** [comment]
You both might be aware of this, but in case not I wanted to mention @SimonDanisch's [JSServe.jl](https://github.com/SimonDanisch/JSServe.jl) which I think is currently along the lines of the first option (i.e. you have an active Julia process that communicates with the Javascript session to evaluate things).

**Comment by SimonDanisch** [comment]
I'm also actively working on static exports for JSServe, that doesn't require a running Julia process!

**Comment by tlienart** [comment]
@SimonDanisch count me interested

**Comment by asprionj** [comment]
Very interesting discussion / ideas. I guess there's often the task of "sharing" some model / calculation / visualization on a website, in a web app etc. If there's complex calculations involved (like solving a DDE of a 10k-state-model), the best way surely is to have Julia running the stuff in the backend and having only the visualization / interaction in the frontend. However, for "small stuff", this setup is overkill. Then, being able to also "port" the backend part (just one or a handful of simple functions and some glue code) into the frontend (i.e. to JS) would be really nice. Porting by hand is possible, but not good to maintain, especially if the Julia code is the main use case and the web app is rather a "byproduct".

Is there any discussion (on Discourse etc.) related to this in general?

**Comment by tlienart** [comment]
I definitely agree, this is why I'm working on JSXGraph; the following is very WIP, leads to fully static JS. There's a lot of details to iron out but it could be fun.

```
using Pkg; Pkg.add(PackageSpec(url="https://github.com/tlienart/JSXGraph.jl"))
using JSXGraph

brd = board("brd", xlim=[-12, 12], ylim=[-10,10])
slider("a", [[2,8],[6,8],[0,3,6]]) |> brd
slider("b", [[2,7],[6,7],[0,2,6]]) |> brd
slider("A", [[2,6],[6,6],[0,3,6]]) |> brd
slider("B", [[2,5],[6,5],[0,3,6]]) |> brd
slider("delta", [[2,4],[6,4],[0,0,π]], name="&delta;") |> brd
@jsf f1(t) = val(A)*sin(val(a)*t+val(delta))
@jsf f2(t) = val(B)*sin(val(b)*t)
plot(f1, f2, a=0, b=2π, strokecolor="#aa2233", strokewidth=3) |> brd
brd
```

You can get the JS from

```
JSXGraph.str(brd)
```

Here's what it looks like: https://jsfiddle.net/pwvjstyo/

**Comment by asprionj** [comment]
Wow that's already pretty cool. I mean, I can build up the UI step by step, play with it in Juno, and when I'm done, just export the JS code. Sounds like big fun, actually. That would be approach 1.1 from https://nextjournal.com/sdanisch/wasm-julia, right? Haven't looked into it at all, but suspect that JS-code is generated by parsing (the AST of) the Julia code?

The other three approaches in said article also sound extremely interesting (and promising), and probably are much simpler to reach a quite wide coverage, and surely the only way(s) to reach full coverage. @SimonDanisch : you're probably the guy with the best overview on all of this... which way would you go? I'd be happy to help but can only spend a minimal amount of time on it...

BTW, depending on the way forward, this might also go in the direction of https://discourse.julialang.org/t/bring-julia-code-to-embedded-hardware-arm/19979...

**Comment by tlienart** [comment]
For those who would be following this conversation:

- [JSXGraph.jl](https://github.com/tlienart/JSXGraph.jl) is now a thing
- here are [some examples](https://tlienart.github.io/JSXGraphWeb/) (with franklin of course)

I'll close this here but @shashi I look forward to seeing stuff with Interact.jl :-) please re-open (or open a new one) when appropriate!
