### ISSUE TITLE
How do I use `@def ignore` properly?

### ISSUE THREAD

**Issue by terasakisatoshi** [tlienart/Franklin.jl#450]
- I would like to ignore a specific markdown file generated by other Packages e.g. Remark.jl which will create some markdown files temporally.

- According to this test code, 

https://github.com/tlienart/Franklin.jl/blob/bbec0e5d69c01e924761845445e2596d036439a0/test/manager/dir_utils.jl#L6

it seems to just write `@def ignore = ["remark/src"]` on `config.md`:

```markdown
<!-- config.md -->
@def ignore = ["remark/src"]
<!-- or -->
@def ignore = ["remark/src/index.md"]
```

However, Franklin does not ignore `remark/src/index.md` and trying to process it. 

- Of course, there is a workaround that removing target files before running `Franklin.serve()` 😉, but I would like to know how I use `ignore` properly.

**Comment by tlienart** [comment]
If you have a look at the examples note that for exclusion of a directory you should close it with a `/`

So in your case if you want to avoid everything that's in `remark/` use `ignore = ["remark/"]` if you want to ignore a specific file, use `["remark/path/to/specific/file.md"]`

**Comment by terasakisatoshi** [comment]
> If you have a look at the examples note that for exclusion of a directory you should close it with a /

Oh, I did not know that.

```
<!-- config.md -->
@def ignore = ["remark/src/"]
```

works fine.

> However, Franklin does not ignore remark/src/index.md and trying to process it.

This phenomena does not occurs when I once remove all contents under `__site` 😄 

Thank you for your detailed explanation and examples. 
Let's close this issue.
