### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#456]
The kind of stuff described in https://attila.zutrinken.com/organising-content/

### Required

* a way to indicate tags, page var is fine
* some functionality to collect all tags (basically just need to go through ALL_PAGE_VARS)
* generate `mainurl/tags/tagname/` would use a `_layout/tag.html` and fill it with a generated list

This is all pretty easy to do

### Notes

* need to keep track of tags associated to all pages so that if they get modified can re-trigger generation of tag pages, could just do that in a dict.

PS: cc @wikunia since you mentioned this, if you want to give it a shot I can lend you a hand :-)

**Comment by Wikunia** [comment]
Sounds nice. I'm interested on working on it on Monday. Will ask questions in slack if I have some. (I'll :smile: )

**Comment by fredrikekre** [comment]
I had something like this working, but I don't remember on which machine so I guess it is lost now. Would be nice to have!

**Comment by Wikunia** [comment]
One small question: this should all be done whenever such a page variable tags exists, right? So the user still just calls `serve` and all folders are created automatically.

**Comment by tlienart** [comment]
Ok here's at a high level what I would do:

* optional path `_layout/tag.html` which would contain the structure that goes around one of those tag-list pages. If not there and tags are given, something would fail. 
* a local page var `tags` which allows a `Vector{String}` and is empty by default
* a global dictionary `TAGS` which contains pairs `rpath => [tags]` 
* when `process_mddefs` is called (inside `convert_md` so that's called on every page trigger) check if `tags` is given, if it is check the `TAGS` dictionary and either add, remove or update the entry. If it's identical than before, do nothing, if it isn't and that we're not on the initial fullpass then trigger a `generate_tag_pages` function

The `generate_tag_pages` function would

* take an optional argument indicating which page has triggered the update
* create a `__site/tag/` folder if it isn't there already
* invert the dictionary `TAGS` to get `tag => [rpaths]` 
* go through each tag, (if the triggering page is given & the list of `rpaths` does not intersect with it, ignore)
* for the tags that need an update, create the html which would be built out of `_layout/tag.html` and with the list of links, extracting page titles too via `{{fill title rp}}` etc
* convert that html to resolve any `{{...}}` using `convert_html` 
* create with the converted html a page `__site/tag/tagname/index.html`

The `generate_tag_pages` would also have to be called after the initial `fd_fullpass` after `ALL_PAGE_VARS` and `TAGS` is populated

**Comment by tlienart** [comment]
Ok this is now in master (and 0.7.6 will be released soon), un-announced officially because I'd like to battletest it a bit more (I'll add a theme/template which uses it soon). Help to report any problems in the mean time would be very welcome here!

### API

* add tags to a page with `@def tags = ["aa", "bb"]` 
* this will generate pages at `/tag/aa/` and `/tag/bb/` with the list of pages with the same tags
* the way the list of results is shown is controlled by the html function `hfun_list` which
  - finds the pages with a given tag
  - sorts them by date, and if date not given by creation date
  - puts the results in a simple list

Users can easily overwrite this behaviour, they would need to implement something like this in their `utils.jl`, modifying the core of the logic however they want. 

For instance users could define a variable `short_description` for all these pages and display  those in some order instead of a list.

```julia
function hfun_list(params)
    tag = params[1]
    TAG_PAGES = globvar("fd_tag_pages")
    c = IOBuffer()
    # -------------------------------------------
    # add your logic here
    write(c, "<h1>Tag: $tag</h1>")
    write(c, "<ul>")
    rpaths = TAG_PAGES[tag]
    sorter(p) = begin
        pvd = pagevar(p, "date")
        if isnothing(pvd)
            return Date(Dates.unix2datetime(stat(p * ".md").ctime))
        end
        return pvd
    end
    sort!(rpaths, by=sorter, rev=true)
    for rpath in rpaths
        title = pagevar(rpath, "title")
        if isnothing(title)
            title = "/$rpath/"
        end
        write(c, "<li><a href=\"/$rpath/\">$title</a></li>")
    end
    write(c, "</ul>")
    # -------------------------------------------
    return String(take!(c))
end
```

**Comment by Wikunia** [comment]
Currently `locvar("fd_rpath")` doesn't seem to work on tag pages. For me it just spits out some (for me random) path instead of the tag path. This is probably because the tag pages only exist in the `__site` folder

**Comment by tlienart** [comment]
yes tag pages don't have their own page variables. If you want to recover which tag  page you're on you can do so via `fd_tag`

**Comment by tlienart** [comment]
this  is now supported.
