### ISSUE TITLE
Feature request: RSS feeds for tags

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/Franklin.jl#463]

**Comment by tlienart** [comment]
sounds good, would you have an example of such an RSS feed somewhere that I could use as template? I think it's reasonably simple to do (pretty much  the same as the "main" RSS feed except one per tag) but having a template might help avoid mistakes.

**Comment by fredrikekre** [comment]
I thought Hugo did by default but you probably have to configure it. I know I have seen it on someones blog but can't find it now.

Here is for Hugo sections though https://spf13.com/project/index.xml and how to configure it for tags is probably listed here: https://gohugo.io/templates/rss/

**Comment by ViralBShah** [comment]
Would it make it possible to move JuliaBloggers to Franklin if we have this?

**Comment by ViralBShah** [comment]
@chrisrackauckas

**Comment by ChrisRackauckas** [comment]
I brought this up for the other way around. Blogs that are connecting to JuliaBloggers should be adding a feed for specific tags to JuliaBloggers, and so the lack of per-tag feedbacks restricts blogs from using JuliaBloggers (unless the whole blog is reblogged to it). JuliaBloggers itself could probably change today.

**Comment by tlienart** [comment]
Just for my sake:

<img width="363" alt="Screen Shot 2020-08-23 at 23 00 44" src="https://user-images.githubusercontent.com/10897531/90988640-b0a8e280-e594-11ea-85f5-386992f09288.png">

**Comment by McSinyx** [comment]
`link` and `atom:link` don't point to the right location IMHO, should I file a new issue?

**Comment by tlienart** [comment]
Yes please
