### ISSUE TITLE
Add example with WGLMakie

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#471]
Thanks to @SimonDanisch's hard work, it's now basically possible to export standalone javascript from a Makie plot (with the constraint that, at the moment, it doesn't support much interactivity if any). 

Example provided by Simon in [this issue](https://github.com/JuliaPlots/WGLMakie.jl/issues/38)

```julia
using JSServe, WGLMakie, AbstractPlotting

function handler(session, request)
    return scatter(1:4, color=1:4)
end

dir = joinpath(@__DIR__, "test")
mkdir(dir)
JSServe.export_standalone(handler, dir)
# Then serve it with e.g. LiveServer
using LiveServer

LiveServer.serve(dir=dir)
```

Could be adapted to be an example along PlotlyJS.

**Comment by AlexisRenchon** [comment]
When running the code above, I currently get the following error, when running JSServe.export_standalone(handler, dir)
```
ERROR: MethodError: no method matching JSServe.UrlSerializer(::Bool, ::String, ::Bool, ::String
)
Closest candidates are:
  JSServe.UrlSerializer(::Bool, ::Union{Nothing, String}, ::Bool, ::String, ::Bool) at /home/al
exis/.julia/packages/JSServe/E7QrV/src/types.jl:114
  JSServe.UrlSerializer(::Any, ::Any, ::Any, ::Any, ::Any) at /home/alexis/.julia/packages/JSSe
rve/E7QrV/src/types.jl:114
Stacktrace:
 [1] export_standalone(dom_handler::Function, folder::String; clear_folder::Bool, write_index_h
tml::Bool, absolute_urls::Bool, content_delivery_url::String)
   @ JSServe ~/.julia/packages/JSServe/E7QrV/src/offline.jl:128
 [2] export_standalone(dom_handler::Function, folder::String)
   @ JSServe ~/.julia/packages/JSServe/E7QrV/src/offline.jl:123
 [3] top-level scope
   @ REPL[35]:1
   ```

**Comment by tlienart** [comment]
There's a demo now: https://franklinjl.org/demos/#016_using_wglmakie_jsserve (https://franklinjl.org/demos/wgl/) which shows the proper way of doing things

**Comment by tlienart** [comment]
Yeah WGLMakie is deprecated. 

This is now handled with Makie directly. Xranklin.jl (next version of Franklin, in prep) handles this. But generally, I'd suggest people use something else than Makie for the static site stuff as it's still flaky and even when it works, it doesn't work on all browsers bc webgl is not systematically on.
