### ISSUE TITLE
[dev] Add functionality to create "temporary page var" dictionary for generated pages

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#472]
For tag pages but possibly also for other pages that users would define within their `hfun_*` it should be possible to "easily" create a temporary page var of a similar format than LOCAL_PAGE_VARS but without disrupting that one. 

Basically the mechanism would need to be able to :

- save the current local var (possibly just using ALL_PAGE_VARS)
- define a temporary local var, assign variables that need to be assigned according to some relevant rule
- get back to the previous LOCAL_PAGE_VARS

this is all relatively easy but the tricky part would be to expose this to developers who would want to do it themselves & make it sure that they don't screw everything up by forgetting to back up the current local page vars or forgetting to reload it.

**Comment by zdroid** [comment]
Would this be made obsolete by introducing variable scopes?

**Comment by tlienart** [comment]
This issue is actually stale. 

Re your comment: no it wouldn't. Generated tag pages don't have a scope; they get triggered from any page that has that tag and so can't rely on page variables. They can call global page variables or specific tag variables that indicate what tag we're on.
