### ISSUE TITLE
Run the build on pull requests (but don't deploy "previews")

### ISSUE THREAD

**Issue by DilumAluthge** [tlienart/Franklin.jl#476]
I have the GitHub Actions deployment set up here: https://github.com/JuliaHealth/juliahealth.github.io/blob/dev/.github/workflows/deploy.yml

I'd like to set it up so that the build runs on pull requests. That way, I can make sure that pull requests don't break the build (bad syntax, etc.).

Obviously, I don't want a pull request build to push/deploy to `master`.

I am also not interested in having the pull request builds push/deploy "previews". I just want to see the pass/fail status of the GitHub Action.

Is this possible? How would I set this up?

**Comment by tlienart** [comment]
The master of GA asks the novice how to do stuff :eyes: oh my...

ok so if I understand you properly what you care about is:

- upon a PR check that the site builds properly

right?

So this is identical to what is being done with the JuliaLang; you can hook up the "preview" if you want but you don't have to so that's fine. Just add an "if" statement that if you're on a PR you shouldn't deploy to branch like: https://github.com/JuliaLang/www.julialang.org/blob/a05d866de66eb7e761a3e6cfbe0273f631dfe906/.github/workflows/deploy.yml#L45 

does that make sense?

**Comment by DilumAluthge** [comment]
> The master of GA asks the novice how to do stuff 👀 oh my...

😂 I think you overestimate me

I think this is what I'm looking for.

Now, that being said, it looks like when Franklin pushes a preview, it always pushes it to the `gh-preview` branch. Is that correct?

The main reason that I don't currently use the Documenter previews is that Documenter pushes to a different preview branch for each pull request. This results in a whole lot of preview branches that I forget to delete.

But, if Franklin only uses a single `gh-preview` branch, then this is much more manageable.

> Limitations: if a non-contributor opens a PR, the build will fail, this is because either it's not possible (or I haven't figured out how) to get a non-contributor to trigger a github action (I imagine for security reason?)

For security reasons GitHub doesn't let a PR from a fork have write/push access. So you can't let forks push previews. But you could allow that step of the GitHub Action to fail, so that the overall status of the Franklin action is still green.

**Comment by DilumAluthge** [comment]
I think I have it working: https://github.com/JuliaHealth/juliahealth.github.io/pull/20

In particular, I think I have it set up so that if a non-collaborator makes a PR from a fork, it shouldn't cause the build to fail.

@tlienart Would you be willing to make a PR to https://github.com/JuliaHealth/juliahealth.github.io ? Then we can test this theory out.

**Comment by DilumAluthge** [comment]
Closing this as fixed by https://github.com/JuliaHealth/juliahealth.github.io/pull/20 and https://github.com/JuliaHealth/juliahealth.github.io/pull/22
