### ISSUE TITLE
Make showing code output easier

### ISSUE THREAD

**Issue by newptcai** [tlienart/Franklin.jl#484]
Right now if I want to show the output of a code block I have to use
``````
```julia:./napoleon_rand-2.jl
napoleon_rand()
savefig(joinpath(@OUTPUT, "napoleon_rand-2.svg")) # hide
```
\output{./napoleon_rand-2}
\fig{./napoleon_rand-2}
``````
This works, but it gets really tedious if there are many blocks. Maybe these can all be abbreviated? For the file names we can use some random name to avoid conflicts.

**Comment by tlienart** [comment]
Right so this kind of usecase is *precisely* why Franklin allows the definition of commands. 

In your case consider

`````
\newcommand{\example}[2]{
```julia:./!#1 
#2 
savefig(joinpath(@OUTPUT, "!#1.svg")) # hide
```
\output{./!#1}
\fig{./!#1}
}
`````

which you can use like

```
\example{napoleon_rand-2}{napoleon_rand()}
```

**Comment by newptcai** [comment]
Thanks. That will do.
