### ISSUE TITLE
GitHub deployment missing pages.

### ISSUE THREAD

**Issue by newptcai** [tlienart/Franklin.jl#486]
I have tried to push to a branch to Guthub to tigger an action to deploy. The run was successful but somehow some pages are missing.  You can find all code here.

https://github.com/newptcai/PlaneGeometry.jl

I manually pushed to gh-pages in the end.

**Comment by tlienart** [comment]
There's not enough information here to help you. Provided your site is generated properly locally with `serve(clear=true)` then the same will happen with the GA.

**Comment by newptcai** [comment]
I will try a few more time and see if I can reproduce it. Also perhaps you should mention in the document that python dependency need to be installed explicitly in workflow. 

Also a make file that directly push to gh-page branch may more desirable than a github workflow. The later is a bit slow.

**Comment by tlienart** [comment]
Python is only needed if you want to use the minification step, it's not mandatory. (a message will be shown but that's it). Oh and of course if you use PyPlot...

There's also the `publish` function that you can use if you want to directly push to gh-pages.

**Comment by newptcai** [comment]
Oh I meant to say that the website l was developing uses SymPy so it needs to be installed  in the workflow.

**Comment by tlienart** [comment]
oh right! :+1:

**Comment by tlienart** [comment]
I think this is not an issue anymore (otherwise please feel free to re-open, thanks)
