### ISSUE TITLE
add `nop` mode to fd2html to avoid <p>...</p>

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#489]
If people end up using fd2html inside hfuns then not only will  they want to  use `internal=true` but also something that discards `<p>...</p>` at the  beginning and end of the string which might otherwise mess up their CSS.

**Comment by findmyway** [comment]
>  also something that discards `<p>...</p>` at the beginning and end of the string which might otherwise mess up their CSS.

Just hit this problem......
