### ISSUE TITLE
css / deployment error ?

### ISSUE THREAD

**Issue by tbeason** [tlienart/Franklin.jl#490]
Weird issue I think. I'm making a very minimal site. I just want it to have (1) some plain text, (2) a styled table on it, which is loaded from csv, and (3) a button. I created an `hfun` to load the table and create the html (very cool!). Styling is provided by the newly released Bootstrap 4.5 and a custom css file that as of now only contains one entry (the `.page-foot` entry from the Franklin template).

The site serves fine locally, here is a screenshot (obviously not done styling).

![Screenshot from 2020-05-14 10-00-36](https://user-images.githubusercontent.com/10752449/81963486-0222f800-95ca-11ea-8c13-510e3790c61d.png)

When deployed via the provided gh action, it seems like the css styles are not being applied. 

Here is the deployed site: https://tbeason.com/financeconferences-testing/

Repo: https://github.com/tbeason/financeconferences-testing

**Comment by tlienart** [comment]
Did you set the `prepath` properly?

**Comment by tbeason** [comment]
Dang didn't I JUST help somebody with this same issue?? :rofl: 
Anyways, it's all good now.

Just some final css touches and it'll be done. Way easier than the way I was doing it before (somebody else's custom javascript + jquery datatables)

**Comment by tlienart** [comment]
Please ping me when it’s done I’d love to look at what you did in details!
