### ISSUE TITLE
Franklin github tag

### ISSUE THREAD

**Issue by chakravala** [tlienart/Franklin.jl#495]
Greetings, I'd like to recommend that users of `Franklin` tag their website source repositories with the GitHub tag [franklin](https://github.com/topics/franklin) to make it easier to find examples and get ideas for customization.

Perhaps this can be suggested in the documentation.

**Comment by tlienart** [comment]
Yes that’s an excellent idea thanks

**Comment by tlienart** [comment]
added to the readme as well.
