### ISSUE TITLE
Correct image path?

### ISSUE THREAD

**Issue by KajWiik** [tlienart/Franklin.jl#499]
Let's say that I have a page in directory /chopper. According to instructions in https://franklinjl.org/syntax/markdown/#inserting_a_figure, when I put an image to /chopper/output/julia.png and reference it in md like:
```
\fig{julia}
```
I get the following error:
```
// Image matching '/assets/chopper/code/julia' not found. //
```
Where should I put the figure, there is no path like `/assets/chopper/code/julia`?

**Comment by tlienart** [comment]
Hello! sorry for the confusion. You can use an image without path **only** if that image was generated by code within Franklin.

In your case you could equivalently use one of the following:

```
\fig{/chopper/output/julia.png}
![](/chopper/output/julia.png)
```

I would recommend (but you can do what you want) to put your images in `_assets` for instance in `_assets/chopper/...` the paths are then extended with `/assets/` 

```
\fig{/assets/chopper/output/julia.png}
![](/assets/chopper/output/julia.png)
```

**Comment by tlienart** [comment]
You can also look at the source code of the page you linked to if that helps: https://github.com/tlienart/franklindocs/blob/master/syntax/markdown.md#inserting-a-figure

**Comment by tlienart** [comment]
I'll close this  in favour of the issue I opened in your repo: https://github.com/KajWiik/KajWiik.github.io/issues/1

**Comment by KajWiik** [comment]
I see it now, many thanks!
