### ISSUE TITLE
Troubles with quotes spanning multiple rows.

### ISSUE THREAD

**Issue by lucaferranti** [tlienart/Franklin.jl#525]
Franklin is not able to render quotes spanning multiple rows. The classical markdown syntax:
```
> row 1
>
> row 2
>
> row 3
```
is not rendered correctly. In the final html version all newlines are suppressed.

**Comment by tlienart** [comment]
For others who have this issue, adding `\\` at the end of lines fixes the issue.

The eventual use of commonMark.jl should fix the rest
