### ISSUE TITLE
How to ignore a file and/or directory?

### ISSUE THREAD

**Issue by DilumAluthge** [tlienart/Franklin.jl#548]
I have a MWE here: https://github.com/bcbi/test_franklin

I have a file located in my repository at `/CONTRIBUTING.md`:
- https://github.com/bcbi/test_franklin/blob/master/CONTRIBUTING.md

Franklin is including this file when it builds and deploys my site:
- https://github.com/bcbi/test_franklin/blob/gh-pages/CONTRIBUTING/
- https://github.com/bcbi/test_franklin/blob/gh-pages/CONTRIBUTING/index.html
- https://bcbi.github.io/test_franklin/CONTRIBUTING/
- https://bcbi.github.io/test_franklin/CONTRIBUTING/index.html

Is there a way that I can tell Franklin to exclude the `/CONTRIBUTING.md` file when it builds and deploys my site?

cc: @tlienart

**Comment by tlienart** [comment]
yes, in your `config.md` add

```
@def ignore = ["path/to/file.ext", "path/to/dir/"]
```

the first one for a specific file, the second one for an entire dir. See https://franklinjl.org/syntax/page-variables/index.html#global_page_variables

**Comment by DilumAluthge** [comment]
Perfect!

**Comment by DilumAluthge** [comment]
I notice that, by default, you ignore `README.md`.

If I set
```
@def ignore = ["CONTRIBUTING.md"]
```

Then it will ignore both `CONTRIBUTING.md` and `README.md`, right?
