### ISSUE TITLE
Too many <p></p> sometimes

### ISSUE THREAD

**Issue by Wikunia** [tlienart/Franklin.jl#549]
This is done by #546 . Sorry that I didn't realize that before but it seems like you haven't created a new version for this yet. 

I think you have this as an example to create notes somewhere:

```
\newcommand{\note}[1]{@@note @@title ⚠ Note@@ @@content #1 @@ @@}
```

If I use `\note{This is a test}` it creates:

```
<div class="note"><div class="title">⚠ Note</div></p>
<p><div class="content">This is a test</div><div>
```

and before it was the expected: 

```
<div class="note"><div class="title">⚠ Note</div> <div class="content">This is a text</div></div>
```

The new version gets interpreted as 

```diff
-<div class="note"><div class="title">⚠ Note</div></p>
+<div class="note"><div class="title">⚠ Note</div><p></p>
-<p><div class="content">This is a test</div><div>
+<p></p><div class="content">This is a test</div><div>
```

at least in Chrome and in general it's not desired :smile: 

For users of the website this will create a weird padding between the title and the content.

**Comment by tlienart** [comment]
Good spot, thanks; yes resolving the inside of a div block recursively is a bit tricky.
