### ISSUE TITLE
Feature request: Read config variables from the environment

### ISSUE THREAD

**Issue by DilumAluthge** [tlienart/Franklin.jl#550]
Instead of hard-coding variable values in `config.md`, I'd like to use values from environment variables, using a fallback value provided in `config.md`.

For example, suppose I have the following content in `config.md`:
```md
@def website_url = "https://bcbi.github.io/bidss/"
@def prepath     = "bidss"
```

What I would like is to have something equivalent to the following Julia code:
```julia
website_url = get(ENV, "JULIA_FRANKLIN_WEBSITE_URL", "https://bcbi.github.io/bidss/")
prepath     = get(ENV, "JULIA_FRANKLIN_PREPATH",     "bidss")
```

Is this currently possible in Franklin? If not, would it be possible to add it as a feature?

**Comment by tlienart** [comment]
everything that is on the right side of the `=` of a `@def` is parsed as Julia code so you should be able to do exactly what you said:

```
@def website_url = get(ENV, "JULIA_FRANKLIN_WEBSITE_URL", "https://bcbi.github.io/bidss/")
@def prepath     = get(ENV, "JULIA_FRANKLIN_PREPATH",     "bidss")
```

if it doesn't work please let me know as it's a bug

**Comment by tlienart** [comment]
(in another project I even did this:

```
@def var = (include("foo.jl"); bar) 
```

where `foo.jl` was a script that defined `bar`. For i18n it's good bc you can have a separate file where you define a big ass dictionary with all the correspondences and then you can just bring it in Franklin's net with the kind of syntax above.

**Comment by DilumAluthge** [comment]
Works perfectly, thanks! See e.g. https://github.com/JuliaHealth/juliahealth.github.io/pull/74
