### ISSUE TITLE
Support for Google Analytics

### ISSUE THREAD

**Issue by JackRab** [tlienart/Franklin.jl#554]
Hi Thibaut,

Thanks for your work on this terrific package. 

I don't see any issues related to Google Analytics. I switch from [Academics theme](https://sourcethemes.com/academic/) in Hugo to Franklin. I see there Google Analytics is supported using [gtag.js](https://developers.google.com/analytics/devguides/collection/gtagjs). I am wondering if there is some support for using Google Analytics now. Or maybe you can give me some guidance of how to set this up. 

Thanks in advance for your help.

**Comment by tlienart** [comment]
Hello, if I’m not mistaken you’ll get GA support just by dropping a few lines of JavaScript in the `_layout/head.html`; see for instance the JuliaLang.org repo where that file (or one of the neighbouring file) has the GA stuff (no more than 5 lines IIRC which just indicate an ID number)

Let me know if that doesn’t work for you!

**Comment by tlienart** [comment]
```html
<script type="application/javascript">
	var doNotTrack = false;
	if (!doNotTrack) {
		window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
		ga('create', 'UA-28835595-1', 'auto');
		ga('send', 'pageview');
	}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
```

See `_layout/head_scripts.html` in that repo

**Comment by tlienart** [comment]
Ps: let me know how the move from academic theme goes please; I’d like to bring that port to Franklin soon but there’s one thing Franklin is missing at this point: pagination; this should be in soon...

**Comment by JackRab** [comment]
Awesome. It works very well. 

For your question about the move from the academic theme, it went quite smoothly since what I have and need are quite basic. I just ported your personal website and modified the CSS theme for a few places. You may have look at my academic website [here](https://yiminyi.site/).

Thanks a lot for your help.

**Comment by tlienart** [comment]
very nice, I like the folding abstract! (you might want to use a slightly different font or font colour to distinguish the content).

great stuff and glad that GA works well for you :+1:

**Comment by tlienart** [comment]
ah and @JackRab you will want to change the favicon (currently it's the default red question mark)

**Comment by JackRab** [comment]
Yes, actually I like the default question mark favicon. It seems to me quite conform with the academic purpose. 

Thanks for your suggestion about font settings. I'd like to adjust them at some time. 

I don't know if this is related to Franklin.jl but I guess you know better than me. I would like to have lines rendered with equal width just like what LaTeX does. Like in [this](https://jblevins.org/projects/markdown-mode/)

![image](https://user-images.githubusercontent.com/650460/87581357-cc23f200-c6a6-11ea-981d-1f6e337df7e7.png)

instead of 

![image](https://user-images.githubusercontent.com/650460/87582131-f2965d00-c6a7-11ea-8444-8847f8554f97.png)

I wonder if this is easily possible with Franklin. Thanks for your comments.

**Comment by tlienart** [comment]
You can look up “justified text with CSS” and you can set it in your CSS file; note that using justified text online is discouraged as it can be very ugly in some settings (for latex everything is super optimised for one page size but on web you could have any page size and the browser has to reflow the text accordingly)


https://designforhackers.com/blog/justify-text-html-css/

**Comment by JackRab** [comment]
I see. Thanks.
