### ISSUE TITLE
Feature request: automatically generate the custom 404 page for GitHub Pages

### ISSUE THREAD

**Issue by DilumAluthge** [tlienart/Franklin.jl#560]
GitHub Pages allows the user to display a custom 404 page: https://docs.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

It would be great if, as part of the build, Franklin could automatically generate a custom 404 page for use with GitHub Pages.

Obviously I can just manually add a `/404.html` page myself. But I would like to have a 404 page that matches the style and layout of my Franklin site.

cc: @tlienart

**Comment by tlienart** [comment]
Right so if you write a `404.md` then it has the style etc of the rest of your site, this is what is done with the Julia website for instance:

https://julialang.org/doesnotexist.html

source:  https://github.com/JuliaLang/www.julialang.org/blob/master/404.md 

but I agree that the default templates should ship with it.

**Comment by DilumAluthge** [comment]
I can try to make a PR to add this to the default template.

Would I make a PR to Franklin.jl or FranklinTemplates.jl?

**Comment by tlienart** [comment]
It would go in FranklinTemplates the "common" subfolder alongside `index.md` a PR would be great, thank you!
