### ISSUE TITLE
Feature request related to Franklin.jl

### ISSUE THREAD

**Issue by fusion809** [tlienart/Franklin.jl#565]
I thought you'd appreciate being informed that I've filed a feature request at Microsoft/vscode#103132 that is essentially a request for Visual Studio Code's default Markdown support to include support for Franklin-enhanced Markdown.

**Comment by tlienart** [comment]
Thanks!

**Comment by flyaflya** [comment]
this seems to have fizzled.  I would love for code blocks in an .md file that start ```julia:blockName ...

to get highlighted.  Has any extension been enhanced to do this in vscode?

**Comment by tlienart** [comment]
the issue mentioned above is probably the right place to ask for such things (or discourse) but I expect the answer is "no".

Also bear in mind that even though `Julia` code blocks might get properly highlighted, the Franklin style 

````
```julia:name
...
```
or
```!
...
```

````

likely won't be for quite a while as it's not standard Markdown.

**Comment by flyaflya** [comment]
Thx for the quick reply!  Franklin is really great.  The VSCode issue you reference above got closed so it seems that path is a dead end... we just need to find someone with the skillset to modify a VSCode extension.  

I think it might be as simple as modifying one line in the "Markdown Julia" extension (see code below).  I put in an issue request there even though it does not seem actively maintained:  https://github.com/colinfang/markdown-julia/issues/2

If you know someone who knows regular expressions well, I really think the feature can be added quite easily to the "Markdown Julia" extension.  My guess is the only change is to one or two lines within these 46 lines of the extension's core JSON logic:

```
{
    "fileTypes": [],
    "injectionSelector": "L:text.html.markdown",
    "patterns": [
        {
            "include": "#fenced_code_block_julia"
        }
    ],
    "repository": {
        "fenced_code_block_julia": {
            "begin": "(^|\\G)(\\s*)(`{3,}|~{3,})\\s*(?i:(julia)((\\s+|:|\\{)[^`~]*)?$)",
            "name": "markup.fenced_code.block.markdown",
            "end": "(^|\\G)(\\2|\\s{0,3})(\\3)\\s*$",
            "beginCaptures": {
                "3": {
                    "name": "punctuation.definition.markdown"
                },
                "4": {
                    "name": "fenced_code.block.language"
                },
                "5": {
                    "name": "fenced_code.block.language.attributes"
                }
            },
            "endCaptures": {
                "3": {
                    "name": "punctuation.definition.markdown"
                }
            },
            "patterns": [
                {
                    "begin": "(^|\\G)(\\s*)(.*)",
                    "while": "(^|\\G)(?!\\s*([`~]{3,})\\s*$)",
                    "contentName": "meta.embedded.block.julia",
                    "patterns": [
                        {
                            "include": "source.julia"
                        }
                    ]
                }
            ]
        }
    },
    "scopeName": "markdown.julia.codeblock"
}
```
