### ISSUE TITLE
allow ignoring files at optimisation step

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#568]
much ligne the `ignore` variable, there should be a `optimize_ignore` in order to avoid minifying or prerendering specific pages as either step can sometimes cause issues.

**Comment by tlienart** [comment]
also it should be in the FAQ that if something works locally and not online then it's the optimization step that did something wrong. I actually think that may already be in there but need to check...

**Comment by fredrikekre** [comment]
This would be another use case for static content: https://github.com/tlienart/Franklin.jl/issues/410

**Comment by tlienart** [comment]
Hmm I'm still not convinced but I think that, in this case, the error is that the minifier also looks at what's in `_assets` and that breaks the idea that what is in there is left untouched and copied as is by Franklin.
