### ISSUE TITLE
Processing hfuns before all global vars are fully populated

### ISSUE THREAD

**Issue by mcognetta** [tlienart/Franklin.jl#582]
Opening this issue per @tlienart 's request on Slack. Also cc'ing @fredrikekre who was involved in the thread.

Currently, `process_utils` is called before all global variables are fully populated. As such, if an `hfun` depends on some global variable, it is possible for it to be called with incomplete information. You may see [here](https://github.com/tlienart/Franklin.jl/blob/c2a7017dfccd9dd376306c98e4daad6a502f9a6a/src/manager/franklin.jl#L223) for the line where `process_utils` is called but [several lines later](https://github.com/tlienart/Franklin.jl/blob/c2a7017dfccd9dd376306c98e4daad6a502f9a6a/src/manager/franklin.jl#L248) is when the first actual pass of the files is done.

Below is an MWE:

1. Make a new site with some tagged articles (I used one of the default themes as is)
2. Make the following `hfun` in `utils.jl`:
```julia
function hfun_test_population()
  println(Franklin.globvar("fd_page_tags"))
  return ""
end
```
3. Put the following in your `table.html` file
 `<div>{{ test_population }}</div>`

4. Call `serve()`

You will see that the first time `hfun_test_population` is called (and the `{{ test_population }}` is processed), the dictionary is only partially complete.

---------------------------------------------------------------------------

One possible fix is to make a separate "metadata pass" in which all of the static global/local variables (authors, dates, tags, titles, etc.) are precomputed without converting the markdown/html. Then, on the second pass, the util functions will all have access to the complete information when being processed. The downside of this is that the entire site has to be processed twice (but still only converted once), which takes time. It could possibly be integrated into [`scan_input_dir!`](https://github.com/tlienart/Franklin.jl/blob/445d80a71657119e612f44af40b837f743323dcc/src/manager/dir_utils.jl#L108).

**Comment by tlienart** [comment]
Just for the context Marco, what were you trying to achieve initially? thanks (and thanks for the detailed issue!)

**Comment by mcognetta** [comment]
For context, what I wanted to do was have a section of the side bar that had links to the top 5 tags by post count. I also wanted a "tag landing page" which would be at :site/tag. This was so a user didn't have to search for tags by going through posts and then going to :site/tag/code to see all the pages with the code tag. The hfuns I wrote for these two things are here (please let me know if you see an issue with them, though, other than the bug in this issue, they worked fine):

```julia
function hfun_tag_landing_page()
  PAGE_TAGS = Franklin.pagevar("fd_page_tags")
  TAG_COUNT = Franklin.invert_dict(PAGE_TAGS)
  markdown = ""
  for k in sort(collect(keys(TAG_COUNT)))
    markdown *= "* ["*k*"](" * Franklin.joinpath("/tag/", k) * ") (" * string(length(TAG_COUNT[k])) * ")\n"
  end
  return fd2html(markdown, internal=true)
end

function hfun_tag_side_bar()
  PAGE_TAGS = Franklin.pagevar("fd_page_tags")
  TAG_COUNT = Franklin.invert_dict(PAGE_TAGS)
  markdown = ""
  # we want (tag, postcount) tuples to be ordered lexicographically by descending post count and then by
  # ascending alphabetical order.
  for k in sort(collect(keys(TAG_COUNT)), by=x->(-length(TAG_COUNT[x]), x))[1:(min(length(keys(TAG_COUNT)), 5))]
    markdown *= "* ["*k*"](" * Franklin.joinpath("/tag/", k) * ") (" * string(length(TAG_COUNT[k])) * ")\n"
  end
  return fd2html(markdown, internal=true)
end
```

What I noticed is that pages had only the tag information that was present in the pages that were ancestors of it on the path back up to the root directory. So like the main index.md page had only it's tags in the side bar, but a really nested page would have many more.

**Comment by mcognetta** [comment]
Here are some things that I tried to resolve the problem. None of them worked, though that may have just been cause I did it wrong.

- I made a `FD_ENV :METADATA_PASS` variable which acted sort of like `FD_ENV :FULL_PASS`. Essentially, the very first time that a full pass was completed, `METADATA_PASS` was set to true. Then, I made all of the statements that actually converted code have `FD_ENV[:METADATA_PASS] || <previous code>`. Then, I just made serve call `fd_full_pass` twice and change `FD_ENV[:METADATA_PASS]` to false after the first one. This didn't work but I can't remember why (I think some hfun variables were being called before they were defined).

- I tried to use `FD_ENV[:FULL_PASS]` to change what the hfuns were outputting. My understanding was that `FD_ENV[:FULL_PASS]` is set to false after the first full pass is done (at which time all global vars should be fully populated). So, I made my hfun something like 

```julia
function hfun_test_example()
     !FD_ENV[:FULL_PASS] || return "{{ test_example }}"
    # original code here
end
```
The idea here was that we should continuously replace "{{ test_example }}" with itself until all the global variables are set before replacing it with the html that we really wanted. Each time that `process_utils` was called it would reprocess "{{ test_example }}" until the full pass was done. This didn't work as it would just replace it with "{{ test_example }}" once which would appear as plain text in the final page. It is very likely that I just don't understand how html works or how the hfuns are supposed to replace stuff. Nevertheless, it would be a nice feature if we could return `nothing` from an hfun to delay its processing.

- I tried moving around when `process_utils` and `generate_tag_pages` but I ran into the same issues from point 1 where it would crash because some variables were being called before their definition.

**Comment by tlienart** [comment]
Thanks a lot for all this careful thinking, I need to take some time to try this myself carefully and see what can be done to better support it; I think your initial analysis of the necessary "double pass" is correct with one pass that solely looks at page var definitions. There may be a way to do this cleverly so that either

- there's a parsing phase which ignores everything that's not `@def` (that should be pretty quick and is probably the easiest option) and then a second phase which looks at everything
- there's a single full parsing phase but the ordering of when blocks are processed is done more carefully to ensure that when `hfun` are processed, all page vars are available, this would require parsing each page, storing the blocks, and then doing a pass where each page is built

The second one has the advantage of a single pass but would require storing a fair bit of stuff for sites which have many pages like julialang (though in the grand scheme of things it's probably very little by modern computing standards). 

I think I'll try the first one which is simpler and, assuming it doesn't have too much of an impact on the speed of processing (my hunch is that it won't) then that's probably the easiest option.

**Comment by ericphanson** [comment]
Just to say that I ran into this too, also in the context of tags. I wanted to create a page listing the tags and showing their relative popularity, and then have each one link to a summary page for that tag listing all the posts with the tag, which sounds basically exactly the same as @MarcMush was doing.

One possible way to fix it could be to do some dependency analysis like Pluto.jl does, to figure out what order to execute the Julia code. It occurs to me that a website is kind of like a notebook where the cells are scattered across different pages :).

**Comment by tlienart** [comment]
Alright, I think I have a satisfactory first attempt at this which is in branch `v010`. I would appreciate if you could give it a shot and let me know what you think. It introduces a macro `@delay` for `hfun` definition which need the full scope (i.e. the completion of a full pass) to be done properly. When a function is marked as `@delay` then every page which calls it will be re-built after the first pass.

Here's an example from the OP:

**`utils.jl`**

```
@delay function hfun_test_population()
    all_tags = globvar("fd_page_tags")
    if all_tags === nothing
        return ""
    end
    all_tags = union(values(all_tags)...)
    tagstr = strip(prod("$t " for t in all_tags))
    return "<p>ALL TAGS: $tagstr</p>"
end
```

use in `index.md`:

```
@def tags = ["tag1", "tag2"]
{{test_population}}
```

in `menu1.md`

```
@def tags = ["tag2", "tag3"]
```

upon `serve()` with no modification:

![Screenshot 2020-09-18 at 15 42 56](https://user-images.githubusercontent.com/10897531/93604527-c5c33680-f9c5-11ea-8261-35d018c9d303.png)

This is very fast, and, assuming you only have a few such functions, it only requires one or two pages maybe to re-build a second time (so maybe an extra `10ms`) which seems reasonable. 

Feedback welcome!

**Comment by mcognetta** [comment]
I like this approach. `delay` isn't a bad choice (especially if later usage allows delaying until some global variable matches a condition, like `@delay_until(FULLPASS)`. I will test it out and let you know if I run into issues.

**Comment by tlienart** [comment]
Awesome, thanks!

**Comment by tlienart** [comment]
now released
