### ISSUE TITLE
how to generate all the website contents?

### ISSUE THREAD

**Issue by feima0011** [tlienart/Franklin.jl#586]
How to generate all the website contents, 
which I can upload to a local server (do not rely julia)?

**Comment by tlienart** [comment]
`serve()` will generate everything in `__site/` you can then take the content of that folder and put it where you want. 

The easier route involves using GitHub or GitLab or a similar service which can deploy things for you (see documentation). They can host the content themselves or you can redirect other services to serve a specific branch from them.

If you want to do this yourself on your own server, then you'll need to take the content of `__site/` and put it in the appropriate location manually (or write your own functionality which does this for you).
