### ISSUE TITLE
loose lists only?

### ISSUE THREAD

**Issue by tbeason** [tlienart/Franklin.jl#594]
I can't seem to get anything other than a loose list, which has space between each item. This happens because each item ends up wrapped in `<p>` tags.

```
* Item 1
* Item 2
```
becomes
```
<ul>
<li><p>Item 1</p>
</li>
<li><p>Item 2</p>
</li>
</ul>
```

whereas a tight list would be
```
<ul>
<li>Item 1</li>
<li>Item 2</li>
</ul>
```

For now I've just inserted the proper HTML with `~~~`. Wasn't sure if there was a Franklin `@@` insertion that would work since a list isn't normally its own container/element.

**Comment by tlienart** [comment]
Hello, yes this is an issue with the Base Markdown converter (not Franklin), but you can remove the effect by making the p have zero margin in a list something like 

```css
li p { margin 0;}
```

If you don't want that everywhere you can add a div like `@@tlist` with a more specific rule 


```css
.tlist li p { margin 0;}
```

**Comment by fredrikekre** [comment]
Am I missing something or why can't Franklin look at the `.loose` field?
```
julia> m = md"""
        - a
        - b
        
        
        - a
        
        - b""";

julia> m.content
2-element Array{Any,1}:
 Markdown.List(Any[Any[Markdown.Paragraph(Any["a"])], Any[Markdown.Paragraph(Any["b"])]], -1, false)
 Markdown.List(Any[Any[Markdown.Paragraph(Any["a"])], Any[Markdown.Paragraph(Any["b"])]], -1, true)

julia> m.content[1].loose
false

julia> m.content[2].loose
true
```

**Comment by fredrikekre** [comment]
I guess this implementation is wrong:
```
julia> show(stdout, MIME("text/html"), m)
<div class="markdown"><ul>
<li><p>a</p>
</li>
<li><p>b</p>
</li>
</ul>
<ul>
<li><p>a</p>
</li>
<li><p>b</p>
</li>
</ul>
</div>
```

**Comment by tlienart** [comment]
yes the latter, see 

* https://github.com/JuliaLang/julia/issues/30198
* https://discourse.julialang.org/t/parsing-markdown-lists-add-paragraph-to-items/36169

**Comment by tbeason** [comment]
Thanks for the workaround. I went with 
```
ul li p { margin: 0;}
```
because I think any list that I'm ever going to display should probably be tight. The loose lists have way too much space.

**Comment by tlienart** [comment]
Yeah makes sense. Maybe just check nested list are ok for you.

I'll probably add this default CSS in the templates

**Comment by tlienart** [comment]
closing (there's an issue on FraknlinTemplates 87 for my last comment)
