### ISSUE TITLE
Prepath variable not applied to tag pages

### ISSUE THREAD

**Issue by epatters** [tlienart/Franklin.jl#602]
I'm using the `prepath` configuration variable. For my regular pages, it rewrites the CSS links in `<head>` as expected, however the links in my tag pages are not rewritten.

My `_layout/tag.html` file is the default one is the `basic` theme.

**Comment by tlienart** [comment]
Thanks for reporting this! It definitely should, and it's an easy fix; I'll try to sort this out asap

**Comment by tlienart** [comment]
Hmm, I'll nee more info for this one, I just  checked with this  [dummy repo](https://github.com/tlienart2/myWebsite) and it seems to work fine (e.g. https://tlienart2.github.io/myWebsite/tag/tag1/ and https://tlienart2.github.io/myWebsite/tag/tag2/)

Could you point me to  a  repo where you tried this? (or add me as a collaborator if it's a private repo).

Thanks!

**Comment by epatters** [comment]
Thank you for investigating! Let me first compare the dummy repo with my own and see if I can reproduce the problem in that context.

**Comment by tlienart** [comment]
great, thanks!

**Comment by epatters** [comment]
Actually, now that I look closer, I see the problem on the repo you made. The links to point to `https://tlienart2.github.io/menu1/` and `https://tlienart2.github.io/`, **without** the `myWebsite` prefix. I assume the links work when you click them because there is another dummy website deployed to the root path.

**Comment by tlienart** [comment]
Ah yes you're right, I should have looked a bit more but thought you were talking about the URL of the tag page and not the actual links on the tag page.

Ok that's definitely a bug, thanks for reporting!!

**Comment by tlienart** [comment]
ok I've got a fix, am doing a bit more testing and will release it soon

**Comment by epatters** [comment]
Sounds good, thank you!
