### ISSUE TITLE
Paths in hfun- functions

### ISSUE THREAD

**Issue by cormullion** [tlienart/Franklin.jl#607]
I've started defining some `hfun` functions that generate images, and it's working really well, although there's one thing I've got confused about, and can't work out. Perhaps your more enlightened eyes can see the solution:

Here's the setup:

```
└───
    └───config.md
    └───index.md
    └───package-lock.json
    └───utils.jl                     <******************** [C] the location of the hfun- function
    └───__site
        └───feed.xml
        └───index.html
        └───package-lock.json
        └───utils.jl
        └───assets
            └───images
                └───thepost
                    └───pic1.png     <******************** [D] the final destination for the copied image
    └───_assets
        └───fonts
        └───images
            └───background.png
            └───thepost              <******************** [B] the directory for images in the post
                └───pic1.png
    └───_css
        └───basic.css
    └───_layout
    └───_libs
    └───pages
        └───2020-09-04-thepost.md    <******************** [A] 'thepost' is the Markdown post
```

So in [A] I insert a call to `hfun-` function (with `{{ func() }}`) which calls the function in [C] which needs to create an image in [B], so that it'll be copied to [D] ready for uploading.

But I don't know how to specify the path to [B] in a function defined in [C] and called from [A]. Is there some variable I can use?

**Comment by tlienart** [comment]
Ok so what needs to happen is that the output of the hfun is HTML which has the right final path (without prepath, that gets fixed automatically) so the hfun needs to produce HTML with a img with source `/assets/images/thepost/pic1.png`. 

Now if you're going to use that kind of path a lot in hfuns, you could define a `const IMGPATH = "/assets/images/"` in `utils.jl` and thereafter append the rest as needed (and the rest could be passed as argument to the function).

Note that there is a sidekick to hfuns which are the `lx*` functions, these work in a similar way except that their output is plugged in as markdown (and then processed by Franklin); in a way they're like Julia macros. So with those you could use the relative paths approches that you're already used to with `./...` etc. Depending on how often and how you call the functionality one or the other might be preferred

**Comment by cormullion** [comment]
Thanks so much! I'll do some experimenting and see what happens.
