### ISSUE TITLE
Franklin 0.9.14 broke code sections

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/Franklin.jl#612]
E.g. from https://julialang.org/blog/2020/08/invalidations/

```
f&#40;x::Int&#41; &#61; 1
applyf&#40;container&#41; &#61; f&#40;container&#91;1&#93;&#41;
```
Looks like #610 is the problem.

**Comment by tlienart** [comment]
thanks for the quick reaction; will look into this

**Comment by tlienart** [comment]
Hmm it's the prerendering via highlight that messes up ...

**Comment by tlienart** [comment]
ok I have a fix for it, am doing a round of testing then will push a patch release
