### ISSUE TITLE
Blog listing and access details pages variable like title, category, etc.

### ISSUE THREAD

**Issue by pakzy** [tlienart/Franklin.jl#613]
Hi Tlienart,

I found the way(mention below) to list all the blogs in blog listing page. But i am not able to access blog detail page variables like title, category, etc. Also sorting based on publish date. Could you please help for this documentation ?

@def subpages1 = ["foo/", "blah/"]

{{for page in subpages1}}
<a href="{{ page }}">{{ page title }}</a>
{{ end }}

**Comment by tlienart** [comment]
Hello @pakzy you can use `pagevar` to retrieve this information, please have a look at [this example](https://github.com/JuliaLang/www.julialang.org/blob/e075d9a4b042fb3373262709c46efd0c3ed0e051/utils.jl#L27-L68)

**Comment by pakzy** [comment]
Hi Tlienart,

Thanks for this documents.

I am getting this error: ERROR: LoadError: LoadError: UndefVarError: @dateformat_str not defined

**Comment by tlienart** [comment]
This is not a Franklin error but something to do with whether you have the proper libraries loaded; do you have a `using Dates` somewhere?

**Comment by pakzy** [comment]
Hi Tlienart,

Thanks, that was my bad, i didn't mention using Date.... its working fine now..... Will bother you again if i get stuck somewhere :)

**Comment by tlienart** [comment]
cool thanks, don't hesitate to reach out on Slack `#Franklin` ; it's a bit more appropriate for this kind of stuff :)
