### ISSUE TITLE
ERROR: IOError: could not spawn `/purgecss/bin/purgecss`

### ISSUE THREAD

**Issue by fonsp** [tlienart/Franklin.jl#619]
My GitHub action builds are failing today, here is the error:
https://github.com/mitmath/18S191/runs/1143435492?check_suite_focus=true#step:5:110

I did not change any frontend files in that commit, I only added a static resource.

**Comment by fonsp** [comment]
How can I disable the `purgecss` step as a workaround?

**Comment by tlienart** [comment]
This is with PkgPage, you can add `purge=false` in this line: https://github.com/mitmath/18S191/blob/273609f250e82ca75ca77193e99dd0af88ee61df/.github/workflows/DeployPage.yml#L45

Can you give me collab access to the repo and I'll try to see what's going on?

**Comment by fonsp** [comment]
https://github.com/FullHuman/purgecss just released 3.0.0, I guess we should fix the dependency to `2.x`?

**Comment by fonsp** [comment]
I've added you :) https://github.com/mitmath/18S191/invitations

**Comment by fonsp** [comment]
I'll try `purge=false` now

**Comment by tlienart** [comment]
why are you using PkgPage actually? the error stems from the file `bootstrap.min.css` not being found but you're not using bootstrap; I think you should just remove `PkgPage`, remove `purge` and use `Franklin.optimize`. But I can try that so that you don't waste time on it

**Comment by fonsp** [comment]
I'm not sure why we use PkgPage :) Shashi set it up - I have never used Franklin with CI before

**Comment by tlienart** [comment]
Ok let me try to clean that up and suggest a PR

**Comment by fonsp** [comment]
> I'll try `purge=false` now - [here is the action run](https://github.com/mitmath/18S191/actions/runs/264980074)

It worked! Feel free to continue debugging
