### ISSUE TITLE
Support the \newenvironment tag along with \newcommand

### ISSUE THREAD

**Issue by schneiderfelipe** [tlienart/Franklin.jl#630]
It would be nice to be able to define one's own environments. That could greatly increase Franklin's flexibility. Starred (#629) environments would be nice too. (This came from [a comment](https://github.com/tlienart/Franklin.jl/issues/624#issuecomment-699528958) in #624.)

**Comment by tlienart** [comment]
If I understand properly the syntax is 

```
\newenvironment{name}{ {pre}{post} }
```

Used like 

```
\begin{name} content \end{name}
```

To yield 

```
pre content post
```

this requires two things on the Franklin side:

1. support to parse the `\newenvironment` 
2. support to parse and process general `\begin{xxx} ... \end{xxx}` which might be nested

There's a bit of work to get that in but it's fairly straightforward.

**Comment by schneiderfelipe** [comment]
> If I understand properly the syntax is
> 
> ```
> \newenvironment{name}{ {pre}{post} }
> ```

Almost. Actually, the syntax is `\newenvironment{name}{pre}{post}` ([see here](https://pt.overleaf.com/learn/latex/Environments#Defining_a_new_environment)).

> Used like
> 
> ```
> \begin{name} content \end{name}
> ```
> 
> To yield
> 
> ```
> pre content post
> ```

Exactly. That is in some sense a generalization of the `@@name ... @@` syntax.

**Comment by tlienart** [comment]
Cool! I see what you're saying with the generalisation :) 

Anyway I can see this being useful when working with CSS templates like bootstrap where one would have things like `<section ...> ... </section>`

I'll work on this soon

**Comment by tlienart** [comment]
this is actually just as complex as new command given one can also add arguments to it 😱 it'll take me a few days to get this in...
