### ISSUE TITLE
Generating a rel="canonical" link tag

### ISSUE THREAD

**Issue by schneiderfelipe** [tlienart/Franklin.jl#640]
Hi @tlienart, I'm trying to produce a `rel="canonical"` link tag, something close to

```html
<link rel="canonical" href="{{getcanonical}}">
```

The problem is that I can't work out how `hfun_getcanonical` should be implemented, namely, how do I get the path to the current file. (I know I could call `locvar("somevar")` from within `hfun_getcanonical`, but which variable holds the actual name of the file/actual path?)

**Comment by tlienart** [comment]
In the body of the `hfun` you can call `Franklin.url_curpage()` this will return the **relative** url to the current page starting with a `/` so for instance `/index.html``/page/foo/index.html` so you would have to add to that the base url and the prefix something like

```
function hfun_canonical_link()
    rpath = Franklin.url_curpage()
    base = globvar("website_url") # might have to do something if it's empty
    pre = globvar("prepath")
    canonical = joinpath(base, pre, rpath) # might have to check that join path does the right thing 
    return "<link rel=\"canonical\" href=\"$canonical\""
end
```

**Comment by schneiderfelipe** [comment]
Awesome! Thanks for the code @tlienart. It is meant to do almost exactly what I want. Here's what I ended up doing:

```julia
function hfun_canonical_url()
    rpath = Franklin.url_curpage()
    base = globvar("website_url")  # might have to do something if it's empty
    pre = globvar("prepath")

    # might have to check that join path does the right thing
    canonical = joinpath(base, pre, rpath)
    return replace(canonical, r"index\.html$" => "")
end
```

The thing is that I was expecting (if I have `@def website_url   = "http://my-awesome-url.abc"` in `config.md`)

```html
<link rel=canonical  href="http://my-awesome-url.abc/">
```

Instead, I get

```html
<link rel=canonical  href="/">
```

So the code above clearly receives an empty string from `globvar("website_url")`. This happens both locally and in CI builds. Furthermore, I can confirm that all other variables (such as `website_title` and `website_descr`) are used without issues throughout my files. I also use `globvar` with some variables in `utils.jl` without any problem.

Does Franklin treat `website_url` differently than other variables in `config.md`?

**Comment by schneiderfelipe** [comment]
> no no, it's just `joinpath` that is tricking you. Consider the following in the REPL and their result
> 
> ```
> julia> joinpath("http://hello","b")
> "http://hello/b"
> 
> julia> joinpath("http://hello","/b")
> "/b"
> ```
> 
> do you see what's going on? in the second case it thinks it's a path that starts at the root of your file system (`joinpath` is more meant for filesystem use than for URLs) so it ignores everything before it. So you need to strip that first `/` if there is one.

Excellent! [I should have read the documentation 🙈](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.joinpath). The following line did the trick:

```julia
rpath, pre = lstrip.([rpath, pre], ['/'])
```

> Note: sorry that's what I meant with my comment `might want to check...` you want to make sure the `/` are at the right place joy sorry hope you didn't waste too much time on this

That's fine, I only looked into it early today. Thanks by the way!
