### ISSUE TITLE
`Franklin.serve` redirects /page/?query=string to /page/?query=string/

### ISSUE THREAD

**Issue by tkf** [tlienart/Franklin.jl#641]
MWE

1. Checkout https://github.com/JuliaFolds/data-parallelism/commit/5fc32d831256b9ff2e59fde572badc577883765a
2. Run `julia --startup-file=no -e 'import Pkg; Pkg.instantiate()'`
3. Run `bin/serve` (or, in Julia, `cd("src"); using Franklin; serve()`)
4. Open http://localhost:8000/tutorials/quick-introduction/?test=show

Then it is redirected to http://localhost:8000/tutorials/quick-introduction/?test=show/ (note the `/` at the end).

**Comment by fredrikekre** [comment]
It is probably a LiveServer issue, I think here: https://github.com/asprionj/LiveServer.jl/blob/52b4efa7b581f07d29603d178f83853894101cf1/src/server.jl#L79-L94

**Comment by tkf** [comment]
Thanks! Yes, I can reproduce this just with `LiveServer.serve`.
