### ISSUE TITLE
Rebuild doesn't trigger when you change _layout/*

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/Franklin.jl#643]
If you update e.g. `head.html`/`tag.html`/etc the automatic rebuild doesn't trigger.

**Comment by tlienart** [comment]
Hmm, I'll look into this, is this something that used to work for you and now doesn't? 

This: https://github.com/tlienart/Franklin.jl/blob/b014623720be8de65d46e21db9e5823ce8d28b92/src/manager/franklin.jl#L328-L335 should ensure that whenever infrastructure files are modified, a full pass is triggered

Infra files include CSS, layout etc https://github.com/tlienart/Franklin.jl/blob/b014623720be8de65d46e21db9e5823ce8d28b92/src/manager/dir_utils.jl#L123-L127

I'll try myself and see if I can reproduce your issue

**Comment by fredrikekre** [comment]
> Hmm, I'll look into this, is this something that used to work for you and now doesn't?

Not sure. I mentioned this some months ago (on Slack?) but couldn't identify what was the culprit then.

**Comment by tlienart** [comment]
Could you try the following? 

* newsite in some temporary folder
* serve
* modify `_layout/head.html` e.g. adding something like `BLAH` after the `<body>` tag
* does the page reload? 

I just did the above and it works, so I'm tempted to think that you're bumping against another issue (but I'm not clear what it is)

**Comment by fredrikekre** [comment]
Yea, that indeed works.. I will try to investigate further.

**Comment by tlienart** [comment]
thanks a lot! yeah once we know for sure what seems to be happening I'll try to fix it asap

**Comment by fredrikekre** [comment]
I figured out the problem; I had those files in `ignore`.
