### ISSUE TITLE
Command failed: ssh-add -

### ISSUE THREAD

**Issue by cormullion** [tlienart/Franklin.jl#644]
Is this a Franklin-related issue or just some Github problem. I don't think I've changed anything since last month...

<img width="1121" alt="Screenshot 2020-10-09 at 14 25 22" src="https://user-images.githubusercontent.com/52289/95588468-5e842980-0a3b-11eb-9736-71a03261d9f4.png">

**Comment by tlienart** [comment]
it's some GitHub problem, let me see if there's an issue with the ssh-agent action

**Comment by tlienart** [comment]
yeah, can you try putting `@0.4` ? https://github.com/webfactory/ssh-agent/releases/tag/v0.4.1 (in the deploy.yml)

**Comment by tlienart** [comment]
yeah that's it.

@ all those who end up searching this in your `deploy.yml` replace

```
uses: webfactory/ssh-agent@v0.2.0
```

by 

```
uses: webfactory/ssh-agent@v0.4.1
```

**Comment by tlienart** [comment]
Urgh that's super annoying they want a PEM format now

**Comment by OpnSrcPro** [comment]
Thanks for solution, really appreciate
