### ISSUE TITLE
Tweaking sitemap options

### ISSUE THREAD

**Issue by schneiderfelipe** [tlienart/Franklin.jl#646]
Hi, how do I tweak the options in the sitemap generator? Specifically, I would like to remove some pages and change the priority of others (currently, all pages have a `0.5` priority value).

[This might have something to do with the planned `sitemap_exclude` option ([it's marked as TODO somewhere in the code](https://github.com/tlienart/Franklin.jl/blob/8dc118316caa76d62e656f153be9186931e21ca3/src/manager/sitemap_generator.jl#L12)).]

**Comment by tlienart** [comment]
I should get rid of that todo, have a look at https://github.com/tlienart/Franklin.jl/pull/631 for details on how to tweak things :) basically

* `sitemap_exclude`
* `sitemap_changefreq`
* `sitemap_lastmod`
* `sitemap_priority` 

can all be defined on a  page via `@def` 

(PS: this is not in the docs yet... if you fancy writing a paragraph explaining this in the docs after having given it a shot you'll  be a hero :medal: )
