### ISSUE TITLE
Robots.txt and others

### ISSUE THREAD

**Issue by remi-garcia** [tlienart/Franklin.jl#651]
It would be nice to have a straightforward way to generate:
- [ ] [robots.txt](https://www.robotstxt.org/)
- [ ] [security.txt](https://securitytxt.org/)
- [ ] [humans.txt](http://humanstxt.org/)
- [ ] etc.?

<details>
  <summary>Other stuff</summary>
Thanks for the package, I'm trying it right now and it is really comfortable to use.
</details>

**Comment by tlienart** [comment]
Hello Remi, this is a good idea and would be a pretty easy to add. Would you be willing to give it a shot? happy to give you a hand as to where to put stuff etc. 

Thanks!

**Comment by remi-garcia** [comment]
> Would you be willing to give it a shot?

Well, at worst I will probably learn a lot trying. I'll probably find time tomorrow and will look at how Hugo/Jekyll handle this.

> PS: I didn't have a look but do these files need to be generated or copy pasted from a template? in the second case it might be better to do that at FranklinTemplates.jl

My _a priori_ is that these files can be independent of the template (except for humans.txt 🤔). I'll look into this.
