### ISSUE TITLE
Add support for code blocks in 4 backticks

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#672]
At the moment we can do

single: 
``
a `b` c
``

double:

```
a ``b`` c
```

triple

````
a 
```
b
``` 
c
````

and then penta 

``````
a
`````
b
`````
c
``````

We should really add quadruple for good measure... this is an easy add in the parser

* https://github.com/tlienart/Franklin.jl/blob/4f7907ac68f46a3262829af987c73f18e697c0ec/src/parser/markdown/tokens.jl#L88-L93 (add a line for unnamed and a `is_language3` or something)
* here to define an OCP https://github.com/tlienart/Franklin.jl/blob/4f7907ac68f46a3262829af987c73f18e697c0ec/src/parser/markdown/tokens.jl#L143-L148
* here to add it (this should now be generated) https://github.com/tlienart/Franklin.jl/blob/4f7907ac68f46a3262829af987c73f18e697c0ec/src/parser/markdown/tokens.jl#L251

and that should be it because it will be taken like a code block lang.

**Comment by fredrikekre** [comment]
I also didn't manage to include a single `` ` `` in text without also including a space (`` `  ``)

**Comment by tlienart** [comment]
Ok for special characters you need to escape them with a backslash for instance ``\$ \` `` does that answer your issue?

**Comment by fredrikekre** [comment]
How?
````
`\``
`` \` ``
````
Both result in `` \` ``

**Comment by tlienart** [comment]
Right sorry for the confusion, so you can do

* in text `\` ` this will result to a single backtick in text (not in code)
* in code `` ` `` you need to use double back ticks and you must add space otherwise it's ambiguous

**Comment by fredrikekre** [comment]
Okay, but then there will be a literal space in the code-block, `e.g. <code><backtick><space></code>`. Given that a leading space is trimmed, a trailing one can be trimmed too?

**Comment by fredrikekre** [comment]
So e.g. 
```
r"``\s(.*?)\s``"
```

**Comment by tlienart** [comment]
Yes good call, I think I have a `strip` somewhere but clearly need to double check :-)

**Comment by tlienart** [comment]
Both these issues are now fixed on master (a patch release will be in soon)
