### ISSUE TITLE
Multiword tags result in URL with space

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/Franklin.jl#678]
Might not be too important, but spaces are replaced by `_` in generated `id` for example.

**Comment by fredrikekre** [comment]
On the other hand, might be strange if the tag and URL does not exacly match..

**Comment by tlienart** [comment]
So what you're saying is that if you have a tag `"foo bar"` it will be at a url `/tag/foo_bar` right? what would you prefer it to be?

**Comment by fredrikekre** [comment]
Currently it will be at url `/tag/foo bar`.

At first I thought it might be good to rewrite this same as is done for e.g. header id's, but not sure if it would be strange if the tag and url have a mismatch.

**Comment by tlienart** [comment]
hmm that's a (simple) bug, the intent is definitely to have the same story as with the headers; it's bad to have spaces in URLs. I think the mismatch thing is not too important because people usually go to tag pages by clicking on a tag link.

**Comment by fredrikekre** [comment]
Sounds good. Multi-word tags probably aren't that common anyway, and you can usually put a `-` in between if you really want them to match.

**Comment by tlienart** [comment]
just a heads up that this is now released and so you might want to check that you don't have a stray link
