### ISSUE TITLE
(demo) Copy code to clipboard

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#680]

**Comment by tlienart** [comment]
This is now done: https://franklinjl.org/demos/ ; all code blocks have a copy button; in general you might want to style it a bit, add a font-awesome icon or whatever but the base is there.

### Steps:

* get the `clipboard.min.js` from [their website](https://clipboardjs.com) and put it in `/libs/`
* load this in `layout/head.html` : https://github.com/tlienart/Franklin.jl/blob/0276b1afb054017ff7e81bc7d083021a867a4b92/demos/_layout/head.html#L9
* add some javascript in the `layout/foot.html` : https://github.com/tlienart/Franklin.jl/blob/0276b1afb054017ff7e81bc7d083021a867a4b92/demos/_layout/foot.html#L7 and https://github.com/tlienart/Franklin.jl/blob/master/demos/_layout/foot_clipboard.html (adapted from [this demo](http://tutsplus.github.io/clipboard/)) 
* adjust the CSS: https://github.com/tlienart/Franklin.jl/blob/0276b1afb054017ff7e81bc7d083021a867a4b92/demos/_css/extras.css#L37-L61

that's it

**Comment by Wikunia** [comment]
I'm getting an illegal constructor warning at:
```
var copyCode = new Clipboard('.copy-button', {
	target: function(trigger) {
	   return trigger.previousElementSibling;
    }
});
``` 
when I add it to my own site. I downloaded the zip from the clipboard website.

**Fixed:** I've just copied your clipboard.min.js and it works. They might have changed their structure in the master version. 
This might be happening to others so I decided to comment here nonetheless :smile:

**Comment by tlienart** [comment]
Yes so this is `clipboard` 1.4 something whereas the most recent one is `2.x` I haven't checked what's the difference + how to adapt stuff, if you do please let me know :)
