### ISSUE TITLE
creating a Date object from fd_mtime?

### ISSUE THREAD

**Issue by tomohiro-soejima** [tlienart/Franklin.jl#700]
Hi,

I would like to create a `Date` object from `fd_mtime` to be used in e.g. indicating last modified time on my blog post. However, adding this to the top of my markdown file does not work

```
@def last_modified=Date(fd_mtime)
```

becaue `fd_mtime` is not defined in this scope. What is the best way to define such `last_modified`.

In case there are other ways to handle this, here is an excerpt of the header that I want to make work.

```html
{{ispage /blog/julia/*}}
<div class="container blog-title">
	{{isdef title}}<h1>{{fill title}}</h1>{{end}}
  <h3>
  {{isdef published}} <span style="font-weight: lighter;"> posted: {{fill published}} 
  
  last modified: {{isdef last_modified}}{{fill last_modified}}{{end}}
  </span>
	|
	{{end}}
	{{isdef author}} <span style="font-weight: bold;">{{fill author}}</span> {{end}}
  <!-- assumption that only one of the two is defined -->
  {{isdef authors}} <span style="font-weight: bold;">{{fill authors}} </span> {{end}}
  </h3>
</div>
<br>
{{end}}
```

**Comment by tlienart** [comment]
you should _access_ `fd_mtime` via `locvar`:

```
@def last_modified=Date(locvar(:fd_mtime))
```

you can test this quickly in a session:

```
s = """
       @def last_modified=Date(locvar(:fd_mtime))
       {{last_modified}}
       """ |> fd2html
```

this will show `0001-01-01` because it's not executed in a file but you get the idea.

**Comment by tlienart** [comment]
By the way why did you not just do `{{fd_mtime}}` in your header? did you want to re-format the date?

**Comment by tlienart** [comment]
Other note: it looks like your ` {{isdef published}}` is not closed with an `{{end}}`?

**Comment by tomohiro-soejima** [comment]
thank you for your quick response!

I tried your code snippet, but it printed `0001-01-01`. Looks like `fd_mtime` is not correctly formatted for `Date` to parse. Is there a way around this?

I wanted to convert `fd_mtime` to `Date`, since `published` is a `Date` object, and I'd like to use the same format for `published` and `last_modified`. 

The `{{isdef published}}` is closed two lines after `</span>`. Sorry for the bad indentation!

**Comment by tomohiro-soejima** [comment]
this is what I want the end result to look like (with the correct last-modified date):

![image](https://user-images.githubusercontent.com/29153822/98229940-68e8f480-1f0f-11eb-8cfe-6a3522577937.png)

**Comment by tlienart** [comment]
Ah right you want `fd_mtime_raw`: consider the following, the first one is what you want, the second one is formatted. Sorry for my previous response.

```
Last modified: {{fd_mtime_raw}} or {{fd_mtime}}
```

**Comment by tomohiro-soejima** [comment]
That worked like a charm! Thanks.

![image](https://user-images.githubusercontent.com/29153822/98231052-c3cf1b80-1f10-11eb-8bac-bff25c3b221a.png)
