### ISSUE TITLE
how to detect a page has been modified

### ISSUE THREAD

**Issue by tomohiro-soejima** [tlienart/Franklin.jl#701]
I would like to change the appearance of my blog post based on whether the post has been modified or not, and I'd like Franklin to detect it automatically.

I've tried the following setup, which does not work. In the `/blog/post.md`, I include
```
@def published=Date(2020, 11, 5)
@def ismodified=locvar(:fd_mtime_raw)!=locvar(:published)
@def modified_date = locvar(:fd_mtime_raw) <!-- for debugging -->
```

in `head.html`
```
{{modified_date}} <!-- for debugging -->
{{if ismodified}} last modified: {{fd_mtime_raw}} {{end}}
```

This shows `0001-01-01 | last modified: 2020-11-05`. It is clearly not working.

As I understand it, this is because the value of the `fd_mtime_raw` variable is not calculated within `post.md`, and it just has the default value. Since I cannot insert `@def` statements inside `head.html`, it seems nontrivial to solve this problem. Is there a good way to do this?

Thank you for your help in advance. (I see that the most obvious solution to this is to set manually a flag `modified` myself. If that's the easiest method available, I'd gladly take that as an answer. Just wanted to know if there's some existing machinery I am failing to utilize.)

**Comment by tomohiro-soejima** [comment]
Full HTML block in case that is relevant

```html
{{ispage /blog/julia/*}}
<div class="container blog-title">
	{{isdef title}}<h1>{{fill title}}</h1>{{end}}
  <h3>
  {{isdef published}} <span style="font-weight: lighter;"> posted: {{fill published}}

  {{fill modified_date}}
  {{if modified}}| last modified:  {{fill fd_mtime_raw}}{{end}}
  </span>
	|
	{{end}}
	{{isdef author}} <span style="font-weight: bold;">{{fill author}}</span> {{end}}
  <!-- assumption that only one of the two is defined -->
  {{isdef authors}} <span style="font-weight: bold;">{{fill authors}} </span> {{end}}
  </h3>
  {{fill modified_date}}
  {{if modified}}| last modified:  {{fill fd_mtime_raw}}{{end}}
</div>
<br>
{{end}}
```

**Comment by tlienart** [comment]
> As I understand it, this is because the value of the `fd_mtime_raw` variable is not calculated within `post.md`, and it just has the default value. Since I cannot insert `@def` statements inside `head.html`, it seems nontrivial to solve this problem. Is there a good way to do this?

this is correct

The trick is to do this from inside a `hfun` (https://franklinjl.org/syntax/utils/) : if you put this in `utils.jl` (not tested but it should work)

```julia
function hfun_showmodified()
    modified = locvar(:fd_mtime_raw) != locvar(:published)
    modified && return "| last modified:  $(locvar(:fd_mtime_raw))"
    return ""
end
```

and in your header you call this with `{{showmodified}}` let me know if that works

**Comment by tomohiro-soejima** [comment]
It worked! Thanks!
