### ISSUE TITLE
Short filename for code block crashes

### ISSUE THREAD

**Issue by rikhuijzer** [tlienart/Franklin.jl#705]
It seems that the regex for the code block filename expects more than one symbol. For example,

    ```julia:n
    println("foo")
    ```

crashes with `type Nothing has no field captures`, which seems to indicate that a regex doesn't match on this pattern.

**Comment by tlienart** [comment]
🤔 thanks! I'll check this.

Side note, you may be interested in the shortcut introduced recently:

````
```!
println("foo")
```
````

which runs the cell and shows it.

**Comment by tlienart** [comment]
look at this monstrosity:

https://github.com/tlienart/Franklin.jl/blob/91f11a26e13ba67ea14a9e93510c36735a0f082d/src/regexes.jl#L67-L74

anyway the error is the `+` on line 71 which should be a `*` , I'll fix this and add a test
