### ISSUE TITLE
ENOENT error with delay function

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#717]
As reported by @pfitzseb 

```
ok, I can't get delayed hfuns to work: If I put
@delay function hfun_test()
  return "<div></div>"
end
into utils.jl and then {{test}} in e.g. _layout/head.html
of the directory generated by newsite("mySite", template="pure-sm"), I get the following error:

[stacktrace]
```

**Comment by tlienart** [comment]
Alright  so this  stems from 

https://github.com/tlienart/Franklin.jl/blob/9d9194a1873a43a5cc14fd70ba976cc9f36a7718/src/converter/html/html.jl#L50-L51

for some reason this gets stored as an additional DELAYED page if the delayed function is called in the templating.

An easy way out is to  just add a condition in https://github.com/tlienart/Franklin.jl/blob/6c85f17d2a3c7f18add072fd5dc88a20545c93db/src/manager/franklin.jl#L249-L253

Maybe better would be that this isn't added in the first place so here: https://github.com/tlienart/Franklin.jl/blob/c992a64fc2dc699120976b9c4d2fb6e71b5fcaae/src/utils/misc.jl#L264

the `union!` should only be done if `Franklin.FD_ENV[:SOURCE]` is a valid rpath.

**Comment by pfitzseb** [comment]
Thanks for the quick fix!
