### ISSUE TITLE
Allow Spaces in fun calls arguments

### ISSUE THREAD

**Issue by kellertuer** [tlienart/Franklin.jl#731]
First of all, since I am switching from liquify/ruby to a Julia based generator: This is much more fun to build!

To my current problem: I have a scenario where my variable I'd like to pass to an `hfun_` contains a space. How can I achieve this?

For context: I have a `names.yml` that stores metadata for people (a full name, a short name, maybe an orcid or a link or a GitHub username or somethings like that – I can surely show a demo when I am finished). And in the ruby variant I used the Full name as a key in the yaml. To be precise: The first known full name (in case someone marries / changes their name).

So my function `fun_name` takes 2 arguments: the person to display and the format to use, i.e. I would call

```
{{name "Ronny Bergmann" link_fullname_fngithub}}
```
in order to display my name linking to my stored url and showing a GitHub icon in `<sup>` linking to my GitHub (if such data is stored in above mentioned `.yaml` file). However currently this ends up as 3 parameters
```
["\"Ronny", "Bergmann\"", "link_fullname_fngithub"]
```
How can I “escape” a space in there? Currently I trick this by storing the data under `RonnyBergmann`, i.e. I omit spaces, but it's extra effort and not nice in style, especially because I use that in another setting as identifier, too.

**Comment by tlienart** [comment]
Ah nice, good idea

This should be easy to do; the parameter string is split in https://github.com/tlienart/Franklin.jl/blob/master/src/parser/html/blocks.jl on line 62 (sorry I'm on my phone) with the line `ps = split(...)`

The string could be manipulated with something more subtle than `split` or `ps` could be reduced afterwards with some post processing. 

If we simplify a bit and assume that this will only happen with `"..."` (and not triple quotes or macro string) then I think the post processing is maybe the easiest: if entry startswith `\"` find the next one that endswith `\"` and then reform a list of parameters having merged those.

**Comment by kellertuer** [comment]
I think just `"..."` should be enough, yes. I might take a look at this when my current idea (maybe complete homepage) is finished.

**Comment by kellertuer** [comment]
So, here https://regex101.com/r/dM3wM7/211 is a regex that I tried to come up with (and google) but sadly a code like
```
regexp = r"([^\s\"']+)|\"([^\"]*)\"|'([^']*)'|\"\"\"([^\"\"\"]*)\"\"\""
s = "123 abc \"secure this\" 'secure this\" \", too' or even this \"\"\"ABD\"\"\""

m = match(regexp,s)
m.captures
```
does not (yet) work, though I hope I took the right flavor of regex. Note that this would save single and double quotes as well as `"""..."""`. Currently I am not 100% sure why it does not do in Julia what the weblink above indicates it should do.

**Comment by kellertuer** [comment]
Oh, I wasn'T aware that this was even a point of the large list. Thanks for mentioning me for fixing this :)

**Comment by tlienart** [comment]
I just added it, it helps me keep track of what should be added to the docs eventually 😄 thanks for contributing!

**Comment by kellertuer** [comment]
Well, when I saw that it's not that difficult to add after all,...it really makes both my data handling (in `yaml`s) and my corresponding code much nicer. I will demonstrate once my page is finished.
