### ISSUE TITLE
Improve dependency & packages in deploy script

### ISSUE THREAD

**Issue by kellertuer** [tlienart/Franklin.jl#735]
Currently the deploy script does activate the local environment like
```
    - run: julia -e '
             using Pkg; Pkg.add(["NodeJS", "Franklin"]);
             using NodeJS; run(`$(npm_cmd()) install highlight.js`);
             using Franklin;
             Pkg.activate("."); Pkg.instantiate();
```
which by default no local environment existing (i.e. no `Project.toml` and ignoring a `Manifest.toml in the `.gitignore`). Maybe it would be nicer to add `Franklin` and `NodeJS` to the local environment and switch these lines to 
```
    - run: julia -e '
             using Pkg; Pkg.activate("."); Pkg.instantiate();
             using NodeJS; run(`$(npm_cmd()) install highlight.js`);
             using Franklin;
```
This would demonstrate to new users that `Project.toml` can be used and makes the script just slightly shorter.

**Comment by kellertuer** [comment]
Or to be precise the `Project.toml` would look like
```
[deps]
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
```
or one could even fix the version such that a user can be sure to use the Franklin version used also locally on their machine (in that environment that is).

**Comment by tlienart** [comment]
Cool yes, would you be willing to try this and open a PR for it? thanks!

**Comment by kellertuer** [comment]
Oh that is actually already my setup but sure I can make that into a PR; I am not 100% sure how to add the two new files to what Franklin.jl initializes. Will check that later.

**Comment by tlienart** [comment]
This would have to go in FranklinTemplates, here: https://github.com/tlienart/FranklinTemplates.jl/tree/master/src/templates/common

**Comment by tlienart** [comment]
thanks for the PR! pending release in FT 0.8.8
