### ISSUE TITLE
Using Lists stored in yaml:s (using Yaml.jl) as an extension?

### ISSUE THREAD

**Issue by kellertuer** [tlienart/Franklin.jl#737]
In my recent homepage build with Franklin, I store some data in yaml files, for example my talks
https://ronnybergmann.net/talks/
or meta-information for names (mainly urls and orcid:s), as well as the literature (until there is some BibTeX available). 

To Sketch the idea of my rearranged code imagine a yaml either a list
```
- f1: a
  a1 
  ...
- f1: b
...
```
(with the fields, f1, a1, f2, a2, u1, ... per entry)

Currently I have commands in mind like ``{{ol file.yaml "f1|a1, f1|a2|u2, f3"}}`` which would do an `<ol>` printing the `<span class="a1>f1</span><span class="a2"><a href="u2"></span>`per entry in the yaml within an `<li>` and so on...similarly for the `<ul>` of course as well as for an array and a `dl` with either two lists of such keys or something like that.

The main idea is to split content (yaml) from design (html/css) for certain list data, which is not as much text as blog posts.

I can surely make these functions a little nicer, but I am thinking, in which package this should be stored or whether it should be a separate plugin package?

**Comment by tlienart** [comment]
I think it's great and I would lean towards this being a plugin package, this is what I was hoping people would eventually do :-) and the advantage is that the dependencies come with the plugin, not by defaults. 

I'd be happy to help you with this though you've already essentially done it! 

Since this would be the first plugin, maybe we should also discuss the naming of such packages; what would you prefer?

**Comment by kellertuer** [comment]
Ah, well; I had hoped to ask for an Example to build my ideas on concerning the plugin idea.

My Proposal would be a `FranklinLIst.jl` – just for fun we could go for `FranklinLiszt.jl` – even for `Liszt.jl` (but it might be misleading). I would load Franklin and Yaml internally and then build the functions?
The general goal/workflow is then to load `Franklin.jl` and `FranklinLiszt.jl` additionally to use the yaml tricks.

But if you have a preference how to name things, we can also use a different scheme.

Concerning implementation, I would improve usability a little bit and work on above mentioned nicer ways to display yaml lists.

**Comment by tlienart** [comment]
`FranklinLiszt.jl` is fun :+1: 

So the way I see this work is as follows: 
* you create a module which imports Franklin and whatever else you might need (YAML etc)
* this module exports a few key "`hfun_*`" 
* users put `using FranklinLiszt` in their `utils.jl`

that should be it really; you can also check out https://github.com/tlienart/franklinutils.jl which has some of these ideas  

Adding tests is the bit that will require a  bit of care (e.g. making sure that environment variables are declared; there's some of that in  Franklin tests but I can help you with  that)

**Comment by kellertuer** [comment]
Ok, cool.As I said, I want to make the interface a little nicer and unified, but will work on that then the next days.

For the tests, I am not yet sure how they will work but I will steal some ideas from here I think.

**Comment by kellertuer** [comment]
So, here

https://github.com/kellertuer/FranklinLiszt.jl

is the first rearranged test, that is more generic than just a ``{{references ...}}`` command, namely reading yaml to ul, ol or dl lists, and I just realised a sublist feature.

Now I just have to check that they also work and illustrate them in some docs.
