### ISSUE TITLE
Weird git permissions deployment issue

### ISSUE THREAD

**Issue by fusion809** [tlienart/Franklin.jl#738]
Hi,

Oddly on my Franklin website I get this GitHub Actions error message ([full log](https://github.com/fusion809/fusion809.github.io/runs/1597767541)):

```bash
/usr/bin/git remote rm origin
/usr/bin/git remote add origin git@github.com:fusion809/fusion809.github.io
/usr/bin/git fetch --no-recurse-submodules
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
```

I have never gotten this error before, despite deploying my website for several months without a problem. 

And frankly, I don't get why. I have not changed any of my privacy settings, any of my account settings since the last successful build. DuckDuckGo searching this problem gives plenty of results of how to resolve this issue if it were just on my PC, but it's less clear how to fix this on GitHub Actions. 

Does this relate to #736? Do I have to rename my deployment branch to gh-pages? 

Thanks for your time

**Comment by tlienart** [comment]
Hello,

Sorry for the nuisance, this is known and very easy to fix. 

## the fix

Replace your deploy action with https://github.com/tlienart/FranklinTemplates.jl/blob/master/src/templates/common/.github/workflows/deploy.yml

that's basically it, nothing else to do (unless your website requires installing dependencies in which case you'd have to copy paste those from your old deploy to the new one)

## the reason

The old deploy script used an SSH GitHub action which uses something that GitHub deprecated. This caused quite a few people to stumble upon the issue you're seeing unfortunately. The new deploy above does not depend on this.

Also it doesn't require the FRANKLIN_* keys which you can (but don't have to) remove from your repo.

Hope this makes sense and solves your problem, if not please link to your repo and I'll try to fix it.

**Comment by fusion809** [comment]
Thanks, although for whatever reason GitHub Actions isn't trying to build & deploy my repo. https://github.com/fusion809/fusion809.github.io

**Comment by tlienart** [comment]
Alright, I'll have a look soon

**Comment by fusion809** [comment]
Seems to have resolved itself after I fixed the list of branches.
