### ISSUE TITLE
Alternative to `+++` for markdown definition syntax

### ISSUE THREAD

**Issue by kdheepak** [tlienart/Franklin.jl#740]
I'm curious why the syntax `+++` is chosen for code blocks evaluated for definitions?  

If I have the following in a Markdown file:

```
+++
title = "Title"
+++
```

it renders on GitHub / other markdown viewers as this:

+++
title = "Title"
+++

However, an alternative syntax could be to use code blocks instead, with addition tags to differentiate from normal code blocks:

````
```julia :franklin-meta
title = "Title"
```
````

This is rendered on GitHub / other markdown viewers as this:

```julia :franklin-meta
title = "Title"
```

This also has the advantage of showing correct syntax highlighting for the Julia code block. Thoughts?

**Comment by tlienart** [comment]
So this I probably won't do. There's a bunch of reasons but basically a code block with back ticks and what's in a ++ block are not evaluated with the same scope and not processed in the same way and, for the moment, I'd rather keep it that way.

However there's one thing that could be done and probably will soon: at the moment one cannot define new page variables inside a command but this could be toggled on easily. Then what you could do is define your own command `meta` with

````
\meta{
```julia
title = "the title"
```
}
````

where the command would parse it's content, strip off the back ticks and process the internal code. This is fairly close to what you suggest and would have the highlighting.

**Comment by kdheepak** [comment]
Sounds good! I thought it was worth suggesting since a lot of editors have built in markdown rendering or markdown syntax highlighting.
