### ISSUE TITLE
Allow use of `url` or `slug` page variable

### ISSUE THREAD

**Issue by kdheepak** [tlienart/Franklin.jl#741]
Other static site generators tend to support the use of a `url` or a `slug` variable, which is the route the final page is served at.

Currently, I wish to have a filename called `00-intro.md` and have the url be `introduction-to-julia` or `introduction-to-julia.html`, if inside `00-intro.md` there is a page variable that contains a valid url.

**Comment by kdheepak** [comment]
Minor improvement suggestion: it would be nice if the `slug` meta variable that is returned by `pagevar` always contained the final url. Currently, it contains the final url if it is set by the user or it is nothing / an empty variable, and the user has to check that and then parse the filename to figure out the final url.

**Comment by tlienart** [comment]
Yes that makes sense, I'll add another issue for that
