### ISSUE TITLE
Metadata from each markdown file

### ISSUE THREAD

**Issue by kdheepak** [tlienart/Franklin.jl#742]
When using `pandoc`, I use a yaml block to define the `title`, `category`, `date`, `tags` etc.

```
$ bat content/02-tasker.md | head -n 10
───────┬────────────────────────────────────────────────────────────────────────
       │ File: content/02-tasker.md
───────┼────────────────────────────────────────────────────────────────────────
   1   │ ---
   2   │ title: Tasker Projects
   3   │ category: blog
   4   │ date: 2014-12-12T19:00:00-06:00
   5   │ tags: Tasker, Android
   6   │ summary: A collection of Tasker projects I've worked on ...
   7   │ ---
```

`pandoc` also has a feature that lets you read this meta data externally. Let's say you can define a html file with the content `$meta-json$` (this is pandoc's templating syntax for the internal variable `meta-json`):

```
$ bat metajson.html
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: metajson.html
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ $meta-json$
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

Then, you can convert any markdown file with meta data in it to the template. For example, if we use the above file:

```
$ pandoc content/02-tasker.md --template=metajson.html
{"summary":"A collection of Tasker projects I’ve worked on …","category":"blog","date":"2014-12-12T19:00:00-06:00","title":"Tasker Projects","tags":"Tasker, Android"}
```

Pandoc returns a JSON string. I use this a lot in my current setup. For example, I can read the `date` of all the blogs to sort them in reverse order by time, I can filter what shows up in different sections of the home page based on `category` etc.

I know `Franklin.jl` has `locvar` to access some of these local variables. I'm wondering if it is possible to access them in a `hfun_function`. Currently, it appears people are [hardcoding generating the index](https://github.com/tk3369/www.ahsmart.com/blob/c4e3d57726e6296c871c96f302765b9d79e1d2ac/index.md) or using [a one off parsing script that is custom to their content](https://github.com/cormullion/cormullion.github.io/blob/7afde9776bda6c1c60a1cf8f8d3f10a5f605628a/utils.jl#L3-L34).

Thoughts?

**Comment by tlienart** [comment]
You can retrieve the dictionary of all page variables after a full pass, just use `serve(cleanup=false, single=true)` and look at `Franklin.ALL_PAGE_VARS` it's pretty much your Json for all pages as a dictionary.

Now to the second part of your question, you definitely don't have to hardcode, the second example is evaluated on the fly and gets updated automatically. See also how we do it for the JuliaLang.org website where there's a similar function to generate the grid of all blog posts.

**Comment by kdheepak** [comment]
Thanks for that information!

If I add the following to `hfun_blogposts` and call `{{blogposts}}` in `index.md`:

```
@show blog
pagename = "/$(first(splitext(b)))"
@show pagename
date = pagevar(pagename, :date)
title = pagevar(pagename, :title)
@show date
@show title
```

I get the following:

```
blog = "tasker-projects.md"
pagename = "/tasker-projects"
date = nothing
title = nothing
```

Even `keys(Franklin.ALL_PAGE_VARS)` only contains one element: `index`. Am I missing something? 

I've set up a public test repository by the way. Where I'm trying to build up blog up from scratch. Happy to take this discussion there if you think it doesn't belong here.

**Comment by tlienart** [comment]
Re the blog posts, could you have a look at this: https://github.com/tlienart/ft-so-simple/blob/master/utils.jl and try to adapt it to your needs? 

Yes I think for specific questions, from the repo helps because you can point me directly to what you tried, we can always open issues here later on for things that don't work well or things that should be added, thanks!

**Comment by kdheepak** [comment]
Thanks! I'm able to use this and it works!

```julia
function is_blogpost(post)
    rpath = joinpath(".", splitext(post)[1])
    category = pagevar(rpath, :category)
    category == "blog"
end

function get_all_blog_posts()
    first_year = globvar(:first_blog_year)
    this_year = year(Dates.today())
    all_posts = Dict()
    base = abspath(".")
    posts = filter!(p -> endswith(p, ".md"), readdir(base))
    filter!(f -> endswith(f, ".md"), posts)
    filter!(f -> !occursin("draft", f), posts)
    filter!(f -> is_blogpost(f), posts)
    all_posts = Dict()
    for (i, post) in enumerate(posts)
        posts[i] = rpath = joinpath(base, splitext(post)[1])
        date = pagevar(rpath, :date)
        title = pagevar(rpath, :title)
        url = pagevar(rpath, :slug)
        all_posts[post] = Dict(:title => title, :date => date, :url => url)
    end
    all_posts
end

function hfun_blogposts()
    all_posts = get_all_blog_posts()
    io = IOBuffer()
    write(io, "")
    write(io, "<div class=\"tocwrapper\">\n")
    for (k,v) in all_posts
        url = v[:url]
        title = v[:title]
        date = v[:date]
        k = """<p>
          <span class="toclink">
            <a href="$(url)">$(title)</a>
          </span>
          <span class="tocdate">
            $(monthabbr(date)), $(year(date))
          </span>
        </p>"""
        write(io, """$k\n""")
    end
    write(io, "</div>\n")
    write(io, "")
    return String(take!(io))
end
```

I'm not sure what I was doing wrong earlier.
