### ISSUE TITLE
warning: `Types.jl` and `highlight.js` missing

### ISSUE THREAD

**Issue by kunov** [tlienart/Franklin.jl#747]
It's nothing serious, but I'm getting the following warning while trying to `add Franklin`.

OS: Windows 10
julia v1.5.3 

```
 .... pkg> add Franklin
 Installing known registries into `C:\Users\ataik\.julia`
┌ Warning: could not download https://pkg.julialang.org/registries
└ @ Pkg.Types C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Types.jl:951
┌ Warning: could not download https://pkg.julialang.org/registries
└ @ Pkg.Types C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Types.jl:951
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
      Added registry `General` to `C:\Users\ataik\.julia\registries\General`

...
```

And, after typing `using Franklin` it's saying `highlight.js` is not found within my `.julia`

**Comment by tlienart** [comment]
The first bit is unrelated to Franklin; the bit about saying "highlight.js" not being found you can ignore, Franklin will just skip pre-rendering of your code locally. Note that if you use GitHub to deploy the website, it will be applied by the GitHub action even though you don't have it locally
