### ISSUE TITLE
Allow users to specify HTML files that they want to serve with the exact same path

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#759]
This popped up in a discussion with @ViralBShah, Google verification can require you to serve a file like `g1092341.html` at the root of your website so that it can be checked by it at `<yourdomain>/g1092341.html`. 

At the moment if you add a file `foo.html` in your folder, it will be copied over to `__site/foo/index.html` so that it becomes visible at `<yourdomain>/foo/`. 

I'm not exactly sure how the group of pages should be named, maybe `keep_path` so we'd have in `config.md`: 

```
@def keep_path = ["g1092341.html"]
```

**Comment by ViralBShah** [comment]
If possible, we should allow entire directories as well. So that if I have an existing set of html files to include in my website, I can add them "as is", and slowly migrate parts of the site to Franklin.
