### ISSUE TITLE
[bug] _out_path wrong when path has unicode

### ISSUE THREAD

**Issue by lucasvreis** [tlienart/Franklin.jl#768]
I had been puzzled for a while with the behavior of Franklin in my site, [`gat-ergódico`](https://github.com/lucasvreis/lucasvreis.github.io). I always had to keep two separate copies of folders `_layout`, `_css`, etc., one with the underscore and the other one without it. If I deleted one version of them, either Franklin would complain that it needs the ones with the underscores or my site would render in "raw" html and with no formatting.

So it turns out the culprit is the function `_out_path`. There is a `length` that should be changed to `lastindex`, so it outputs the right path when it contains Unicode.

**Comment by tlienart** [comment]
Thanks! this should now be fixed and the release is pending
