### ISSUE TITLE
Feature request: Code auto-labeling and/or warning for duplicates

### ISSUE THREAD

**Issue by cscherrer** [tlienart/Franklin.jl#771]
First, thanks for your work on this. Franklin is really great, especially for Julia blogging. 

I had a silly mistake that was confusing me for a while. I never know what to call the code chunks, so I was using `ex1`, `ex2`, etc. But then after some editing, I ended up with duplicates. So things were re-evaluating each time I saved, and it took me a while to figure out why.

I can see two things that could help with this:
- Some kind of auto-labeling. Most of the time you only refer to a result once, and it's immediately after the code. Maybe there could be a place-holder that lets you not worry about coming up with new names for most cases. Then you could do something like `\show{ans}`.
- A warning that lets you know if there are duplicate labels.

Either of this would help to simplify editing and make it less prone to this kind of error.

**Comment by tlienart** [comment]
Hello Chad, there is in fact something that might be close to what you want, could you give the following block a shot:

````
```!
x = randn(100)
println(sum(e->e^3, x))
```
````

😄 

so basically what that means is "run this, and show immediately what the output is" (and it does the auto-labelling etc in the background) this is effectively "notebook mode".

**Comment by tlienart** [comment]
I'm closing this as I think the suggestion above solves the issue (?). Please reopen otherwise.
