### ISSUE TITLE
old files from `__site` not deleted

### ISSUE THREAD

**Issue by lucaferranti** [tlienart/Franklin.jl#776]
Currently, it seems that if I delete a page from my source code,  the corresponding folder in `__site` is not deleted. Otherwise this would not matter, but if I build the search index with `lunr()` locally, then also old results in non-existing pages are indexed. Here's a clarifying example of what I mean:

1. the page `page1.md` contains the word `abcd`. I have called both `lunr` and `serve`, so `abcd` is indexed.
2. I delete `page1.md`, I call `serve()` again but the folder `page1` is not deleted from `__site`, hence when I call `lunr()` "abcd" is still associated to `page1`.
3. Locally, this just means that `page1` is still there. Online, if I search for `abcd` I get a link to `page1` even though that's not there, hence opening the link results in error 404.

Not sure whether this deserves to be its own issue or whether should be a comment to #754 , since fixing it would fix this problem (I think).

**Comment by tlienart** [comment]
this is locally right? you can always do `serve(clear=true)`; that will remove the `__site` folder entirely and re-build everything. 

We could also add logic in `__site` to check whether a file has a parent but as you can imagine, this is a bit tricky; and if done improperly might result in pretty annoying behaviour for the user. I might get to it one day but for now put it on the side as I thought it wasn't really worth the effort when you could just call `clear=true` (though of course this will require re-running all the code).

**Comment by tlienart** [comment]
@lucaferranti can this be closed?

**Comment by lucaferranti** [comment]
the only reason why I considered this an issue was the index building. Now that we have figured out how to integrate the lunr search in the workflow, I think this is not that relevant anymore. 

Maybe it would be good to just mention in the docs that if lunr is tested locally, then old pages are still visible but this does not happen when deployed?

**Comment by tlienart** [comment]
Makes sense, thanks!
