### ISSUE TITLE
Extra space before parsed latex argument

### ISSUE THREAD

**Issue by hpoonawala** [tlienart/Franklin.jl#783]
I want to automatically generate a link from a latex macro: 
in config.md : 
```
\newcommand{\coursepdflink}[1]{[pdf]( {{ fill notes_url }}/#1/) }
```
In a markdown file, if I include
```
\coursepdflink{04_Euclidean_Space.pdf}
```
the output in the html is 
```
<a href=" /assets/pdf/ 04_Euclidean_Space.pdf/">pdf</a>
```
The space between `pdf/` and `04` breaks the link.

When checking the html to include here, I noticed that this occurs in another macro that produced a working link: 
```
\newcommand{\coursenotes}[1]{ [Notes Ch #1 ]({{ fill full_notes_url }}) }
```
on input 
```
\coursenotes{1}
```
becomes 
```
<a href="/assets/pdf/00_RMC_Notes.pdf">Notes Ch  1 </a>
```
Here, of course, the extra space isn't an issue since it's in the displayed text. However, it seems like a space is always being added, which is fine in most cases, but not when generating a link. 
Either this property is a bug in parsing latex into markdown, or incorrect usage of that parsing by me. Help is appreciated either way.

PS - Thanks for all the great features in Franklin. I did a basic search for similar issues and couldn't find one, apologies if I missed a solution.

**Comment by tlienart** [comment]
Hello! yes: https://franklinjl.org/syntax/divs-commands/#whitespaces

Long story short, use a `!` in the definition of the command so compare: 

* `\newcommand{\foo}[1]{b:#1}` with
* `\newcommand{\foo}[1]{b:!#1}`

**Comment by hpoonawala** [comment]
Ah, an RTFM fail. I appreciate your response, thanks again.

**Comment by tlienart** [comment]
No worries 😅
