### ISSUE TITLE
Serving .toml files

### ISSUE THREAD

**Issue by c42f** [tlienart/Franklin.jl#800]
I'd like to serve Project.toml and Manifest.toml files from a Franklin sub-page, as I'm building several tutorials with varying package environments from the same site.

However it seems that franklin magically disregards toml files, perhaps here:

https://github.com/tlienart/Franklin.jl/blob/7777f4241e16a9a5c5e6ad006251a4729ccec593/src/manager/dir_utils.jl#L147

Is there any way to get project and manifest toml files copied over to the generated site?

**Comment by tlienart** [comment]
Hello Chris, 

Hmm yeah that line is probably overly aggressive. I've just relaxed it on the master branch, could you try and let me know if it works for you?

**Comment by c42f** [comment]
This seems to work nicely, thanks!
