### ISSUE TITLE
highlight.js deprecation warning in HTML

### ISSUE THREAD

**Issue by keorn** [tlienart/Franklin.jl#803]
I noticed that recently pages built with template CI process display a deprecation notice above code blocks:

- https://julialang.org/blog/2020/08/invalidations/#an_example_compilation_for_containers_with_unknown_element_types
- https://juliasmoothoptimizers.github.io/#publications_talks_and_other_references

"Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated. Deprecated as of 10.7.0. Please use highlight(code, options) instead. https://github.com/highlightjs/highlight.js/issues/2277"

**Comment by tlienart** [comment]
For anyone stumbling upon this, for now just set `prerender=false` in the `optimize` call of the deploy script so 

```
optimize(prerender=false)
```

**Comment by RoyiAvital** [comment]
Any reason not to move forward to the new version?

**Comment by abelsiqueira** [comment]
If I understood correctly, when `optimize(prerender=true)` the new version is used because it's downloaded by `node` on deploy. The issue seems to be that somewhere in the code the deprecation log is captured. The `optimize(prerender=false)` uses the already downloaded `highlight.js`, which is the old version without the deprecation.

I tried to fix it, but it's out of my expertise, so eventually, I got lost. If you have any tips on where to look and/or how to verify it, I can try again.

**Comment by RoyiAvital** [comment]
I meant upgrading to the latest version of `Highlight.js`.

**Comment by tlienart** [comment]
Both will happen, I'm just under quite a lot of pressure at work at the moment so it's delaying updates here :) 

I also want to be careful about not breaking things after a hurried RSS update which caused breakage 😣 (and which I still have to fix).

**Comment by tlienart** [comment]
@abelsiqueira sorry for not replying to your message, the line to change is https://github.com/tlienart/Franklin.jl/blob/1fd22cca60f18f68efcf2e593503e9b479b9692d/src/converter/html/prerender.jl#L71 

A PR with this would be very welcome, you'd have to test this separately though (i.e. run the `optimize` locally, and check that the appropriate HTML is generated + a screenshot of the result)

I think that should be all that is required.

**Comment by abelsiqueira** [comment]
Thanks for the guidance @tlienart. I made the modifications in #804 and I also did https://github.com/tlienart/FranklinTemplates.jl/pull/123. I haven't tested the templates change, though.
