### ISSUE TITLE
Google News stopped fetching articles from feed.xml.

### ISSUE THREAD

**Issue by pakzy** [tlienart/Franklin.jl#805]

**Comment by tlienart** [comment]
Yes, this is ongoing work and on me for messing this up.

In the meantime you could pin Franklin to 0.10.30 in the deploy script if you wanted an immediate fix, otherwise this will hopefully be fixed and released within the next few days.

**Comment by tlienart** [comment]
@pakzy there is now a fix + a way to use it: https://github.com/tlienart/Franklin.jl/pull/799 would you mind trying it out? (it's already successfully used by JuliaGPU). 

This will be released in a week or so (I just need to add a bunch of tests).

**Comment by tlienart** [comment]
This is now fully released. For those stumbling upon this, from 0.10.35 problems should be fixed and you shouldn't have to do anything special.
