### ISSUE TITLE
Sidenotes

### ISSUE THREAD

**Issue by daeaedalus** [tlienart/Franklin.jl#811]
[Tufte CSS style](https://edwardtufte.github.io/tufte-css/) uses sidenotes. It would be nice if we could pick between footnotes and sidenotes.

**Comment by tlienart** [comment]
Hello @daeaedalus this is more an issue with https://github.com/tlienart/franklintemplates.jl , there's already https://github.com/tlienart/FranklinTemplates.jl/issues/35 that discusses how you could approach some of it. If you experiment with it and have issues, let me know on Slack or there and we can try figuring it out!

**Comment by daeaedalus** [comment]
Thanks @tlienart - I'll dig around in there.
