### ISSUE TITLE
favicon with transparent regions not rendered on local serve

### ISSUE THREAD

**Issue by miguelraz** [tlienart/Franklin.jl#814]
I have a favicon with a transparent background - it gets rendered appropriately in the website at [my github site](https://miguelraz.github.io) but not on localhost:80000

Here's a picture
https://imgur.com/d5DvzQf.png

**Comment by tlienart** [comment]
This isn't related to Franklin but likely related to caching on your Browser possibly of a previous version of the favicon. 

Could you try (1) opening the local one in another browser or (2) opening the local one in a incognito window on Firefox and check? 

I'll close this for now as I'm pretty sure it's unrelated to Franklin (the fact that it works fine online shows this).
