### ISSUE TITLE
Extension suggestions

### ISSUE THREAD

**Issue by hustf** [tlienart/Franklin.jl#827]
I ended up with writing some new utils functions for [DEQ](https://hustf.github.io/DEQ/), and I believe that is fairly common. See the list below, which just reflects the current state and would need some renaming. Some of them may perhaps be worth adding to Franklin.jl.

The learning curve for Franklin users and developers gets steeper every time functionality is added. If the default interface is feature-incomplete, users can easily copy their own libraries to the next project and perhaps develop a personal style. But writing those functions is hard, too. So there's a balance.

Some older Julia packages are already well into feature-bloat, while Franklin is still starting and can go any path. In [Unfinished Spotify.jl](https://github.com/kwehmeyer/Spotify.jl), we have an experiment in making some forty user facing functions easily available. For exploration, we use the REPL menus to load sub-modules. 

But anyway, here's a dump list for what I needed for that first blog post: 
```
"""
Use the indent style after math, apply a css style including text "where"
"""
function lx_indentmath(com, _)


"""
Span element with brackets and color for units
"""
function lx_unit(com, _)

"""
Span element with brackets and color for units
"""
lx_codeunit(com, _)

"""
accordion(fullversion)
The arguments are received packed in a vector of strings.
Call from parsedown with \accordion{
  What is returned from here is  \\style{color:#d94}{reprocessed} by Franklin.
  }
...note that you would use one backslash in nested calls, like normal.
"""
function lx_accordion(com, _)


"""
Inline julia expression in string form -> numbered katex equation.
Uses Latexify plus glue code for units.
"""
function lx_katexeq(com, _)


"""
Julia expression in string form -> inline katex, otherwise as above.
"""
function lx_katexi(com, _)

"""
Like /input{julia}{source}, but drop {julia} and add source info for copy button hover.
"""
function lx_inputJ(com, _)
```

**Comment by tlienart** [comment]
The way I initially thought things would go is that devs/users would define packages a bit like LaTeX `.sty` files. Each of these packages would define a bunch of useful commands (either hfuns or lxfuns) within some contexts. All the users would then have to do is put

```
using TheStylePackage
```

in their `utils.jl`. 

I prefer this to baking them into Franklin (apart for truly generic tools which would be used everywhere) as it makes the development/testing etc easier and faster. 

What do you think?

**Comment by hustf** [comment]
Absolutely a good approach. The smaller Franklin is, the more flexible it will be. In my opinion, any choice which leads to easy long time maintenance is likely to be a good choice. Think of potential users as semi-competent in Julia, latex, html, css, git and javascript. That cuts down on the workload for the maintainer, and there are plenty of commercial options anyway.

**Comment by tlienart** [comment]
Cool, I'll close this issue then, if you start one such package, feel free to ping me from there or add me as a collaborator if you want a hand :)
