### ISSUE TITLE
Adding Styling with just Markdown

### ISSUE THREAD

**Issue by logankilpatrick** [tlienart/Franklin.jl#837]
I know I can use the syntax to embed html into the markdown files, but is there a way to style a section without doing that and just using raw markdown?

**Comment by tlienart** [comment]
well you can wrap a section into a `@@something ... @@` and that will put it into a div of its own that you can style at will so for instance:


```
This is some **markdown** text followed by

@@yellow-box,text-large
some more text in a yellow box with large font
@@
```

you'd then put in the relevant css file something like

```
.yellow-box {
  background-color: yellow; /* will look horrible */
}
.text-large {
  font-size: 25px;
}
```
