### ISSUE TITLE
Docs for @@tight-list

### ISSUE THREAD

**Issue by logankilpatrick** [tlienart/Franklin.jl#838]
Is there somewhere where `@@tight-list` is documented? I don't see it in this repo or the like. I am trying to do a nested list and the formatting is messed up right now using a single `@@tight-list`.

**Comment by tlienart** [comment]
Hello Logan, the `@@tight-list` just defines a `<div class="tight-list"> ... </div>` around some content (typically a list). Usually the corresponding css is the following:

```css
.tight-list li p {
  margin: 0;
}
```

the explanation is that Base.Markdown to html conversion adds a bunch of `<p>` around list items, these typically add line spacing and, as a result, you get a larger list than what you want. Setting `margin: 0` makes those elements effectively invisible. 

Now beyond this, if your *nested* list looks messed up, this might be some other issue. One thing to keep in mind is that list items **must** be on the same line so you must have something like this:

```
* this is a very long list item you cannot skip a line it it, no no
* this is another item
```

but not like this

```
* this is a very long list item but I'm going
to break it into pieces 
* this is another item
```

I'm just guessing though, so if the pointers above don't help, please point me to what you tried and I'll have a look

**Comment by logankilpatrick** [comment]
This is what the site looks like: https://julialang.org/contribute/ and here is the code: https://github.com/JuliaLang/www.julialang.org/blob/main/contribute/index.md#chose-your-path I had it without the nested tight lists before

**Comment by logankilpatrick** [comment]
Bumping this @tlienart
