### ISSUE TITLE
Issues with sidebar

### ISSUE THREAD

**Issue by alonsoC1s** [tlienart/Franklin.jl#843]
Hello! First of all thank you very much for all the great work.

I have been trying to add some pages and folders to the sidebar (or topbar depending on the theme) but I havent found the pertinent configuration files. The only way I found was modifying the html files directly. I don't know if its something that can be enhanced in Franklin itself. If it an actual feature, I propose adding more references to it on the documentation.

**Comment by tlienart** [comment]
Hello!

That's right, you have to write the sidebar/toolbar yourself, the thing is that is ambiguous what one might want to put there but I agree that there could be something where you provide a list of `title => path` pairs and each would be on the side bar. This is more an issue for FranklinTemplates than for Franklin though.

In the meantime a good way to do it on your side now would be to write a Julia function that reads a list of paths with label (eg given in config) and generates a list of item that can then be inserted. So you'd do something like

```julia
function hfun_sidebar()
    for (label, rpath) in globvar("sidebar_links")
        ...
    end
    return the_html
end
```

and insert `{{sidebar}}` at the relevant place in `head.html` or whatever

Let me know if that makes sense, I could write a demo for this that some users might find useful anyway

**Comment by alonsoC1s** [comment]
Thanks! That might be enough. Are there any plans to add this to the documentation?

**Comment by tlienart** [comment]
I'm not sure where that would go in the docs but we could write a demo for it which would go in franklinjl.org/demos/

If you're keen to get this started with even a wholly incomplete PR, I'll gladly help you with it

**Comment by alonsoC1s** [comment]
I was thinking maybe in the section that deals with page structure or maybe even on the custom processing functions. If that works for you I can start a PR

**Comment by tlienart** [comment]
yes please, PRs always welcome :)
