### ISSUE TITLE
GitHub deployment fails after adding package Weave.jl

### ISSUE THREAD

**Issue by EvoArt** [tlienart/Franklin.jl#848]
Sorry to keep moving this issue around. But I  deleted my previous GitHub pages repository to start afresh. Everything works fine (newsite(), serve(), git push) to get the basic site template up and running properly. But as soon as I ```] add Weave``` the deployment fails. I tried ``` ] rm Weave ``` But it still fails. 

I noticed in your examples basic user site and basic project site, there are no associated project.toml files. Am I doing the right thing by using the folder that's linked to the GitHub master branch as my Julia environment?

**Comment by tlienart** [comment]
Please have a look at [this comment](https://github.com/tlienart/Franklin.jl/issues/372#issuecomment-882408280) this is a fully reproducible example (you can just fork the repo and copy paste the demos folder). I hope this helps.
