### ISSUE TITLE
Custom processing of code block results

### ISSUE THREAD

**Issue by jkrumbiegel** [tlienart/Franklin.jl#851]
In Makie, example blocks usually return a `Figure`, which when `display`ed creates a png or svg (or a native window) depending on activated backend and coding environment.

It is cumbersome to save each plot manually, with a specified name, and then include it in the markdown, because there are so many plots we have to do this with. In Documenter, we would just end an `@example` block with those objects and the plots would be inserted into the document there.

What I've done so far is create an `env_` function to wrap code blocks with that are supposed to result in plots: https://github.com/jkrumbiegel/Makie.jl/blob/jk/franklin-docs/docs_franklin/site/utils.jl#L45-L73

This function splices in a call `save(name, current_figure())` at the end. The problem is that this only works if there is a `Figure` created in the block, but sometimes Makie just creates `Scene`s instead. It's difficult to come up with code that could be spliced in which can handle saving a created plot without edge cases. What would be really simple instead, is if there was some kind of action one could hook into that is executed with the return value of a code block. Currently, the return value can only be accessed in its textual form, but that's useless for plots.

So what I'm thinking of is a custom Franklin block, where I can decide what happens given specific output types. Save figures or scenes, splice them back into the markdown, etc.

**Comment by jkrumbiegel** [comment]
Oh after thinking about it some more, maybe I can solve it by wrapping the code block in a hidden `begin` block. This will allow me to intercept the resulting value without having to deal with the syntax in there.

**Comment by tlienart** [comment]
So if I understand correctly what would be helpful to you is if you could recuperate the result of a code block as a Julia object and do something with it later.

Actually you can do that by going through the page context, this might seem clunky (it is, I could make this more streamlined in the future) but it should work and be easy to hide in a function.

What you'd do in the code is add a hidden line:

```
Franklin.set_var!(Franklin.LOCAL_VARS, :var_name, value)
```

(I'm typing on my phone so there may be typos), this adds a variable to the local context of the page. It can then be accessed from a utils function via

```
locvar(:var_name)
```

Using this and generating variable names depending on the name of the code block should work. Note that the functions in utils run in a different scope so you'll need to make sure any packages you want to use on that passed result is also loaded in the `utils.jl` file.

I hope this makes some sense, if not I'll try to show this in a demo tomorrow

**Comment by jkrumbiegel** [comment]
That sounds interesting, I'll keep that in mind. Currently, I'm rolling with the `begin` block solution, which kind of wraps what I wanted inside that codeblock. It's not necessarily pretty, but works ok :) The pagevar solution also doesn't look so pretty either ;)

**Comment by tlienart** [comment]
good if you have something working, I'll be glad to have a look to see why you used this and how you did it
