### ISSUE TITLE
Can't style code input and output together with \show

### ISSUE THREAD

**Issue by jkrumbiegel** [tlienart/Franklin.jl#856]
The code and the output are wrapped in `<pre>` but there is no way to apply css differently if an input block and an output block follow each other. Maybe it would be good to give and input and an output class to the `<pre>` tags?

**Comment by tlienart** [comment]
hmm typically the code block has a language and the output block is `plaintext` for instance in the demos there's something that leads to

```html
<pre><code class="language-julia">for i in 1:5
  println&#40;&quot;*&quot;^i&#41;
end</code></pre><pre><code class="plaintext">*
**
***
****
*****
</code></pre>
```

so the styling could be done via `.language-julia` and `.plaintext`. 

Is that insufficient? If so we could have what you're suggesting by 

* adding a kwarg to `html_code` (https://github.com/tlienart/Franklin.jl/blob/e99dedbf97cc831aabeb56816fdb9951e053b07f/src/utils/html.jl#L61-L72) 
* passing that kwarg to this line:  https://github.com/tlienart/Franklin.jl/blob/e99dedbf97cc831aabeb56816fdb9951e053b07f/src/converter/latex/io.jl#L106

**Comment by jkrumbiegel** [comment]
using the code language feels a bit brittle to me, if I have another language that I don't have styling for, this might break. it's probably cleaner to mark the blocks specifically.

**Comment by tlienart** [comment]
alright done in #858. Note that I added the class to `code` and not to `pre` to not risk breaking existing CSS sheets. 

Note that so far other languages are not supported but it's a fair point anyway because they will be in the future.

So now you'd style `code` and `code.code-output`. We could add also a specific class for the code "input" but it seems redundant to me.

**Comment by jkrumbiegel** [comment]
Thanks, but is it possible in css to read out if two code blocks in two different pre tags with different classes follow each other? Well I guess output will usually not come alone, but I wanted to attach code and output visually if they come right behind each other. Not sure if that's possible with this solution

**Comment by jkrumbiegel** [comment]
For example, remove the rounded corners of the code cell at the joint
