### ISSUE TITLE
gitlab deployment needs main instead of master

### ISSUE THREAD

**Issue by brittAnderson** [tlienart/Franklin.jl#861]
I just created a test repo on gitlab and the newsite function from Franklin and failed to get automatic ci. I think this is because `.gitlab-ci.yml` defaults to 
    
    only:
      -  master

when it should be "main". After I made that changed automatic ci happened.

**Comment by tlienart** [comment]
Thanks @brittAnderson for the report, I'll change this in the defaults of FranklinTemplates

kr

**Comment by tlienart** [comment]
done https://github.com/tlienart/FranklinTemplates.jl/commit/ffdfd4b8ce77c418cf26d6dfc17175927d33dadd
