### ISSUE TITLE
Table rendering differs locally and deployed

### ISSUE THREAD

**Issue by vchuravy** [tlienart/Franklin.jl#862]
On https://vchuravy.dev/notes/2021/08/bpftrace/ I am embedding a table source code https://github.com/vchuravy/vchuravy.github.io/blob/main/notes/2021/08/bpftrace.md 

Locally this renders just fine. 

```
Updating `~/work/vchuravy.github.io/vchuravy.github.io/Project.toml`
  [713c75ef] + Franklin v0.10.46
  [2bd173c7] + NodeJS v1.3.0
```

**Comment by tlienart** [comment]
In your deploy script can you try using

```
optimize(minify=false)
```

? that should fix it

**Comment by vchuravy** [comment]
Hmm... That wasn't enough https://github.com/vchuravy/vchuravy.github.io/runs/3279617359

**Comment by tlienart** [comment]
will have a look at your repo, give me 30 mins

**Comment by tlienart** [comment]
there is something odd about all this, maybe to do with how quickly things propagate to your custom domains, not sure.

In any case this seems to work: https://tlienart.github.io/test_vchuravy/notes/2021/08/bpftrace/ 

I've not done much else than 

- removing the favicon (unrelated but the cause of an ugly red question mark)
- simplified the deploy script (probably also unrelated)
- some testing
- there's a specific prepath bc it's a project site which you'd have to remove in `config.md` if you copy-pasted my stuff

**Comment by vchuravy** [comment]
Found the difference. My deploy scripty was using Julia 1.5 and yours is 1.6 https://github.com/vchuravy/vchuravy.github.io/commit/e23cfe9e47aca71f0b3526d745ca0b0ad241484f
