### ISSUE TITLE
Beta testers for Xranklin

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#863]
Xranklin is an ongoing project that will be the next big release of Franklin and eventually it's `1.0` version. Among the goodies

* using CommonMark.jl
* strict(er) checking of validity of generated HTML (namely fewer instances of unbalanced `<p>`)
* systematic caching to make everything faster (especially for big websites with lots of code)
* much more sophisticated dependency management for page variables (i.e. when a page depends on a variable from another page and that other page gets updated, the initial page should be updated as well etc, this is quite tricky)
* latex generation (so every page can be made into a PDF with proper maths etc)
* MIME processing for better handling of code cell results
* better error handling 
* a large number of small things to make the code faster and cleaner

As of August 2021, I'm about 75% there (all of the above is already in place, I'm just putting everything together and adding back features until it matches Franklin). I'm tentatively looking for patient users who are interested in beta-testing this once we get around 90% there. What this would entail is:

- you try a specific branch of Franklin locally, if errors are encountered, you report them or adjust the code following a short migration guide (there should be few things that need adjustment though unless you rely on internals)
- (later) you try to deploy the site using that branch, report errors

once there's confidence that Xranklin can reproduce Franklin, it becomes Franklin v0.11, we release it, do more testing, and a few months later make it 1.0.

**List of potential beta testers**

if you'd like to contribute and would like to beta-test, please ping me on slack and I'll add you to the list here, thank you!

* (confirmed) storopoli with the https://github.com/storopoli/Bayesian-Julia site
* (tbc) jkrumbiegel with the https://makie.juliaplots.org/dev/
* (tbc) lazarusa with the https://lazarusa.github.io/BeautifulMakie/
* (tbc) kellertuer with https://ronnybergmann.net etc
* (tbc) fredrikekre with https://fredrikekre.se
* (tbc) wikunia with https://opensourc.es
* ...

**Comment by jeremiahpslewis** [comment]
@tlienart Are you still planning on going from Markdown.jl -> CommonMark.jl? (Think this is an awesome change ;) ) Have you seen this project / might this be relevant as well? (It builds on CommonMark.jl, but enables further HTML objects to be composed) https://github.com/JuliaPluto/HypertextLiteral.jl

**Comment by tlienart** [comment]
Thanks @jeremiahpslewis , 

Re using CommonMark.jl: this was the _initial_ plan until it turned out that adapting to CommonMark would limit some of Franklin's extensions. The next version (which you can check out at Xranklin.jl) has its own parser. So the move from Markdown.jl has definitely been applied. Also all tests from CommonMark.jl are passing with the new parser apart the stuff that we're consciously not supporting (specifically one: indented code blocks will never be allowed)

Re HypertextLiteral, I'm aware of it but I don't think it's relevant for Franklin's core. However, like every Julia package, it can be used by the user within Franklin. 

In fact this last comment holds for CommonMark as well, users will be able to choose to bypass Franklin's parser and use another one like CommonMark though, of course, this will come at the expense of using Franklin's extensions.
