### ISSUE TITLE
Franklin.jl + GH Pages deployment fail : `ERROR: TypeError: in typeassert, expected VersionNumber, got a value of type Pkg.Types.VersionSpec`

### ISSUE THREAD

**Issue by SimonCoste** [tlienart/Franklin.jl#868]
Hello, 
I am using Franklin for [my personnal website](https://github.com/SimonCoste/SimonCoste.github.io), it is hosted through GitHub pages. 
I recently pushed some changes, but [the deployment failed](https://github.com/SimonCoste/SimonCoste.github.io/runs/3379823589?check_suite_focus=true). Here is the output : 

> Run julia -e ' using Pkg; Pkg.activate("."); Pkg.instantiate(); using NodeJS; run(`$(npm_cmd()) install highlight.js`); using Franklin; optimize()'
>  Activating environment at `~/work/SimonCoste.github.io/SimonCoste.github.io/Project.toml`
>  Installing known registries into `~/.julia`
> 
>                                                                            0.2%
> ######################################                                    53.2%
> ######################################################################## 100.0%
>       Added registry `General` to `~/.julia/registries/General`
> ERROR: TypeError: in typeassert, expected VersionNumber, got a value of type Pkg.Types.VersionSpec
> Stacktrace:
>  [1] load_urls(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:510
>  [2] #download_source#54 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:686 [inlined]
>  [3] download_source at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:685 [inlined]
>  [4] instantiate(::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Pkg.BinaryPlatforms.Linux, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:875
>  [5] instantiate(::Pkg.Types.Context) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:795
>  [6] #instantiate#169 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:791 [inlined]
>  [7] instantiate() at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:791
>  [8] top-level scope at none:1
> Error: Process completed with exit code 1.

I think this might be linked with the fact that I recently upgraded my Julia version on my computer, from <1.5 to 1.6.2. 
How can I overcome this ?

**Comment by fredrikekre** [comment]
> I think this might be linked with the fact that I recently upgraded my Julia version on my computer, from <1.5 to 1.6.2.

Probably, and now you try to run a 1.6 manifest with 1.5: https://github.com/SimonCoste/SimonCoste.github.io/blob/c3ddc644f134f1833cbf9b56abc898bb143bf492/.github/workflows/Deploy.yml#L26

**Comment by SimonCoste** [comment]
Thanks for your answer, Fredrik. I manually updated the deploy.yml file and the deployment worked. 
Do you know if there is a way to automate this ?
