### ISSUE TITLE
GH Pages : Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]

### ISSUE THREAD

**Issue by SimonCoste** [tlienart/Franklin.jl#869]
Hello, on my website I use GLMakie.jl, the OpenGL backend for Makie. I use it in a script to draw a picture. 
````
This is my file.md with a script :
```
using GLMakie
# code to draw stuff using GLMakie
save(joinpath(@OUTPUT, "raw.png"), fig)
```
\fig{raw}
````
Unfortunately, when I deploy to GitHub pages, I get no picture : the output of the script (in [`script.out`](https://github.com/SimonCoste/SimonCoste.github.io/blob/gh-pages/assets/posts/random_eigenfunctions/code/output/raw.out)) says
> Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to /home/runner/.julia/compiled/v1.6/GLMakie/jl_9ClA9M.

Everything works fine locally, so I guess it has to do with the deployment itself ?

**Comment by tlienart** [comment]
Sorry I'm away from my computer this weekend, is this the same as #868? Did fixing the Julia version fix the issue?

**Comment by SimonCoste** [comment]
Hi, Thibaut.
No, this is a separate subsequent issue that happened after #868 . Fixing the Julia version allowed me to deploy normally, but now I have this "failed to precompile GLMakie" error described above.

**Comment by tlienart** [comment]
This error message is unrelated to Franklin as far as I know, it could have been due to the Julia version but it seems that it's an issue with setting up GLMakie in the first place for GA; you should check with someone from that repo how it's supposed to be set up properly on GHA, eg whether you need to install additional non Julia libs, this might be the case as the Linux version run by GHA does not come with everything you might expect

**Comment by tlienart** [comment]
could you try adding this line to your deploy? https://github.com/JuliaPlots/Makie.jl/blob/a3298c08f98e41a43920bb61739419235df943b5/.github/workflows/Docs.yml#L26

**Comment by SimonCoste** [comment]
Hi Thibaut, adding  
```yml
- name: Install binary dependencies
  run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-de
```
in the deploy did not work. 

Apparently, GH Actions have an [OpenGL support](https://github.com/openrndr/setup-opengl), but it didn't work either - see [this issue](https://github.com/openrndr/setup-opengl/issues/5) which was also opened in relation with GLMakie.

**Comment by tlienart** [comment]
Ok great, let me know if there's something that can be done on the Franklin side, in the meantime I'll close this issue
