### ISSUE TITLE
Adding Search functionality

### ISSUE THREAD

**Issue by logankilpatrick** [tlienart/Franklin.jl#871]
Following this page: https://franklinjl.org/extras/lunr/index.html after I NPM install, do I need to include the Node modules file in the repo? How will the deployed version work?

**Comment by logankilpatrick** [comment]
I think I got past the initial question, but I still get: 
```
julia> using Franklin

julia> lunr()
→ Building the Lunr index...       Could not find folder:  ../../__site
/Users/logankilpatrick/Desktop/18S191/website/_libs/lunr/build_index.js:89
    for (var i = 0; i < files.length; i++) {
                              ^

TypeError: Cannot read property 'length' of undefined
    at main (/Users/logankilpatrick/Desktop/18S191/website/_libs/lunr/build_index.js:89:31)
    at Object.<anonymous> (/Users/logankilpatrick/Desktop/18S191/website/_libs/lunr/build_index.js:103:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
┌ Warning: There was an error building the Lunr index.
└ @ Franklin ~/.julia/packages/Franklin/BDfoY/src/manager/extras.jl:33

```

**Comment by logankilpatrick** [comment]
Had to switch it to: `const HTML_FOLDER  = "../../../website/__site";`

**Comment by tlienart** [comment]
Did you generate the site locally before running lunr? so the workflow should be

1. generate the site (`serve` or `serve(single=true)` etc)
2. call `lunr()`

then you can have something like this in your deploy script that does it automatically:

```
serve(single=true, cleanup=false)
lunr()
optimize(minify=false, prerender=false)
```

(e.g. https://github.com/JuliaPlots/Makie.jl/blob/4df004ceb791716fdaf4410b39b1c0bfcc66c148/docs/makedocs.jl#L31-L33 and what I use on the docs website here: https://github.com/tlienart/Franklin.jl/blob/8491936ed7d3a3e1d58e0affcbc1ff25a796bee7/.github/workflows/deploy.yml#L28-L38)

I hope this helps

**Comment by tlienart** [comment]
I think we fixed this so closing here.
