### ISSUE TITLE
exporting hfuns

### ISSUE THREAD

**Issue by untoreh** [tlienart/Franklin.jl#894]
why doesn't franklin pick up these hfuns defined in an external module?
```julia
function export_hfuncs(mod)
    for sym in names(@__MODULE__; all=true)
        if startswith(string(sym), "hfun_")
            @eval $mod, export $sym
        end
    end
end
```

**Comment by tlienart** [comment]
you'll need to help me out a bit more here; what are you trying to do? do you want to define your `hfun*` in a module that is defined somewhere in your site folder?

(my intuition this far is that the limitation is not on the Franklin side; there's nothing specific in Franklin that blocks access to specific modules etc, likely this is more a Julia question).

**Comment by untoreh** [comment]
>  likely this is more a Julia question).
mmh probably. 
I was trying to use functions from an external module. That snippet works if the module is top level, but if it is a submodule, such that it is loaded from within the top module, i just have to import the submodule like `using Mod.Sub`.
