### ISSUE TITLE
Unexpected leading spaces in parsed `\newcommand` arguments

### ISSUE THREAD

**Issue by adigitoleo** [tlienart/Franklin.jl#903]
Hi, thanks for the awesome package.

I've noticed that the LaTeX parser inserts leading spaces into the html in some cases. Example below.

From `config.md`:

```
\newcommand{\figure}[4]{
~~~
<a id="#2"></a>
<figure style="width: #1; margin-left: 0; margin-right: 0; padding: 0">
<img src="!#4" alt="#2" width="100%"/>
<figcaption style="text-align: center">~~~#3~~~</figcaption>
</figure>
~~~
}
```

Used in the markdown like this:
```
\figure{40%}{just-a-figure}{
    This is just a figure with a caption and an anchor.
}{/assets/favicon.png}
```

And the resulting html:
```
<a id=" just-a-figure"></a>
<figure style="width:  40%; margin-left: 0; margin-right: 0; padding: 0">
<img src="/assets/favicon.png" alt=" just-a-figure" width="100%"/>
<figcaption style="text-align: center"> This is just a figure with a caption and an anchor.</figcaption>
</figure>
```

In this case, there are leading spaces in `id` and `alt`, which means I can't link to the anchor. I also tried doing things like `<a id="~~~#2~~~"></a>` but got the same result.

I will have to look at the latex parser more to figure out how this could be fixed. I wonder if there are any ideas?

**Comment by tlienart** [comment]
Hello! Yes this is on purpose but you can force it to not do that (when you know it's not ambiguous and you don't want a spurious white space) by using `!#1` (there's a bit more of an explanation in the doc on commands) 

The next version won't require this distinction but it's not quite ready yet ;-)
