### ISSUE TITLE
Fenced html block with &quot; is broken

### ISSUE THREAD

**Issue by kescobo** [tlienart/Franklin.jl#917]
Loading up a brand new site and adding:

````
```html
<h1>I&#039;m getting closer
```

```html
<h1> Hmm... &quot;something is up
```
````

![image](https://user-images.githubusercontent.com/3502975/139738242-ce05aae4-9dba-4cd3-8232-31549fc80e7a.png)

I haven't tried other sequences like that, but any html block containing `&quot;` seems to get rendered as actual html rather than fenced html code.

**Comment by tlienart** [comment]
Haha that's a funny corner case and a good catch. I can reproduce and was scratching my head a bit as to why this is but actually the answer is simple: in the case of HTML code, exactly to **prevent** what you're seeing, there's a sequence of escaping/un-escaping of the code. But to avoid escaping code that has _already_ been escaped, there is a function `is_html_escaped` that checks whether the code looks like it's been escaped. 

That code checks whether there are occurrences of `&lt;`, `&gt;`, `&quot;` or `&amp;` and if so, indicates that the code has been escaped and doesn't escape it further. You're hitting this with `&quot`!

I can strengthen that condition a bit to check that there is no `<` (which wouldn't occur in escaped HTML). It's not perfect but it'll prevent what you're seeing.

(0.10.63 will have this)
