### ISSUE TITLE
Hide (but execute) code in literate notebooks with Literate.jl syntax

### ISSUE THREAD

**Issue by kescobo** [tlienart/Franklin.jl#918]
I'm not sure there's an easy fix for this, (and it's a small thing really) but it would be great to be able to use `Literate.jl` syntax to hide code. At the moment, lines followed by `#hide` are hidden, but not evaluated, I'm guessing because Franklin is depending on the markdown output of `Literate.jl`, in which these lines don't show up. Eg. 

```julia
cd(joinpath(@__DIR__, "_literate")) #hide
using Pkg #hide
Pkg.activate(".") #hide
Pkg.instantiate() #hide
```

doesn't work, whereas using Franklin.jl syntax

```julia
cd(joinpath(@__DIR__, "_literate")) # hide
using Pkg # hide
Pkg.activate(".") # hide
Pkg.instantiate() # hide
```

and 

```julia
##hideall
cd(joinpath(@__DIR__, "_literate", "webeasties"))
using Pkg
Pkg.activate(".")
Pkg.instantiate()
```

**do** work, but then these lines aren't hidden if the same file is processed directly using `Literate.jl`. (The double hash on `##hideall` is required, with only one, it gets rendered by literate.jl as regular text rather than a julia comment)

**Comment by tlienart** [comment]
ah it's interesting 🤔 there's some clash between the `#hide` of Literate and the hide of Franklin...

I think there's a simple hack that would get us around this. To explain what's going on the steps are:

1. Literate-like file is provided
1. Franklin takes it, uses `Literate.markdown(...)` to make it into a Markdown-like file with a few changes and parses that Markdown to produce HTML

In step (2) the `#hide` are picked up by `Literate.markdown` which takes out those lines and so Franklin doesn't see them (and so doesn't execute them).

The hack is that we could just insert a step which looks for `#hide` and replaces them with `# hide` before the `Literate.markdown` 😄 

I'll try this now and if all goes well will bring this in; thanks for opening an issue, it's definitely a bug!

**Comment by tlienart** [comment]
Yeah that works, I'll bring this in in a patch release, please test it and let me know whether that works for you
