### ISSUE TITLE
inline svg url not working with Franklin because changed by compression

### ISSUE THREAD

**Issue by schlichtanders** [tlienart/Franklin.jl#922]
On Franklin server everything just works, but when deploying to gitlab, my background heropatterns (svg images inlined into background-image: url(...)) just don't show up.

Inspecting the issue it turns out that something in the pipeline deleted the surrounding quotes. Unbelievable...

So on my local system I have
```
background-image: url("data:image/svg+xml,...");
```
which somehow ends up on gitlab pages as 

```
background-image: url(data:image/svg+xml,...);
```
no surrounding quotes any longer.

Any help is highly appreciated, as this seems to be due to the standard Franklin gitlab pipeline.

**Comment by schlichtanders** [comment]
Turning off `minify` fixed this issue as well.
See https://github.com/tlienart/Franklin.jl/issues/921#issuecomment-962938930

I would vote for turning off minify by default for everyone.

**Comment by tlienart** [comment]
yes so as per other issue, minification will be turned off for everyone (prerendering as well btw even though it causes much fewer issues)
