### ISSUE TITLE
Dead links in RSS docs

### ISSUE THREAD

**Issue by mcognetta** [tlienart/Franklin.jl#930]
On the [RSS doc page](https://franklinjl.org/syntax/page-variables/#rss) there are a number of dead links:

At the very bottom:

> For an example, see this mirror of the Julia blog posts with:
> 
> the config file
> an example of page.

Both links are to deleted pages.

Then, the RSS dedicated page, [here](https://franklinjl.org/syntax/rss/), is empty. It is linked to in the following snippet:

> For more information about generating an RSS feed, see the dedicated RSS page.

**Comment by mcognetta** [comment]
Ah, I believe some (all?) of these are fixed in #926, but they haven't been deployed to a version. If that is the case, I will close this issue.

**Comment by tlienart** [comment]
ah thanks for this, Yes #926 fixes everything but I hadn't realised the build failed due to some bug with TikzPictures; will investigate and fix this. Thanks @mcognetta

**Comment by tlienart** [comment]
fixed now + bug report filed @ TikzCD (https://github.com/JuliaTeX/TikzCDs.jl/issues/8)
