### ISSUE TITLE
Latex formula is not displaying correctly

### ISSUE THREAD

**Issue by gorbatschow** [tlienart/Franklin.jl#941]
Hi! Looks like a bug, this formula
`$${a_i} = \sum\limits_{j = 0}^3 {{{\left( {{b_i}} \right)}_j}} {P^j}$$`
causes warning
```
 A block '{{b_i}} ...}}' was found but the name 'b_i}}' does
│ not correspond to a built-in block or hfun nor does it match anything
│ defined in 'utils.jl'. It might have been misspelled.
│ 
│ Relevant pointers:
│ - page variables and {{...}} blocks: https://franklinjl.org/syntax/page-variables/
│ - h-functions (hfun) and lx-functions: https://franklinjl.org/syntax/utils/
```
and  it is not displaying correctly.

**Comment by tlienart** [comment]
Hello!

In Franklin double braces mean something specific and so you hit the case where this is ambiguous, if you add white spaces between the braces so that you don't have `{{...}}` but `{ {` and `} }` the warning and issue should go away

**Comment by gorbatschow** [comment]
Ok, thanks, solved my problem.
