### ISSUE TITLE
CSS fails to load

### ISSUE THREAD

**Issue by Tobias-Thomas** [tlienart/Franklin.jl#943]
When publishing my site via github pages, the css fails to load.
It is a personal webpage, and to make sure, I didn't fail anything, I just copied the personal webpage example from the [Deplaying you website](https://franklinjl.org/workflow/deploy/) part of the documentation.
Link to the [webpage](https://tobias-thomas.github.io/) and to the [repository](https://github.com/Tobias-Thomas/tobias-thomas.github.io).
Using the local webserver, the page look perfectly fine.
Does anyone see, what my mistake is?

Thanks for any help!

**Comment by tlienart** [comment]
Your site is being loaded off the master branch.

Please go to your Repo settings, click Pages, select the `gh-pages` branch, wait a bit and it will be fine.

**Comment by tlienart** [comment]
Further than this it looks like no actual deployment happens, are Github actions enabled on that repository?

**Comment by Tobias-Thomas** [comment]
Hmm, actions are enabled, yet it seems that the only action, that ran was the default (Jekyll) one for personal web pages (see images below).
Do you know how I tell github not to use that one and instead the one defined in deploy.yml?
Also switching to the "Allow local actions only" setting did not help.
![all_actions](https://user-images.githubusercontent.com/39030885/150683972-cd92fe0f-0981-42ea-8fb7-661879c05a04.png)
![that_job](https://user-images.githubusercontent.com/39030885/150683975-994040eb-534b-4f0f-86aa-773082f39e4d.png)

**Comment by tlienart** [comment]
can you go to https://github.com/Tobias-Thomas/tobias-thomas.github.io/actions/workflows/deploy.yml and see if there's some button that allows you to start it manually? either that or push to the repo some dummy commit.

**Comment by tlienart** [comment]
(if you want, give me full admin rights on your repo, I'll have a look and then you can revoke my access)

**Comment by Tobias-Thomas** [comment]
Thanks, now it works!
For those not completely clear (because part of the conversation is in a pr), the two mistakes I made were
1. I had the wrong branch to trigger in the deploy.yml
2. I selected the wrong branch to show (first comment in this issue)

**Comment by tlienart** [comment]
👏 glad that it's fixed, good luck with your website!
