### ISSUE TITLE
Fix figure output paths with windows

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#956]
Hey @tlienart 

It is working now. But you would need to do the same changes in other loop as well. 
The following code in `\syntax\markdown\` does not work anymore. 
```
@@small-img
  \fig{./output/test}
@@
```

But the code following it works. i.e.: 
```
@@small-img
  \fig{./test}
@@
```

Pasting the truncated output to show how the path is now being defined :

```
candpath = "/assets/extras/plotly/code/output/plotlyex.json"
syspath = "E:\\work\\Franklin.jl-master\\Franklin.jl-master\\docs\\__site\\assets\\extras\\plotly\\code\\output\\plotlyex.json"
isfile(syspath) = true
```

EDIT:

I have edited the file io.jl so that it works for both for loops:

You can check the Forked repo in my profile https://github.com/atiyabzafar/Franklin.jl

I have checked both Markdown and Plotly figures and they seem to be working. 

EDIT2: `sinc.svg` in the page code is still not visible.

Nevermind that seems to be a different issue. the code does not seem to be saving the svg in the location.

Writing it here so that I can get back to it later.

**Error:** `// Image matching '/assets/code/code/sinc' not found. //`
**File Present at :** `\assets\code\index\code\output`

It makes sense for Franklin to generate the file at `code\index\code\output\` As index.md is the file with the code which is located in code folder.

_Originally posted by @atiyabzafar in https://github.com/tlienart/Franklin.jl/issues/928#issuecomment-1123536765_

**Comment by tlienart** [comment]
Hello @atiyabzafar, I did some changes for `lx_figalt` in line with what you suggested and with a bit more care. It's pushed on 469e6fe7 ; could you kindly try again? 

(also if the issue with `sinc.svg` is separate, please open another issue so we don't confuse this one).

thanks

**Comment by atiyabzafar** [comment]
Hey @tlienart I have checked with the new commit in the master branch. 

The plots both in `plotly` page and `markdown` page are working. It works in both my windows machine and my linux machine. So you can use this commit in next release.

<img src="https://user-images.githubusercontent.com/63765230/167998780-08e3cc4d-228d-4f39-85e6-f200922623e9.png" width="500">
<img src="https://user-images.githubusercontent.com/63765230/167998830-c9af864f-1f37-4bf9-97dd-4e00fcf6cfdb.png" width="500">

I will look into the `sinc.svg' issue and if needed open another issue with it. Interestingly I saw the image was missing in both windows and linux machine.

**Comment by tlienart** [comment]
Ok great, I'll do a patch release with this then, and yeah sounds good about the sinc issue, thanks!
