### ISSUE TITLE
Permalink support?

### ISSUE THREAD

**Issue by pranphy** [tlienart/Franklin.jl#961]
I am migrating from another static site generator and most of my `.md` files are named `YYYY-mm-dd-page-slug.md`. Something like 

```
permalink: %year/%m/%slug
```
in global config would result the processed file to be generated like
```
YYYY
└── mm
    └── page-slug
        └── index.html   
```
Is something like this possible in Franklin? I am basically trying to avoid having to rename my files `YYYY-mm-dd-page-slug.md` to `YYYY/mm/page-slug.md`.

**Comment by tlienart** [comment]
Hello @pranphy, no this is not directly supported by Franklin. I think the easiest here would be for you to write a script that renames your files. 

You can set a `slug` per page but not with a pattern. You could call a function that does it automatically but this is not well supported in the current version of Franklin and would likely lead to a headache more than a working solution. The next version allows you to do this but that's not helpful to you right now.

Hope the workaround is not too cumbersome for you!
