### ISSUE TITLE
prepath not applied on plotly json when publishing

### ISSUE THREAD

**Issue by noxthot** [tlienart/Franklin.jl#967]
## Problem:
We followed this guide: https://franklinjl.org/extras/plotly/index.html
Our site is published on github.io, thus we have `prepath` set.

We include the plotly json like this:
`\figalt{Barplot showing participants per country}{/assets/pages/datascience/plot_explorative_da_country.json}`

After publishing, the json can not be found since `prepath` is not prepended. 

## Suspicion
`\figalt` and `\fig` both call `html_plotly`. This function produces the following output:
```
<div id="$id" style="$style"></div>
<script>
graphDiv = document.getElementById("$id");
plotlyPromise = PlotlyJS_json(graphDiv, '$src');
</script>
```

`$src` basically being the second argument of `\figalt` (`/assets/pages/datascience/plot_explorative_da_country.json`)

Publishing (and optimizing) calls `fix_links` which adds the `prepath` depending on this pattern:
```
const PREPATH_FIX_PAT = r"(src|href|formaction|action|url)\s*?=\s*?([\"\']?)\/"
```

But unfortunately this pattern does not apply for the previously generated code part:
```
plotlyPromise = PlotlyJS_json(graphDiv, '/assets/pages/datascience/plot_explorative_da_country.json');
```

**Comment by tlienart** [comment]
Thanks for the report and going the extra mile to correctly diagnose the problem.

I think this can be fixed by adding a `globvar("prepath")` in the plotly logic but I need to play with it a bit to check.

Will try to fix this by eow.

**Comment by tlienart** [comment]
Just released a patch with this, demo: https://tlienart.github.io/test-plotly/ , demo repo: https://github.com/tlienart/test-plotly

**Comment by noxthot** [comment]
Thanks a bunch. We will apply this patch soon.

I would have loved to create a pull request but was unsure where to fix it without breaking the architecture.

**Comment by noxthot** [comment]
Works like a charm. Thanks for the fast fix. :)

**Comment by tlienart** [comment]
Great!
