### ISSUE TITLE
LiveServer.jl is interrupted when move to another page 

### ISSUE THREAD

**Issue by KotaAihara** [tlienart/Franklin.jl#972]
I need some help.

When I move to another markdown page, such as menu1, menu2, LiveServer.jl i is shut down.  I used default template named "pure-sm". Do you have any solutions?

**Comment by tlienart** [comment]
Hello @KotaAihara could you report your pkg status and in particular whether you're using LiveServer 0.9.2 please?

**Comment by KotaAihara** [comment]
Thank you for reply 
I did not installed LiveServer.jl . I have only installed Franklin.jl. Should I use LiveServer 0.92?


---- Here is my terminal ---------------
(@v1.8) pkg> status LiveServer
No Matches in `~/.julia/environments/v1.8/Project.toml`


julia> using LiveServer
 │ Package LiveServer not found, but a package named LiveServer is available
 │ from a registry. 
 │ Install package?

**Comment by tlienart** [comment]
Could you do `add LiveServer` and check that the installation shows 0.9.2?

Long story short: no you don't need to install LiveServer in theory but there were some recent updates on it that may have caused you to have a bad dependency if you have not recently updated your packages. If you explicitly add LiveServer it should fix the problem.

**Comment by tlienart** [comment]
And now with the the realease of LiveServer 1 and F 0.10.77, this should all be fixed (assuming you just `up` and you won't need to explicitly install LiveServer).

I'll close this for now but please re-open with details if there's something that still looks wrong.
