### ISSUE TITLE
How to change `blog-name`?

### ISSUE THREAD

**Issue by eigenvivek** [tlienart/Franklin.jl#974]
Where is the class `blog-name` specified in the markdown? I can't find it in any of the files, and the blog-name is showing up as "Basic Template". Thank you!

**Comment by tlienart** [comment]
Hello @eigenvivek, welcome to Franklin!

The `blog-name` is in the layout: https://github.com/tlienart/FranklinTemplates.jl/blob/fed3d61a9f789096b3dae6778c39925dcebda879/src/templates/basic/_layout/header.html ; the CSS is in basic.css: https://github.com/tlienart/FranklinTemplates.jl/blob/fed3d61a9f789096b3dae6778c39925dcebda879/src/templates/basic/_css/basic.css#L45-L57

To change the blog name, you would edit the file `_layout/header.html`; I would suggest you have a look at [this page in the docs](https://franklinjl.org/workflow/structure/) to get a clearer idea of how pages are constructed (what's from the markdown and what's from the layout)

**Comment by eigenvivek** [comment]
Thank you! I figured it out and have converted my website to a Franklin backend. Looks great!
