### ISSUE TITLE
Gallery generation?

### ISSUE THREAD

**Issue by Moelf** [tlienart/Franklin.jl#979]
https://github.com/cbenning/fussel

https://github.com/saimn/sigal

we could probably use some existing JS library

**Comment by tlienart** [comment]
Nice, note that the first one (fussel) you can use it right now with a code cell that calls python via PyCall (or shells out); and you can post process the output (to place things in the appropriate directory).

To get an integrated solution, I wonder whether it wouldn't be better to have something like `PhotoGallery.jl` which does something similar as to what fussel does and insert the HTML output within a Franklin page.
