### ISSUE TITLE
Unable to set `div_content` with local page variable

### ISSUE THREAD

**Issue by stanvanlier** [tlienart/Franklin.jl#983]
According to the docs, the global page variable `div_content` should be overwritten if set as local page variable, but this does not happen.

I'm guessing this can easily be fixed by using `locvar` instead of `globvar` in the `build_page` method on [src/manager/write_page.jl](../blob/6f24bef91a256731ca7a3609e4b777fe71594200/src/manager/write_page.jl)

The new `content_class` variable does also not support setting it from a local page.

**Comment by tlienart** [comment]
Hello @stanvanlier, yes I think all these https://github.com/tlienart/Franklin.jl/blob/6f24bef91a256731ca7a3609e4b777fe71594200/src/manager/write_page.jl#L12-L17 could be switched to `locvar` indeed as these should also be controllable from an individual page. 

Would you mind opening a PR for this?
Thanks!
