### ISSUE TITLE
Failed to deploy to GitLab

### ISSUE THREAD

**Issue by newptcai** [tlienart/Franklin.jl#990]
The pipeline failed when the follow is executed

```
julia --project=@. -e 'import Pkg; Pkg.instantiate(); using NodeJS; run(`$(npm_cmd()) install highlight.js`); using Franklin; optimize()'
```
The error is
```
ERROR: MethodError: no method matching joinpath(::Nothing)
```
See details [here](https://gitlab.com/newptcai/newptcai.gitlab.io/-/jobs/3463974530).

**Comment by tlienart** [comment]
did this use to work before and stopped working all of a sudden? what did you do between the time it did work and now?

**Comment by newptcai** [comment]
I have not updated anything package in Franklin.
It works well locally without any problem.
So I guess it's problem on GitLab side, or something wrong with the Docker image.

Besides what you suggested, is it possible to just manually push the `__site` to GitLab?

**Comment by tlienart** [comment]
could you try the `Pkg.add` without Manifest so we can rule this out? 

> Besides what you suggested, is it possible to just manually push the __site to GitLab?

yes, what you can do is:

1. run the command locally
2. push to gitlab including the `__site` folder
3. have a pipeline that does `mv __site public` so basically this one https://gitlab.com/newptcai/newptcai.gitlab.io/-/blob/master/.gitlab-ci.yml but without https://gitlab.com/newptcai/newptcai.gitlab.io/-/blob/master/.gitlab-ci.yml#L10-13

**Comment by newptcai** [comment]
Thanks a lot. Using `Pkg.add` resolves the issue.
